# Lab 2 — Baseline com múltiplos datasets

Neste notebook vamos rodar o mesmo pipeline de baseline para 4 datasets diferentes.

A ideia é simples: para cada dataset na lista `keys_to_run`, o código vai:
1. baixar e carregar os dados
2. limpar valores ausentes e aplicar `dropna` antes do split
3. treinar dois modelos baseline (um linear e um de floresta)
4. imprimir as métricas e salvar os resultados

No final, uma tabela compara os melhores modelos de cada dataset.

In [9]:
import os

base = r"C:\Users\kslima\mestrado\cienciaDados\atv2\jenga\src\jenga"

for root, dirs, files in os.walk(base):
    print(root)
    for d in dirs:
        print("  [DIR]", d)
    for f in files:
        print("  [FILE]", f)

C:\Users\kslima\mestrado\cienciaDados\atv2\jenga\src\jenga
  [DIR] corruptions
  [DIR] evaluation
  [DIR] tasks
  [DIR] __pycache__
  [FILE] basis.py
  [FILE] utils.py
  [FILE] __init__.py
C:\Users\kslima\mestrado\cienciaDados\atv2\jenga\src\jenga\corruptions
  [DIR] __pycache__
  [FILE] generic.py
  [FILE] image.py
  [FILE] numerical.py
  [FILE] text.py
  [FILE] __init__.py
C:\Users\kslima\mestrado\cienciaDados\atv2\jenga\src\jenga\corruptions\__pycache__
  [FILE] generic.cpython-39.pyc
  [FILE] __init__.cpython-39.pyc
C:\Users\kslima\mestrado\cienciaDados\atv2\jenga\src\jenga\evaluation
  [FILE] basis.py
  [FILE] corruption_impact.py
  [FILE] schema_stresstest.py
  [FILE] schema_validation.py
C:\Users\kslima\mestrado\cienciaDados\atv2\jenga\src\jenga\tasks
  [FILE] income.py
  [FILE] openml.py
  [FILE] reviews.py
  [FILE] shoes.py
C:\Users\kslima\mestrado\cienciaDados\atv2\jenga\src\jenga\__pycache__
  [FILE] basis.cpython-39.pyc
  [FILE] utils.cpython-39.pyc
  [FILE] __init__.cpython-39.pyc

In [10]:
# 1) Bibliotecas
from __future__ import annotations

import json
import zipfile
from pathlib import Path
from urllib.request import urlretrieve

import numpy as np
import pandas as pd

from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.linear_model import LogisticRegression, Ridge
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score,
    mean_absolute_error,
    mean_squared_error,
    r2_score,
)
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

from sklearn.impute import SimpleImputer, KNNImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.exceptions import ConvergenceWarning
import warnings
warnings.filterwarnings('ignore', category=ConvergenceWarning)

from sklearn.preprocessing import FunctionTransformer, OneHotEncoder

import sys
from pathlib import Path

import sys
from pathlib import Path

BASE_DIR = Path().resolve()
JENGA_PATH = BASE_DIR / "jenga" / "src"

sys.path.insert(0, str(JENGA_PATH))

import jenga
print("Jenga path:", jenga.__file__)

from jenga.corruptions.generic import MissingValues
print("IMPORT OK")

from jenga.corruptions.generic import MissingValues

import inspect
print(inspect.signature(MissingValues))

from joblib import Parallel, delayed

from lightgbm import LGBMClassifier, LGBMRegressor

import miceforest as mf

# Suprimir warnings verbosos do LightGBM e sklearn em produção

import logging
warnings.filterwarnings('ignore', category=UserWarning, module='lightgbm')
warnings.filterwarnings('ignore', category=UserWarning, module='sklearn')
warnings.filterwarnings('ignore', category=FutureWarning)
logging.getLogger('lightgbm').setLevel(logging.ERROR)

Jenga path: C:\Users\kslima\mestrado\cienciaDados\atv2\jenga\src\jenga\__init__.py
IMPORT OK
(column, fraction, na_value=nan, missingness='MCAR')

In [11]:
# 2) Metadados dos datasets e funcoes  que nos ajudam a baixar, extrair e normalizar os dados

DATASETS = {
    "adult": {"task": "classification", "target": "income"},
    "bank_marketing": {"task": "classification", "target": "y"},
    "air_quality_uci": {"task": "regression", "target": "C6H6(GT)"},
    "communities_crime": {"task": "regression", "target": "ViolentCrimesPerPop"},
}

# Tokens que representam valores ausentes
NUMERIC_MISSING_VALUES = [-200, -200.0]

STRING_MISSING_VALUES = [
    "?", " ?", "? ", "NA", "N/A", "na", "n/a", "NaN", "nan", "", " ",
    "unknown", "Unknown", "-200",
]


def make_one_hot_encoder() -> OneHotEncoder:
    try:
        return OneHotEncoder(handle_unknown="ignore", sparse_output=True)
    except TypeError:
        return OneHotEncoder(handle_unknown="ignore", sparse=True)


def download_file(url: str, output_path: Path) -> Path:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    if not output_path.exists():
        print(f"[download] {url}")
        urlretrieve(url, output_path)
    else:
        print(f"[cache] {output_path}")
    return output_path


def unzip_file(zip_path: Path, extract_dir: Path) -> Path:
    extract_dir.mkdir(parents=True, exist_ok=True)
    marker = extract_dir / ".extracted"
    if not marker.exists():
        print(f"[extract] {zip_path}")
        with zipfile.ZipFile(zip_path, "r") as zf:
            zf.extractall(extract_dir)
        marker.write_text("ok\n", encoding="utf-8")
    else:
        print(f"[cache] {extract_dir}")
    return extract_dir


def normalize_missing_values(df: pd.DataFrame) -> pd.DataFrame:
    """Substitui tokens de missing por NaN, coluna a coluna, respeitando o dtype.
    
    - Colunas numericas: substitui -200 e -200.0
    - Colunas de texto: faz strip e substitui tokens como '?', 'unknown', etc.
    Essa abordagem evita erros do pandas 2.x ao misturar int e str no replace().
    -- TODO: verificar se tem outros simbolos estranhos nos dataset da atividade (pedir par aos alunos checarem isso)
    """
    df = df.copy()
    for col in df.columns:
        if pd.api.types.is_numeric_dtype(df[col]):
            df[col] = df[col].replace(NUMERIC_MISSING_VALUES, np.nan)
        else:
            df[col] = df[col].astype("string").str.strip()
            df[col] = df[col].replace(STRING_MISSING_VALUES, pd.NA)
    return df
def to_native_dtypes(df: pd.DataFrame) -> pd.DataFrame:
    """
    Converte TODAS as colunas com dtypes de extensão do pandas para tipos nativos,
    eliminando pd.NA que causa 'boolean value of NA is ambiguous'.
    Cobre: StringDtype, BooleanDtype, Int8/16/32/64Dtype, Float32/64Dtype, etc.
    """
    df = df.copy()
    for col in df.columns:
        dtype = df[col].dtype
        # Detecta qualquer ExtensionDtype (StringDtype, BooleanDtype, Int64Dtype, etc.)
        if not isinstance(dtype, np.dtype):
            if hasattr(dtype, "numpy_dtype"):
                # Tipos numéricos nullable (Int64, Float64) → float64 nativo
                # (float64 aceita np.nan; int não aceita, por isso usa float)
                try:
                    df[col] = df[col].astype(object).where(
                        df[col].notna(), other=np.nan
                    ).astype(float)
                    continue
                except (ValueError, TypeError):
                    pass
            # Todos os outros (StringDtype, BooleanDtype, CategoricalDtype, etc.) → object
            df[col] = df[col].astype(object).where(df[col].notna(), other=None)
    return df

def _to_object_dtype(X):
    if hasattr(X, "astype"):
        return X.astype(object)
    return X

def _to_str_dtype(X):
    return X.astype(str)

In [12]:
# 3) Funcoes. para baixar os datasets automaticamente

# fiz alguns pequenos ajustes caso a caso para facilitar a leitura e evitar erros de parsing

def load_adult(data_dir: Path) -> tuple[pd.DataFrame, str, str]:
    base = data_dir / "adult"
    data_file = download_file(
        "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data",
        base / "adult.data",
    )
    test_file = download_file(
        "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.test",
        base / "adult.test",
    )

    columns = [
        "age", "workclass", "fnlwgt", "education", "education_num", "marital_status",
        "occupation", "relationship", "race", "sex", "capital_gain", "capital_loss",
        "hours_per_week", "native_country", "income",
    ]

    train_df = pd.read_csv(data_file, header=None, names=columns, skipinitialspace=True, na_values=["?", " ?"])
    test_df = pd.read_csv(test_file, header=None, names=columns, skiprows=1, skipinitialspace=True, na_values=["?", " ?"])

    df = pd.concat([train_df, test_df], ignore_index=True)
    df["income"] = df["income"].astype(str).str.replace(".", "", regex=False).str.strip()
    return df, "income", "classification"


def load_bank_marketing(data_dir: Path) -> tuple[pd.DataFrame, str, str]:
    base = data_dir / "bank_marketing"
    zip_path = download_file(
        "https://archive.ics.uci.edu/ml/machine-learning-databases/00222/bank.zip",
        base / "bank.zip",
    )
    extract_dir = unzip_file(zip_path, base / "extracted")
    df = pd.read_csv(extract_dir / "bank-full.csv", sep=";")
    return df, "y", "classification"


def load_air_quality_uci(data_dir: Path) -> tuple[pd.DataFrame, str, str]:
    base = data_dir / "air_quality_uci"
    zip_path = download_file(
        "https://archive.ics.uci.edu/ml/machine-learning-databases/00360/AirQualityUCI.zip",
        base / "AirQualityUCI.zip",
    )
    extract_dir = unzip_file(zip_path, base / "extracted")
    candidates = list(extract_dir.rglob("AirQualityUCI.csv"))
    if not candidates:
        raise FileNotFoundError("Nao encontrei AirQualityUCI.csv dentro do zip.")

    df = pd.read_csv(candidates[0], sep=";", decimal=",")
    df = df.dropna(axis=1, how="all").dropna(axis=0, how="all")
    for col in ["Date", "Time"]:
        if col in df.columns:
            df = df.drop(columns=[col])
    return df, "C6H6(GT)", "regression"


def load_communities_crime(data_dir: Path) -> tuple[pd.DataFrame, str, str]:
    base = data_dir / "communities_crime"
    data_file = download_file(
        "https://archive.ics.uci.edu/ml/machine-learning-databases/communities/communities.data",
        base / "communities.data",
    )
    df = pd.read_csv(data_file, header=None, na_values=["?"])

    cols = [f"col_{i}" for i in range(df.shape[1])]
    cols[-1] = "ViolentCrimesPerPop"
    df.columns = cols
    # colunas  com muito problema
    df = df.drop(columns=[c for c in ["col_0", "col_1", "col_2", "col_3", "col_4"] if c in df.columns])
    return df, "ViolentCrimesPerPop", "regression"


def load_dataset(key: str, data_dir: Path) -> tuple[pd.DataFrame, str, str]:
    if key == "adult":
        return load_adult(data_dir)
    if key == "bank_marketing":
        return load_bank_marketing(data_dir)
    if key == "air_quality_uci":
        return load_air_quality_uci(data_dir)
    if key == "communities_crime":
        return load_communities_crime(data_dir)
    raise ValueError(f"Key desconhecida: {key}")

def inject_mcar(df: pd.DataFrame, missing_rate: float, random_state: int = 42) -> pd.DataFrame:
    corruption = MissingValues(missing_rate=missing_rate, random_state=random_state)
    df_corrupted = corruption.transform(df.copy())
    return df_corrupted


def inject_mar(df: pd.DataFrame, missing_rate: float, random_state: int = 42) -> pd.DataFrame:
    df_corrupted = df.copy()

    np.random.seed(random_state)

    numeric_cols = df.select_dtypes(include=[np.number]).columns

    if len(numeric_cols) == 0:
        return inject_mcar(df, missing_rate, random_state)

    ref_col = numeric_cols[0]

    threshold = df[ref_col].median()

    mask = df[ref_col] > threshold

    for col in df.columns:
        prob = np.random.rand(len(df))
        df_corrupted.loc[mask & (prob < missing_rate), col] = np.nan

    return df_corrupted


def inject_mnar(df: pd.DataFrame, missing_rate: float, random_state: int = 42) -> pd.DataFrame:
    df_corrupted = df.copy()

    np.random.seed(random_state)

    numeric_cols = df.select_dtypes(include=[np.number]).columns

    if len(numeric_cols) == 0:
        return inject_mcar(df, missing_rate, random_state)

    for col in numeric_cols:
        threshold = df[col].median()
        mask = df[col] > threshold

        prob = np.random.rand(len(df))
        df_corrupted.loc[mask & (prob < missing_rate), col] = np.nan

    return df_corrupted

In [13]:
# 4) Funcoes para separar treino e teste

FAST_MODE            = False
MISSING_MECHANISMS   = ["MCAR", "MAR", "MNAR"]
MISSING_RATES        = [0.01, 0.05, 0.10, 0.15, 0.20, 0.25, 0.30]
N_ESTIMATORS         = 50   # Random Forest e modelos básicos
N_ESTIMATORS_LGBM    = 100  # LightGBM precisa de mais árvores (leaf-wise)
MAX_ITER_IMPUTER     = 5
SAMPLE_SIZE          = None

def split_X_y(df: pd.DataFrame, target: str) -> tuple[pd.DataFrame, pd.Series]:
    if target not in df.columns:
        raise ValueError(f"Target '{target}' nao esta no dataset.")
    return df.drop(columns=[target]), df[target]


def build_preprocessor(X: pd.DataFrame, scale_numeric: bool) -> ColumnTransformer:
    numeric_cols = X.select_dtypes(include=[np.number]).columns.tolist()
    categorical_cols = [c for c in X.columns if c not in numeric_cols]

    num_pipeline = Pipeline([
        ("imputer", SimpleImputer(strategy="mean")),
        ("scaler", StandardScaler() if scale_numeric else "passthrough"),
    ])

    cat_pipeline = Pipeline([
        ("to_object", FunctionTransformer(_to_object_dtype)),  # função nomeada
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("to_str", FunctionTransformer(_to_str_dtype)),        # função nomeada
        ("onehot", make_one_hot_encoder()),
    ])

    transformers = []
    if numeric_cols:
        transformers.append(("num", num_pipeline, numeric_cols))
    if categorical_cols:
        transformers.append(("cat", cat_pipeline, categorical_cols))

    return ColumnTransformer(transformers=transformers, remainder="drop")


def build_preprocessor_with_imputer(
    X: pd.DataFrame,
    imputer_type: str,
    scale_numeric: bool
) -> ColumnTransformer:
    """
    imputer_type aceito:
      "dropna"        – sem imputação (linhas com NaN já foram removidas antes)
      "simple_mean"   – SimpleImputer(strategy="mean")
      "simple_median" – SimpleImputer(strategy="median")
      "simple_freq"   – SimpleImputer(strategy="most_frequent")
      "simple_const"  – SimpleImputer(strategy="constant", fill_value=0)
      "knn_3"         – KNNImputer(n_neighbors=3)
      "knn_5"         – KNNImputer(n_neighbors=5)
      "knn_7"         – KNNImputer(n_neighbors=7)
      "iterative"     – IterativeImputer
    """
    numeric_cols = X.select_dtypes(include=[np.number]).columns.tolist()
    categorical_cols = [c for c in X.columns if c not in numeric_cols]

    # ── imputador numérico ──────────────────────────────────────────────────
    if imputer_type in ("dropna", "miceforest"):
        # dados já vieram sem NaN (dropna removeu linhas; miceforest já imputou)
        num_imputer = SimpleImputer(strategy="mean")
    elif imputer_type == "simple_mean":
        num_imputer = SimpleImputer(strategy="mean")
    elif imputer_type == "simple_median":
        num_imputer = SimpleImputer(strategy="median")
    elif imputer_type == "simple_freq":
        num_imputer = SimpleImputer(strategy="most_frequent")
    elif imputer_type == "simple_const":
        num_imputer = SimpleImputer(strategy="constant", fill_value=0)
    elif imputer_type.startswith("knn_"):
        k = int(imputer_type.split("_")[1])
        num_imputer = KNNImputer(n_neighbors=k)
    elif imputer_type == "iterative":
        num_imputer = IterativeImputer(
            max_iter=MAX_ITER_IMPUTER,
            initial_strategy="mean",
            random_state=0,
        )
    else:
        raise ValueError(f"Imputer desconhecido: {imputer_type}")

    num_pipeline = Pipeline([
        ("imputer", num_imputer),
        ("scaler", StandardScaler() if scale_numeric else "passthrough"),
    ])

    cat_pipeline = Pipeline([
        ("to_object", FunctionTransformer(_to_object_dtype)),
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("to_str", FunctionTransformer(_to_str_dtype)),
        ("onehot", make_one_hot_encoder()),
    ])

    transformers = []
    if numeric_cols:
        transformers.append(("num", num_pipeline, numeric_cols))
    if categorical_cols:
        transformers.append(("cat", cat_pipeline, categorical_cols))

    return ColumnTransformer(transformers=transformers, remainder="drop")


def inject_missing_values(df, target, mechanism, missing_rate, random_state):
    df_corrupted = df.copy()

    y = df_corrupted[target]
    X = df_corrupted.drop(columns=[target]).copy()

    X_original = X.copy()

    for col in X.columns:
        corruption = MissingValues(
            column=col,
            fraction=missing_rate,
            missingness=mechanism
        )
        X = corruption.transform(X)

    null_mask = X.isnull() & X_original.notna()

    df_final = X.copy()
    df_final[target] = y

    return df_final, X_original, null_mask 


def compute_imputation_quality(
    X_original: pd.DataFrame,
    X_imputed: pd.DataFrame,
    null_mask: pd.DataFrame,
) -> dict:
    """
    Compara valores imputados com os valores originais apenas
    nas posições onde nulos foram injetados artificialmente.

    Retorna:
      - mae_num  : MAE médio nas colunas numéricas
      - rmse_num : RMSE médio nas colunas numéricas
      - acc_cat  : Acurácia média nas colunas categóricas
      - n_num    : total de posições numéricas avaliadas
      - n_cat    : total de posições categóricas avaliadas
    """
    numeric_cols     = X_original.select_dtypes(include=[np.number]).columns
    categorical_cols = [c for c in X_original.columns if c not in numeric_cols]

    mae_list, rmse_list, acc_list = [], [], []
    n_num, n_cat = 0, 0

    for col in numeric_cols:
        mask = null_mask[col] if col in null_mask.columns else pd.Series(False, index=X_original.index)
        idx  = mask[mask].index
        if len(idx) == 0:
            continue
        orig = pd.to_numeric(X_original.loc[idx, col], errors="coerce").dropna()
        imp  = pd.to_numeric(X_imputed.loc[orig.index, col],  errors="coerce").dropna()
        common = orig.index.intersection(imp.index)
        if len(common) == 0:
            continue
        o, i = orig[common].values, imp[common].values
        mae_list.append(mean_absolute_error(o, i))
        rmse_list.append(np.sqrt(mean_squared_error(o, i)))
        n_num += len(common)

    for col in categorical_cols:
        mask = null_mask[col] if col in null_mask.columns else pd.Series(False, index=X_original.index)
        idx  = mask[mask].index
        if len(idx) == 0:
            continue
        orig = X_original.loc[idx, col].dropna().astype(str)
        imp  = X_imputed.loc[orig.index, col].fillna("__missing__").astype(str)
        common = orig.index.intersection(imp.index)
        if len(common) == 0:
            continue
        acc_list.append(accuracy_score(orig[common], imp[common]))
        n_cat += len(common)

    return {
        "imp_mae_num":  float(np.mean(mae_list))  if mae_list  else None,
        "imp_rmse_num": float(np.mean(rmse_list)) if rmse_list else None,
        "imp_acc_cat":  float(np.mean(acc_list))  if acc_list  else None,
        "imp_n_num":    n_num,
        "imp_n_cat":    n_cat,
    }

def impute_with_miceforest(
    X_train: pd.DataFrame,
    X_test: pd.DataFrame,
    random_state: int = 42,
    iterations: int = 2,
    max_cols: int = 50,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Imputação com MICE + LightGBM via miceforest (método externo ao scikit-learn).

    Configuração:
      - iterations=2: 2 iterações MICE (suficiente para experimentos)
      - data_subset=0.5: usa 50% das linhas para treinar cada modelo interno
        (acelera datasets grandes sem perder qualidade significativa)
      - max_cols=50: datasets com mais colunas usam apenas as top-50 por variância
        (communities_crime tem ~100 cols e fica lento sem essa limitação)
      - Respeita o protocolo: kernel ajustado só no X_train, X_test imputado
        via impute_new_data()

    Limitações documentadas:
      - Colunas categóricas convertidas para códigos numéricos antes do kernel.
      - Em datasets com >50 colunas, apenas as 50 de maior variância são usadas
        para imputação; as demais recebem SimpleImputer(mean) como fallback.
    """
    X_train_n = to_native_dtypes(X_train.copy())
    X_test_n  = to_native_dtypes(X_test.copy())

    # miceforest v6 exige RangeIndex sequencial
    X_train_n = X_train_n.reset_index(drop=True)
    X_test_n  = X_test_n.reset_index(drop=True)

    # Converter categorias para codes numéricos
    cat_cols = X_train_n.select_dtypes(include=["object", "category"]).columns.tolist()
    for col in cat_cols:
        combined = pd.concat([X_train_n[col], X_test_n[col]], axis=0)
        cats = combined.dropna().unique()
        cat_map = {v: i for i, v in enumerate(cats)}
        X_train_n[col] = X_train_n[col].map(cat_map).astype(float)
        X_test_n[col]  = X_test_n[col].map(cat_map).astype(float)

    # Limitar colunas em datasets grandes (evita lentidão no communities_crime)
    all_cols = X_train_n.columns.tolist()
    if len(all_cols) > max_cols:
        # seleciona top-max_cols por variância (colunas mais informativas)
        variances = X_train_n.var(numeric_only=True).nlargest(max_cols)
        selected_cols = variances.index.tolist()
        remaining_cols = [c for c in all_cols if c not in selected_cols]
        print(f"[miceforest] {len(all_cols)} colunas → usando top-{max_cols} por variância")
    else:
        selected_cols  = all_cols
        remaining_cols = []

    X_tr_sel = X_train_n[selected_cols].copy()
    X_te_sel = X_test_n[selected_cols].copy()

    try:
        # API miceforest >= 6.x
        kernel = mf.ImputationKernel(
            X_tr_sel,
            random_state=random_state,
            data_subset=0.5,   # usa 50% das linhas por iteração — acelera sem perder qualidade
        )
        kernel.mice(iterations, verbose=False)

        X_train_imp_sel = kernel.complete_data(dataset=0)
        new_data_kernel = kernel.impute_new_data(
            new_data=X_te_sel,
            random_state=random_state,
        )
        X_test_imp_sel = new_data_kernel.complete_data(dataset=0)

    except Exception as e:
        err_msg = str(e) if str(e).strip() else type(e).__name__
        print(f"  [miceforest] fallback SimpleImputer ({err_msg})")
        from sklearn.impute import SimpleImputer
        imp = SimpleImputer(strategy="mean")
        X_train_imp_sel = pd.DataFrame(
            imp.fit_transform(X_tr_sel),
            columns=X_tr_sel.columns, index=X_tr_sel.index
        )
        X_test_imp_sel = pd.DataFrame(
            imp.transform(X_te_sel),
            columns=X_te_sel.columns, index=X_te_sel.index
        )

    # Reintegrar colunas restantes (imputadas com mean)
    if remaining_cols:
        from sklearn.impute import SimpleImputer
        imp_rem = SimpleImputer(strategy="mean")
        X_tr_rem = pd.DataFrame(
            imp_rem.fit_transform(X_train_n[remaining_cols]),
            columns=remaining_cols, index=X_train_n.index
        )
        X_te_rem = pd.DataFrame(
            imp_rem.transform(X_test_n[remaining_cols]),
            columns=remaining_cols, index=X_test_n.index
        )
        X_train_imp = pd.concat([X_train_imp_sel, X_tr_rem], axis=1)[all_cols]
        X_test_imp  = pd.concat([X_test_imp_sel,  X_te_rem],  axis=1)[all_cols]
    else:
        X_train_imp = X_train_imp_sel
        X_test_imp  = X_test_imp_sel

    return X_train_imp, X_test_imp


def _print_metrics(name: str, metrics: dict, task: str) -> None:
    """Imprime metricas de forma compacta e legivel."""
    if task == "classification":
        acc = metrics.get("accuracy")
        mf1 = metrics.get("macro_f1")
        wf1 = metrics.get("weighted_f1")
        if acc is None:
            print(f"     x  {name:<26} ERRO")
        else:
            bar = "#" * int(wf1 * 20) + "-" * (20 - int(wf1 * 20))
            print(f"     ok {name:<26} acc={acc:.3f}  mf1={mf1:.3f}  wf1={wf1:.3f}  [{bar}]")
    else:
        mae  = metrics.get("mae")
        rmse = metrics.get("rmse")
        r2   = metrics.get("r2")
        if r2 is None:
            print(f"     x  {name:<26} ERRO")
        else:
            bar = "#" * max(0, int(r2 * 20)) + "-" * (20 - max(0, int(r2 * 20)))
            print(f"     ok {name:<26} mae={mae:.4f}  rmse={rmse:.4f}  r2={r2:.4f}  [{bar}]")


def run_classification(X: pd.DataFrame, y: pd.Series, test_size: float, random_state: int) -> dict:

    y = pd.Series(y.to_numpy(dtype=object, na_value=np.nan), index=y.index)
    y = y.dropna()
    y = y.astype(str)
    X = X.loc[y.index]
    X = to_native_dtypes(X)  # converte todos ExtensionDtypes para nativos

    class_counts = y.value_counts()
    stratify = y if int(class_counts.min()) >= 2 else None

    X_train, X_test, y_train, y_test = train_test_split(
        X, y,
        test_size=test_size,
        random_state=random_state,
        stratify=stratify
    )

    models = {
        "logistic_regression": Pipeline([
            ("preprocess", build_preprocessor(X_train, scale_numeric=True)),
            ("model", LogisticRegression(max_iter=2000, class_weight="balanced")),
        ]),
        "random_forest": Pipeline([
            ("preprocess", build_preprocessor(X_train, scale_numeric=False)),
            ("model", RandomForestClassifier(
                n_estimators=N_ESTIMATORS, 
                random_state=random_state,
                n_jobs=1,
                class_weight="balanced_subsample",
            )),
        ]),
        "lightgbm": Pipeline([
            ("preprocess", build_preprocessor(X_train, scale_numeric=False)),
            ("model", LGBMClassifier(
                n_estimators=N_ESTIMATORS_LGBM,
                random_state=random_state,
                n_jobs=1,
                class_weight="balanced",
                verbosity=-1,
            )),
        ]),
    }

    results = {}

    for name, model in models.items():
        model.fit(X_train, y_train)
        pred = model.predict(X_test)

        metrics = {
            "accuracy": float(accuracy_score(y_test, pred)),
            "macro_f1": float(f1_score(y_test, pred, average="macro")),
            "weighted_f1": float(f1_score(y_test, pred, average="weighted")),
        }

        results[name] = metrics
        _print_metrics(name, metrics, task="classification")

    return results

def run_classification_with_imputation(
    X: pd.DataFrame,
    y: pd.Series,
    test_size: float,
    random_state: int,
    X_original: pd.DataFrame = None,
    null_mask: pd.DataFrame = None,
) -> dict:

    IMPUTERS_LIST = [
        "dropna", "simple_mean", "simple_median", "simple_freq",
        "simple_const", "knn_3", "knn_5", "knn_7", "iterative", "miceforest",
    ]

    y = pd.Series(y.to_numpy(dtype=object, na_value=np.nan), index=y.index)
    y = y.dropna()
    y = y.astype(str)
    X = X.loc[y.index].copy()
    X = to_native_dtypes(X)

    if len(y) == 0:
        raise RuntimeError("Target vazia após limpeza.")

    class_counts = y.value_counts(dropna=False)
    stratify = y if int(class_counts.min()) >= 2 else None

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=test_size, random_state=random_state, stratify=stratify
    )

    results = {}

    for imp in IMPUTERS_LIST:
        print(f"  > imputador: {imp}")

        if imp == "dropna":
            mask_train = ~X_train.isnull().any(axis=1)
            mask_test  = ~X_test.isnull().any(axis=1)
            X_tr = X_train[mask_train]
            y_tr = y_train[mask_train]
            X_te = X_test[mask_test]
            y_te = y_test[mask_test]
            if len(y_tr) == 0 or len(y_te) == 0:
                results[imp] = {}
                continue

        elif imp == "miceforest":
            X_tr_imp, X_te_imp = impute_with_miceforest(
                X_train, X_test, random_state=random_state
            )
            X_tr, y_tr = X_tr_imp, y_train
            X_te, y_te = X_te_imp, y_test

        else:
            X_tr, y_tr, X_te, y_te = X_train, y_train, X_test, y_test

        # ── qualidade da imputação ────────────────────────────────────────────
        imp_quality = {}
        if X_original is not None and null_mask is not None and imp != "dropna":
            try:
                train_idx = X_train.index
                num_cols = X_train.select_dtypes(include=[np.number]).columns.tolist()
                cat_cols = [c for c in X_train.columns if c not in num_cols]

                if imp == "miceforest":
                    X_tr_for_quality = pd.DataFrame(
                        X_tr.values, index=train_idx, columns=X_train.columns
                    )
                else:
                    # Seleciona o imputador numérico correto diretamente
                    if imp == "simple_mean":
                        num_imp = SimpleImputer(strategy="mean")
                    elif imp == "simple_median":
                        num_imp = SimpleImputer(strategy="median")
                    elif imp == "simple_freq":
                        num_imp = SimpleImputer(strategy="most_frequent")
                    elif imp == "simple_const":
                        num_imp = SimpleImputer(strategy="constant", fill_value=0)
                    elif imp.startswith("knn_"):
                        num_imp = KNNImputer(n_neighbors=int(imp.split("_")[1]))
                    elif imp == "iterative":
                        num_imp = IterativeImputer(
                            max_iter=MAX_ITER_IMPUTER, initial_strategy="mean", random_state=0
                        )
                    else:
                        num_imp = SimpleImputer(strategy="mean")

                    # Imputa numérico
                    if num_cols:
                        arr_num = num_imp.fit_transform(X_tr[num_cols])
                        X_num_imp = pd.DataFrame(arr_num, index=train_idx, columns=num_cols)
                    else:
                        X_num_imp = pd.DataFrame(index=train_idx)

                    # Imputa categórico (sempre most_frequent)
                    if cat_cols:
                        cat_imp = SimpleImputer(strategy="most_frequent")
                        arr_cat = cat_imp.fit_transform(X_tr[cat_cols].astype(object))
                        X_cat_imp = pd.DataFrame(arr_cat, index=train_idx, columns=cat_cols)
                        X_tr_for_quality = pd.concat([X_num_imp, X_cat_imp], axis=1)[X_train.columns]
                    else:
                        X_tr_for_quality = X_num_imp[X_train.columns] if num_cols else X_tr.copy()

                imp_quality = compute_imputation_quality(
                    X_original.loc[train_idx],
                    X_tr_for_quality,
                    null_mask.loc[train_idx],
                )
            except Exception as e:
                print(f"     [imp_quality erro] {imp}: {e}")
                imp_quality = {}
        # ─────────────────────────────────────────────────────────────────────

        models = {
            "logistic_regression": Pipeline([
                ("preprocess", build_preprocessor_with_imputer(X_tr, imp, True)),
                ("model", LogisticRegression(max_iter=2000, class_weight="balanced")),
            ]),
            "random_forest": Pipeline([
                ("preprocess", build_preprocessor_with_imputer(X_tr, imp, False)),
                ("model", RandomForestClassifier(
                    n_estimators=N_ESTIMATORS, max_depth=10,
                    random_state=random_state, n_jobs=1,
                    class_weight="balanced_subsample",
                )),
            ]),
            "lightgbm": Pipeline([
                ("preprocess", build_preprocessor_with_imputer(X_tr, imp, False)),
                ("model", LGBMClassifier(
                    n_estimators=N_ESTIMATORS_LGBM, max_depth=10,
                    random_state=random_state, n_jobs=1,
                    class_weight="balanced", verbosity=-1,
                )),
            ]),
        }

        results[imp] = {}

        for name, model in models.items():
            try:
                model.fit(X_tr, y_tr)
                pred = model.predict(X_te)
                metrics = {
                    "accuracy":    float(accuracy_score(y_te, pred)),
                    "macro_f1":    float(f1_score(y_te, pred, average="macro")),
                    "weighted_f1": float(f1_score(y_te, pred, average="weighted")),
                }
            except Exception as e:
                print(f"     x  {name}: {e}")
                metrics = {"accuracy": None, "macro_f1": None, "weighted_f1": None}

            metrics.update(imp_quality)
            results[imp][name] = metrics
            _print_metrics(name, metrics, task="classification")

    return results


def run_regression_with_imputation(
    X: pd.DataFrame,
    y: pd.Series,
    test_size: float,
    random_state: int,
    X_original: pd.DataFrame = None,
    null_mask: pd.DataFrame = None,
) -> dict:

    IMPUTERS_LIST = [
        "dropna", "simple_mean", "simple_median", "simple_freq",
        "simple_const", "knn_3", "knn_5", "knn_7", "iterative", "miceforest",
    ]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=test_size, random_state=random_state
    )

    results = {}

    for imp in IMPUTERS_LIST:
        print(f"  > imputador: {imp}")

        if imp == "dropna":
            mask_train = ~X_train.isnull().any(axis=1)
            mask_test  = ~X_test.isnull().any(axis=1)
            X_tr = X_train[mask_train]
            y_tr = y_train[mask_train]
            X_te = X_test[mask_test]
            y_te = y_test[mask_test]
            if len(y_tr) == 0 or len(y_te) == 0:
                results[imp] = {}
                continue

        elif imp == "miceforest":
            X_tr_imp, X_te_imp = impute_with_miceforest(
                X_train, X_test, random_state=random_state
            )
            X_tr, y_tr = X_tr_imp, y_train
            X_te, y_te = X_te_imp, y_test

        else:
            X_tr, y_tr, X_te, y_te = X_train, y_train, X_test, y_test

        # ── qualidade da imputação ────────────────────────────────────────────
        imp_quality = {}
        if X_original is not None and null_mask is not None and imp != "dropna":
            try:
                train_idx = X_train.index
                num_cols = X_train.select_dtypes(include=[np.number]).columns.tolist()
                cat_cols = [c for c in X_train.columns if c not in num_cols]

                if imp == "miceforest":
                    X_tr_for_quality = pd.DataFrame(
                        X_tr.values, index=train_idx, columns=X_train.columns
                    )
                else:
                    if imp == "simple_mean":
                        num_imp = SimpleImputer(strategy="mean")
                    elif imp == "simple_median":
                        num_imp = SimpleImputer(strategy="median")
                    elif imp == "simple_freq":
                        num_imp = SimpleImputer(strategy="most_frequent")
                    elif imp == "simple_const":
                        num_imp = SimpleImputer(strategy="constant", fill_value=0)
                    elif imp.startswith("knn_"):
                        num_imp = KNNImputer(n_neighbors=int(imp.split("_")[1]))
                    elif imp == "iterative":
                        num_imp = IterativeImputer(
                            max_iter=MAX_ITER_IMPUTER, initial_strategy="mean", random_state=0
                        )
                    else:
                        num_imp = SimpleImputer(strategy="mean")

                    if num_cols:
                        arr_num = num_imp.fit_transform(X_tr[num_cols])
                        X_num_imp = pd.DataFrame(arr_num, index=train_idx, columns=num_cols)
                    else:
                        X_num_imp = pd.DataFrame(index=train_idx)

                    if cat_cols:
                        cat_imp = SimpleImputer(strategy="most_frequent")
                        arr_cat = cat_imp.fit_transform(X_tr[cat_cols].astype(object))
                        X_cat_imp = pd.DataFrame(arr_cat, index=train_idx, columns=cat_cols)
                        X_tr_for_quality = pd.concat([X_num_imp, X_cat_imp], axis=1)[X_train.columns]
                    else:
                        X_tr_for_quality = X_num_imp[X_train.columns] if num_cols else X_tr.copy()

                imp_quality = compute_imputation_quality(
                    X_original.loc[train_idx],
                    X_tr_for_quality,
                    null_mask.loc[train_idx],
                )
            except Exception as e:
                print(f"     [imp_quality erro] {imp}: {e}")
                imp_quality = {}
        # ─────────────────────────────────────────────────────────────────────

        models = {
            "ridge_regression": Pipeline([
                ("preprocess", build_preprocessor_with_imputer(X_tr, imp, True)),
                ("model", Ridge(alpha=1.0)),
            ]),
            "random_forest": Pipeline([
                ("preprocess", build_preprocessor_with_imputer(X_tr, imp, False)),
                ("model", RandomForestRegressor(
                    n_estimators=N_ESTIMATORS, max_depth=10,
                    random_state=random_state, n_jobs=1,
                )),
            ]),
            "lightgbm": Pipeline([
                ("preprocess", build_preprocessor_with_imputer(X_tr, imp, False)),
                ("model", LGBMRegressor(
                    n_estimators=N_ESTIMATORS_LGBM, max_depth=10,
                    random_state=random_state, n_jobs=1, verbosity=-1,
                )),
            ]),
        }

        results[imp] = {}

        for name, model in models.items():
            try:
                model.fit(X_tr, y_tr)
                pred = model.predict(X_te)
                mse = mean_squared_error(y_te, pred)
                metrics = {
                    "mae":  float(mean_absolute_error(y_te, pred)),
                    "rmse": float(np.sqrt(mse)),
                    "r2":   float(r2_score(y_te, pred)),
                }
            except Exception as e:
                print(f"     x  {name}: {e}")
                metrics = {"mae": None, "rmse": None, "r2": None}

            metrics.update(imp_quality)
            results[imp][name] = metrics
            _print_metrics(name, metrics, task="regression")

    return results

def run_regression(X: pd.DataFrame, y: pd.Series, test_size: float, random_state: int) -> dict:
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=test_size, random_state=random_state
    )

    models = {
        "ridge_regression": Pipeline([
            ("preprocess", build_preprocessor(X_train, scale_numeric=True)),
            ("model", Ridge(alpha=1.0)),
        ]),
        "random_forest": Pipeline([
            ("preprocess", build_preprocessor(X_train, scale_numeric=False)),
            ("model", RandomForestRegressor(
                n_estimators=N_ESTIMATORS, 
                max_depth=10,
                random_state=random_state,
                n_jobs=1
            )),
        ]),
        "lightgbm": Pipeline([
            ("preprocess", build_preprocessor(X_train, scale_numeric=False)),
            ("model", LGBMRegressor(
                n_estimators=N_ESTIMATORS_LGBM,
                max_depth=10,
                random_state=random_state,
                n_jobs=1,
                verbosity=-1,
            )),
        ]),
    }

    results = {}

    for name, model in models.items():
        model.fit(X_train, y_train)
        pred = model.predict(X_test)

        mse = mean_squared_error(y_test, pred)
        metrics = {
            "mae": float(mean_absolute_error(y_test, pred)),
            "rmse": float(np.sqrt(mse)),
            "r2": float(r2_score(y_test, pred)),
        }

        results[name] = metrics
        _print_metrics(name, metrics, task="regression")

    return results

# FUNÇÃO PRINCIPAL
import time
import sys
import json

def run_one_dataset(
    key: str,
    out_dir: str = "data",
    test_size: float = 0.2,
    random_state: int = 42
) -> dict:

    data_dir = Path(out_dir)
    df, target, task = load_dataset(key, data_dir=data_dir)
    
    if SAMPLE_SIZE is not None and len(df) > SAMPLE_SIZE:
        df = df.sample(n=SAMPLE_SIZE, random_state=random_state).reset_index(drop=True)
        print(f"  [FAST] amostra de {SAMPLE_SIZE} linhas")

    SEP = "=" * 72
    task_icon = "CLASSIFICACAO" if task == "classification" else "REGRESSAO"
    print(f"\n{SEP}")
    print(f"  {task_icon}  |  {key.upper()}  |  target: {target}")
    print(SEP)

    df = normalize_missing_values(df)
    df = to_native_dtypes(df) 

    df[target] = df[target].astype(object)
    df = df[df[target].notna()].copy()

    if df.empty:
        raise RuntimeError("Dataset vazio após limpeza.")

    X, y = split_X_y(df, target)

    y = pd.Series([np.nan if v is pd.NA else v for v in y.astype(object)], index=y.index, dtype=object)

    if task == "classification":
        y = y.dropna()
        X = X.loc[y.index]

        X = to_native_dtypes(X)

        y = y.astype(object).astype(str)

        vc = y.value_counts()
        total = vc.sum()
        dist_str = "  |  ".join(f"{cls}: {cnt} ({cnt/total:.0%})" for cls, cnt in vc.items())
        print(f"  classes: {dist_str}")

        baseline_results = run_classification(X, y, test_size, random_state)

    else:
        y = pd.to_numeric(y, errors="coerce")
        valid = y.notna()

        X = X.loc[valid]
        # NOVO: converte X também para dtypes nativos
        X = to_native_dtypes(X)
        y = y.loc[valid]

        baseline_results = run_regression(X, y, test_size, random_state)

    # EXPERIMENTOS
    missing_mechanisms = MISSING_MECHANISMS 
    missing_rates      = MISSING_RATES    

    all_results = []

    all_results.append({
        "dataset": key,
        "mechanism": "NONE",
        "rate": 0,
        "results": baseline_results
    })

    for mech in missing_mechanisms:
        for rate in missing_rates:
            pct = int(rate * 100)
            print(f"\n  EXPERIMENTO  {mech}  {pct:2d}%  [{key}]")
            print(f"  {chr(45)*50}")

            df_missing, X_original_exp, null_mask_exp = inject_missing_values(
                df,
                target=target,
                mechanism=mech,
                missing_rate=rate,
                random_state=random_state
            )

            X, y = split_X_y(df_missing, target)


            X = to_native_dtypes(X)
            y = pd.Series(
                [np.nan if (v is pd.NA or (isinstance(v, float) and np.isnan(v))) else v 
                for v in y],
                index=y.index,
                dtype=object
            )

            if task == "classification":
                valid = y.notna()
                X = X.loc[valid]
                y = y.loc[valid].astype(str)
                res = run_classification_with_imputation(X, y, test_size, random_state,
                                         X_original_exp, null_mask_exp)
            else:
                y = pd.to_numeric(y, errors="coerce")
                valid = y.notna()
                X = X.loc[valid]
                y = y.loc[valid]
                res = run_regression_with_imputation(X, y, test_size, random_state,
                                     X_original_exp, null_mask_exp)

            all_results.append({
                "dataset": key,
                "mechanism": mech,
                "rate": rate,
                "results": res
            })

    return {
        "key": key,
        "task": task,
        "results": baseline_results,
        "experiments": all_results
    }

In [14]:
# 5) Configuracao da execucao

# ============================================================
# 🚀 FAST_MODE: True = rápido para testes  (~2-5 min)
#               False = completo para resultados finais (~120 min)
# ============================================================
FAST_MODE = False

# Parametros globais
out_dir = "data"
test_size = 0.2
random_state = 42

datasets_experiment = [
    "adult",
    "bank_marketing",
    "air_quality_uci",
    "communities_crime",
]

if FAST_MODE:
    MISSING_MECHANISMS = ["MCAR"]
    MISSING_RATES      = [0.05]
    N_ESTIMATORS       = 10
    N_ESTIMATORS_LGBM  = 50   # mínimo razoável para LightGBM no FAST_MODE
    MAX_ITER_IMPUTER   = 2
    SAMPLE_SIZE        = 3000
    print("⚡ FAST MODE — resultados aproximados para testes")
else:
    MISSING_MECHANISMS = ["MCAR", "MAR", "MNAR"]
    MISSING_RATES      = [0.01, 0.05, 0.10, 0.15, 0.20, 0.25, 0.30]
    N_ESTIMATORS       = 50
    N_ESTIMATORS_LGBM  = 100  # LightGBM leaf-wise precisa de mais estimadores
    MAX_ITER_IMPUTER   = 5
    SAMPLE_SIZE        = None
    print("🔬 FULL MODE — execução completa")

datasets_experiment

🔬 FULL MODE — execução completa

['adult', 'bank_marketing', 'air_quality_uci', 'communities_crime']

In [15]:
#barra de progresso
from tqdm import tqdm
from joblib import Parallel, delayed

class ParallelTqdm(Parallel):
    def __init__(self, total=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.total = total

    def __call__(self, *args, **kwargs):
        with tqdm(total=self.total) as self._pbar:
            return Parallel.__call__(self, *args, **kwargs)

    def print_progress(self):
        if self._pbar is not None:
            self._pbar.n = self.n_completed_tasks
            self._pbar.refresh()

In [16]:
from joblib import Parallel, delayed
import multiprocessing
from pathlib import Path
import pandas as pd
import numpy as np

if __name__ == "__main__":

    N_CORES     = multiprocessing.cpu_count()
    N_JOBS_OUTER = min(len(datasets_experiment), N_CORES // 2)

    print(f"Total cores: {N_CORES}")
    print(f"Paralelismo externo (datasets): {N_JOBS_OUTER}")

    # ── Sementes para repetições ──────────────────────────────────────────────
    RANDOM_SEEDS = [42, 123, 456]

    # ── Função segura por (dataset, semente) ─────────────────────────────────
    def run_dataset_seed_safe(key, seed):
        try:
            return run_one_dataset(
                key=key,
                out_dir=out_dir,
                test_size=test_size,
                random_state=seed,
            )
        except Exception as e:
            print(f"\n[ERRO] key={key} seed={seed}: {e}")
            return {
                "key": key,
                "task": DATASETS[key]["task"],
                "seed": seed,
                "error": str(e),
            }

    # ── Combinações dataset × semente ────────────────────────────────────────
    combos = [(key, seed) for key in datasets_experiment for seed in RANDOM_SEEDS]

    # ── Execução paralela ─────────────────────────────────────────────────────
    all_runs = ParallelTqdm(
        n_jobs=N_JOBS_OUTER,
        total=len(combos),
        backend="threading",
        prefer="threads",
    )(
        delayed(run_dataset_seed_safe)(key, seed) for key, seed in combos
    )

    # ── Montar CSV detalhado com TODOS os cenários ────────────────────────────
    detail_rows = []

    for run in all_runs:
        if "error" in run and "experiments" not in run:
            continue  # pula runs com erro total

        key  = run["key"]
        task = run["task"]
        seed = run.get("seed", run.get("random_state", 42))

        # Baseline (mechanism=NONE, rate=0, imputer=baseline)
        for model, metrics in run.get("results", {}).items():
            if metrics is None:
                continue
            row = {
                "dataset":   key,
                "task":      task,
                "seed":      seed,
                "mechanism": "NONE",
                "rate":      0.0,
                "imputer":   "baseline_dropna",
                "model":     model,
            }
            row.update(metrics)
            detail_rows.append(row)

        # Experimentos com nulos injetados
        for exp in run.get("experiments", []):
            if exp.get("mechanism") == "NONE":
                continue  # já capturado acima
            for imputer, imp_results in exp.get("results", {}).items():
                for model, metrics in imp_results.items():
                    if metrics is None:
                        continue
                    row = {
                        "dataset":   key,
                        "task":      task,
                        "seed":      seed,
                        "mechanism": exp["mechanism"],
                        "rate":      exp["rate"],
                        "imputer":   imputer,
                        "model":     model,
                    }
                    row.update(metrics)
                    detail_rows.append(row)

    detail_df = pd.DataFrame(detail_rows)
    data_path  = Path(out_dir)
    data_path.mkdir(parents=True, exist_ok=True)

    detail_path = data_path / "all_results.csv"
    detail_df.to_csv(detail_path, index=False)
    print(f"\nCSV detalhado salvo: {detail_path}  ({len(detail_df)} linhas)")

    # ── Resumo com média ± desvio padrão ─────────────────────────────────────
    grp_cols = ["dataset", "task", "mechanism", "rate", "imputer", "model"]

    # Métricas disponíveis dependem da task
    clf_metrics = ["accuracy", "macro_f1", "weighted_f1"]
    reg_metrics = ["mae", "rmse", "r2"]
    all_metrics = clf_metrics + reg_metrics

    existing_metrics = [c for c in all_metrics if c in detail_df.columns]

    summary = (
        detail_df
        .groupby(grp_cols)[existing_metrics]
        .agg(["mean", "std"])
        .round(4)
    )
    summary_path = data_path / "summary_results.csv"
    summary.to_csv(summary_path)
    print(f"CSV resumo (média±std) salvo: {summary_path}")

    # ── Tabelas de baseline (melhor modelo, média das sementes) ───────────────
    baseline_df = detail_df[detail_df["mechanism"] == "NONE"].copy()

    if "accuracy" in baseline_df.columns:
        clf_base = (
            baseline_df[baseline_df["task"] == "classification"]
            .groupby(["dataset", "model"])[clf_metrics]
            .mean()
            .round(4)
            .reset_index()
        )
        if not clf_base.empty:
            best_clf = clf_base.loc[
                clf_base.groupby("dataset")["weighted_f1"].idxmax()
            ]
            print("\n=== Classificacao (baseline, média 3 sementes) ===")
            display(best_clf)
            best_clf.to_csv(data_path / "classification_summary.csv", index=False)
            print("Salvo em:", data_path / "classification_summary.csv")

    if "r2" in baseline_df.columns:
        reg_base = (
            baseline_df[baseline_df["task"] == "regression"]
            .groupby(["dataset", "model"])[reg_metrics]
            .mean()
            .round(4)
            .reset_index()
        )
        if not reg_base.empty:
            best_reg = reg_base.loc[
                reg_base.groupby("dataset")["r2"].idxmax()
            ]
            print("\n=== Regressao (baseline, média 3 sementes) ===")
            display(best_reg)
            best_reg.to_csv(data_path / "regression_summary.csv", index=False)
            print("Salvo em:", data_path / "regression_summary.csv")

Total cores: 12
Paralelismo externo (datasets): 4

  0%|          | 0/12 [00:00<?, ?it/s]

[cache] data\bank_marketing\bank.zip[cache] data\adult\adult.data
[cache] data\adult\adult.data
[cache] data\adult\adult.data

[cache] data\bank_marketing\extracted
[cache] data\adult\adult.test
[cache] data\adult\adult.test
[cache] data\adult\adult.test

========================================================================
  CLASSIFICACAO  |  BANK_MARKETING  |  target: y
========================================================================

========================================================================
  CLASSIFICACAO  |  ADULT  |  target: income
========================================================================

========================================================================
  CLASSIFICACAO  |  ADULT  |  target: income
========================================================================

========================================================================
  CLASSIFICACAO  |  ADULT  |  target: income
========================================================================
  classes: no: 39922 (88%)  |  yes: 5289 (12%)
  classes: <=50K: 37155 (76%)  |  >50K: 11687 (24%)
  classes: <=50K: 37155 (76%)  |  >50K: 11687 (24%)
  classes: <=50K: 37155 (76%)  |  >50K: 11687 (24%)
     ok logistic_regression        acc=0.846  mf1=0.730  wf1=0.865  [#################---]
     ok logistic_regression        acc=0.816  mf1=0.780  wf1=0.827  [################----]
     ok logistic_regression        acc=0.808  mf1=0.769  wf1=0.819  [################----]
     ok logistic_regression        acc=0.808  mf1=0.770  wf1=0.819  [################----]
     ok random_forest              acc=0.904  mf1=0.699  wf1=0.889  [#################---]
     ok lightgbm                   acc=0.857  mf1=0.752  wf1=0.875  [#################---]

  EXPERIMENTO  MCAR   1%  [bank_marketing]
  --------------------------------------------------
  > imputador: dropna
     ok logistic_regression        acc=0.817  mf1=0.776  wf1=0.825  [################----]
     ok random_forest              acc=0.829  mf1=0.779  wf1=0.833  [################----]
     ok lightgbm                   acc=0.832  mf1=0.787  wf1=0.837  [################----]
  > imputador: simple_mean
     ok logistic_regression        acc=0.845  mf1=0.728  wf1=0.864  [#################---]
     ok random_forest              acc=0.842  mf1=0.729  wf1=0.863  [#################---]
     ok lightgbm                   acc=0.854  mf1=0.747  wf1=0.873  [#################---]
  > imputador: simple_median
     ok logistic_regression        acc=0.844  mf1=0.728  wf1=0.864  [#################---]
     ok random_forest              acc=0.846  mf1=0.733  wf1=0.866  [#################---]
     ok lightgbm                   acc=0.853  mf1=0.746  wf1=0.872  [#################---]
  > imputador: simple_freq
     ok logistic_regression        acc=0.844  mf1=0.728  wf1=0.864  [#################---]
     ok random_forest              acc=0.843  mf1=0.730  wf1=0.864  [#################---]
     ok lightgbm                   acc=0.854  mf1=0.748  wf1=0.873  [#################---]
  > imputador: simple_const
     ok logistic_regression        acc=0.844  mf1=0.728  wf1=0.864  [#################---]
     ok random_forest              acc=0.844  mf1=0.731  wf1=0.865  [#################---]
     ok lightgbm                   acc=0.854  mf1=0.747  wf1=0.873  [#################---]
  > imputador: knn_3
     ok random_forest              acc=0.857  mf1=0.790  wf1=0.852  [#################---]
     ok random_forest              acc=0.855  mf1=0.788  wf1=0.850  [#################---]
     ok random_forest              acc=0.854  mf1=0.785  wf1=0.848  [################----]
     ok lightgbm                   acc=0.838  mf1=0.803  wf1=0.846  [################----]

  EXPERIMENTO  MCAR   1%  [adult]
  --------------------------------------------------
  > imputador: dropna
     ok lightgbm                   acc=0.831  mf1=0.795  wf1=0.840  [################----]

  EXPERIMENTO  MCAR   1%  [adult]
  --------------------------------------------------
     ok lightgbm                   acc=0.836  mf1=0.800  wf1=0.844  [################----]

  EXPERIMENTO  MCAR   1%  [adult]
  --------------------------------------------------
  > imputador: dropna
  > imputador: dropna
     ok logistic_regression        acc=0.817  mf1=0.783  wf1=0.827  [################----]
     ok logistic_regression        acc=0.807  mf1=0.772  wf1=0.817  [################----]
     ok logistic_regression        acc=0.807  mf1=0.771  wf1=0.817  [################----]
     ok random_forest              acc=0.800  mf1=0.769  wf1=0.812  [################----]
     ok logistic_regression        acc=0.844  mf1=0.728  wf1=0.864  [#################---]
     ok random_forest              acc=0.793  mf1=0.762  wf1=0.805  [################----]
     ok random_forest              acc=0.792  mf1=0.761  wf1=0.804  [################----]
     ok lightgbm                   acc=0.841  mf1=0.808  wf1=0.848  [################----]
  > imputador: simple_mean
     ok lightgbm                   acc=0.833  mf1=0.800  wf1=0.841  [################----]
  > imputador: simple_mean
     ok lightgbm                   acc=0.830  mf1=0.797  wf1=0.838  [################----]
  > imputador: simple_mean
     ok logistic_regression        acc=0.814  mf1=0.778  wf1=0.825  [################----]
     ok logistic_regression        acc=0.806  mf1=0.768  wf1=0.817  [################----]
     ok logistic_regression        acc=0.808  mf1=0.770  wf1=0.819  [################----]
     ok random_forest              acc=0.840  mf1=0.727  wf1=0.862  [#################---]
     ok random_forest              acc=0.789  mf1=0.756  wf1=0.803  [################----]
     ok random_forest              acc=0.789  mf1=0.755  wf1=0.803  [################----]
     ok random_forest              acc=0.791  mf1=0.758  wf1=0.805  [################----]
     ok lightgbm                   acc=0.838  mf1=0.804  wf1=0.847  [################----]
  > imputador: simple_median
     ok lightgbm                   acc=0.826  mf1=0.790  wf1=0.835  [################----]
  > imputador: simple_median
     ok lightgbm                   acc=0.833  mf1=0.796  wf1=0.841  [################----]
  > imputador: simple_median
     ok logistic_regression        acc=0.815  mf1=0.779  wf1=0.825  [################----]
     ok logistic_regression        acc=0.808  mf1=0.770  wf1=0.819  [################----]
     ok logistic_regression        acc=0.806  mf1=0.767  wf1=0.817  [################----]
     ok lightgbm                   acc=0.851  mf1=0.745  wf1=0.871  [#################---]
  > imputador: knn_5
     ok random_forest              acc=0.797  mf1=0.764  wf1=0.810  [################----]
     ok random_forest              acc=0.788  mf1=0.754  wf1=0.801  [################----]
     ok random_forest              acc=0.792  mf1=0.759  wf1=0.805  [################----]
     ok lightgbm                   acc=0.838  mf1=0.804  wf1=0.846  [################----]
  > imputador: simple_freq
     ok lightgbm                   acc=0.827  mf1=0.792  wf1=0.837  [################----]
  > imputador: simple_freq
     ok lightgbm                   acc=0.834  mf1=0.797  wf1=0.842  [################----]
  > imputador: simple_freq
     ok logistic_regression        acc=0.815  mf1=0.779  wf1=0.826  [################----]
     ok logistic_regression        acc=0.806  mf1=0.768  wf1=0.817  [################----]
     ok logistic_regression        acc=0.808  mf1=0.769  wf1=0.818  [################----]
     ok logistic_regression        acc=0.844  mf1=0.728  wf1=0.864  [#################---]
     ok random_forest              acc=0.794  mf1=0.762  wf1=0.807  [################----]
     ok random_forest              acc=0.787  mf1=0.753  wf1=0.801  [################----]
     ok random_forest              acc=0.789  mf1=0.756  wf1=0.803  [################----]
     ok lightgbm                   acc=0.838  mf1=0.804  wf1=0.847  [################----]
  > imputador: simple_const
     ok lightgbm                   acc=0.829  mf1=0.793  wf1=0.838  [################----]
  > imputador: simple_const
     ok lightgbm                   acc=0.833  mf1=0.797  wf1=0.842  [################----]
  > imputador: simple_const
     ok logistic_regression        acc=0.814  mf1=0.777  wf1=0.824  [################----]
     ok logistic_regression        acc=0.804  mf1=0.765  wf1=0.815  [################----]
     ok logistic_regression        acc=0.807  mf1=0.769  wf1=0.818  [################----]
     ok random_forest              acc=0.844  mf1=0.733  wf1=0.865  [#################---]
     ok random_forest              acc=0.796  mf1=0.763  wf1=0.809  [################----]
     ok random_forest              acc=0.781  mf1=0.747  wf1=0.795  [###############-----]
     ok random_forest              acc=0.786  mf1=0.753  wf1=0.800  [################----]
     ok lightgbm                   acc=0.839  mf1=0.805  wf1=0.847  [################----]
  > imputador: knn_3
     ok lightgbm                   acc=0.828  mf1=0.792  wf1=0.837  [################----]
  > imputador: knn_3
     ok lightgbm                   acc=0.835  mf1=0.799  wf1=0.843  [################----]
  > imputador: knn_3
     ok lightgbm                   acc=0.854  mf1=0.747  wf1=0.873  [#################---]
  > imputador: knn_7
     ok logistic_regression        acc=0.814  mf1=0.778  wf1=0.825  [################----]
     ok logistic_regression        acc=0.806  mf1=0.768  wf1=0.817  [################----]
     ok logistic_regression        acc=0.808  mf1=0.770  wf1=0.819  [################----]
     ok logistic_regression        acc=0.845  mf1=0.728  wf1=0.864  [#################---]
     ok random_forest              acc=0.788  mf1=0.755  wf1=0.802  [################----]
     ok random_forest              acc=0.842  mf1=0.729  wf1=0.863  [#################---]
     ok random_forest              acc=0.792  mf1=0.758  wf1=0.805  [################----]
     ok random_forest              acc=0.790  mf1=0.756  wf1=0.803  [################----]
     ok lightgbm                   acc=0.836  mf1=0.802  wf1=0.845  [################----]
  > imputador: knn_5
     ok lightgbm                   acc=0.851  mf1=0.743  wf1=0.870  [#################---]
  > imputador: iterative
     ok lightgbm                   acc=0.828  mf1=0.793  wf1=0.838  [################----]
  > imputador: knn_5
     ok logistic_regression        acc=0.845  mf1=0.728  wf1=0.865  [#################---]
     ok lightgbm                   acc=0.834  mf1=0.797  wf1=0.842  [################----]
  > imputador: knn_5
     ok random_forest              acc=0.839  mf1=0.727  wf1=0.861  [#################---]
     ok lightgbm                   acc=0.854  mf1=0.748  wf1=0.873  [#################---]
  > imputador: miceforest
  [miceforest] fallback SimpleImputer (AssertionError)
     ok logistic_regression        acc=0.820  mf1=0.694  wf1=0.845  [################----]
     ok random_forest              acc=0.847  mf1=0.732  wf1=0.866  [#################---]
     ok logistic_regression        acc=0.814  mf1=0.778  wf1=0.825  [################----]
     ok lightgbm                   acc=0.852  mf1=0.745  wf1=0.872  [#################---]

  EXPERIMENTO  MCAR   5%  [bank_marketing]
  --------------------------------------------------
  > imputador: dropna
     ok logistic_regression        acc=0.806  mf1=0.768  wf1=0.817  [################----]
     ok logistic_regression        acc=0.827  mf1=0.789  wf1=0.835  [################----]
     ok random_forest              acc=0.847  mf1=0.793  wf1=0.848  [################----]
     ok lightgbm                   acc=0.846  mf1=0.803  wf1=0.850  [#################---]
  > imputador: simple_mean
     ok logistic_regression        acc=0.840  mf1=0.720  wf1=0.860  [#################---]
     ok logistic_regression        acc=0.808  mf1=0.769  wf1=0.818  [################----]
     ok random_forest              acc=0.835  mf1=0.719  wf1=0.858  [#################---]
     ok lightgbm                   acc=0.846  mf1=0.735  wf1=0.866  [#################---]
  > imputador: simple_median
     ok logistic_regression        acc=0.839  mf1=0.719  wf1=0.859  [#################---]
     ok random_forest              acc=0.798  mf1=0.765  wf1=0.811  [################----]
     ok random_forest              acc=0.835  mf1=0.718  wf1=0.857  [#################---]
     ok random_forest              acc=0.785  mf1=0.752  wf1=0.799  [###############-----]
     ok lightgbm                   acc=0.848  mf1=0.736  wf1=0.868  [#################---]
  > imputador: simple_freq
     ok logistic_regression        acc=0.838  mf1=0.717  wf1=0.859  [#################---]
     ok random_forest              acc=0.787  mf1=0.754  wf1=0.801  [################----]
     ok random_forest              acc=0.837  mf1=0.719  wf1=0.858  [#################---]
     ok lightgbm                   acc=0.837  mf1=0.802  wf1=0.845  [################----]
  > imputador: knn_7
     ok lightgbm                   acc=0.847  mf1=0.736  wf1=0.867  [#################---]
  > imputador: simple_const
     ok lightgbm                   acc=0.828  mf1=0.793  wf1=0.837  [################----]
  > imputador: knn_7
     ok logistic_regression        acc=0.834  mf1=0.714  wf1=0.856  [#################---]
     ok lightgbm                   acc=0.834  mf1=0.798  wf1=0.842  [################----]
  > imputador: knn_7
     ok random_forest              acc=0.841  mf1=0.723  wf1=0.861  [#################---]
     ok lightgbm                   acc=0.848  mf1=0.737  wf1=0.868  [#################---]
  > imputador: knn_3
     ok logistic_regression        acc=0.814  mf1=0.778  wf1=0.825  [################----]
     ok logistic_regression        acc=0.807  mf1=0.768  wf1=0.818  [################----]
     ok logistic_regression        acc=0.808  mf1=0.770  wf1=0.819  [################----]
     ok random_forest              acc=0.794  mf1=0.761  wf1=0.807  [################----]
     ok random_forest              acc=0.788  mf1=0.754  wf1=0.802  [################----]
     ok random_forest              acc=0.789  mf1=0.756  wf1=0.803  [################----]
     ok lightgbm                   acc=0.839  mf1=0.804  wf1=0.847  [################----]
  > imputador: iterative
     ok lightgbm                   acc=0.829  mf1=0.793  wf1=0.838  [################----]
  > imputador: iterative
     ok logistic_regression        acc=0.814  mf1=0.778  wf1=0.825  [################----]
     ok lightgbm                   acc=0.835  mf1=0.799  wf1=0.843  [################----]
  > imputador: iterative
     ok logistic_regression        acc=0.806  mf1=0.767  wf1=0.817  [################----]
     ok logistic_regression        acc=0.808  mf1=0.770  wf1=0.819  [################----]
     ok random_forest              acc=0.794  mf1=0.761  wf1=0.807  [################----]
     ok random_forest              acc=0.786  mf1=0.753  wf1=0.800  [################----]
     ok lightgbm                   acc=0.838  mf1=0.803  wf1=0.846  [################----]
  > imputador: miceforest
  [miceforest] fallback SimpleImputer (AssertionError)
     ok logistic_regression        acc=0.799  mf1=0.761  wf1=0.811  [################----]
     ok random_forest              acc=0.791  mf1=0.758  wf1=0.805  [################----]
     ok lightgbm                   acc=0.826  mf1=0.791  wf1=0.836  [################----]
  > imputador: miceforest
  [miceforest] fallback SimpleImputer (AssertionError)
     ok logistic_regression        acc=0.792  mf1=0.751  wf1=0.803  [################----]
     ok lightgbm                   acc=0.834  mf1=0.797  wf1=0.842  [################----]
  > imputador: miceforest
  [miceforest] fallback SimpleImputer (AssertionError)
     ok logistic_regression        acc=0.766  mf1=0.719  wf1=0.779  [###############-----]
     ok random_forest              acc=0.812  mf1=0.778  wf1=0.823  [################----]
     ok random_forest              acc=0.805  mf1=0.770  wf1=0.817  [################----]
     ok lightgbm                   acc=0.837  mf1=0.803  wf1=0.845  [################----]

  EXPERIMENTO  MCAR   5%  [adult]
  --------------------------------------------------
  > imputador: dropna
     ok lightgbm                   acc=0.830  mf1=0.795  wf1=0.839  [################----]

  EXPERIMENTO  MCAR   5%  [adult]
  --------------------------------------------------
     ok logistic_regression        acc=0.819  mf1=0.787  wf1=0.828  [################----]
  > imputador: dropna
     ok random_forest              acc=0.807  mf1=0.771  wf1=0.818  [################----]
     ok logistic_regression        acc=0.811  mf1=0.774  wf1=0.821  [################----]
     ok lightgbm                   acc=0.833  mf1=0.797  wf1=0.841  [################----]

  EXPERIMENTO  MCAR   5%  [adult]
  --------------------------------------------------
  > imputador: dropna
     ok logistic_regression        acc=0.810  mf1=0.775  wf1=0.820  [################----]
     ok logistic_regression        acc=0.835  mf1=0.715  wf1=0.856  [#################---]
     ok random_forest              acc=0.813  mf1=0.784  wf1=0.823  [################----]
     ok lightgbm                   acc=0.846  mf1=0.816  wf1=0.853  [#################---]
  > imputador: simple_mean
     ok random_forest              acc=0.785  mf1=0.754  wf1=0.799  [###############-----]
     ok lightgbm                   acc=0.831  mf1=0.797  wf1=0.839  [################----]
  > imputador: simple_mean
     ok logistic_regression        acc=0.811  mf1=0.774  wf1=0.822  [################----]
     ok random_forest              acc=0.797  mf1=0.765  wf1=0.809  [################----]
     ok lightgbm                   acc=0.829  mf1=0.794  wf1=0.837  [################----]
  > imputador: simple_mean
     ok logistic_regression        acc=0.802  mf1=0.764  wf1=0.814  [################----]
     ok logistic_regression        acc=0.801  mf1=0.763  wf1=0.813  [################----]
     ok random_forest              acc=0.792  mf1=0.759  wf1=0.806  [################----]
     ok random_forest              acc=0.786  mf1=0.752  wf1=0.800  [###############-----]
     ok lightgbm                   acc=0.832  mf1=0.797  wf1=0.841  [################----]
  > imputador: simple_median
     ok random_forest              acc=0.789  mf1=0.756  wf1=0.803  [################----]
     ok lightgbm                   acc=0.826  mf1=0.790  wf1=0.836  [################----]
  > imputador: simple_median
     ok logistic_regression        acc=0.811  mf1=0.775  wf1=0.822  [################----]
     ok lightgbm                   acc=0.830  mf1=0.794  wf1=0.839  [################----]
  > imputador: simple_median
     ok logistic_regression        acc=0.802  mf1=0.763  wf1=0.813  [################----]
     ok logistic_regression        acc=0.802  mf1=0.763  wf1=0.813  [################----]
     ok random_forest              acc=0.792  mf1=0.759  wf1=0.805  [################----]
     ok random_forest              acc=0.778  mf1=0.745  wf1=0.793  [###############-----]
     ok lightgbm                   acc=0.833  mf1=0.799  wf1=0.842  [################----]
  > imputador: simple_freq
     ok lightgbm                   acc=0.827  mf1=0.791  wf1=0.836  [################----]
  > imputador: simple_freq
     ok random_forest              acc=0.789  mf1=0.756  wf1=0.803  [################----]
     ok logistic_regression        acc=0.810  mf1=0.774  wf1=0.821  [################----]
     ok lightgbm                   acc=0.828  mf1=0.792  wf1=0.837  [################----]
  > imputador: simple_freq
     ok logistic_regression        acc=0.801  mf1=0.762  wf1=0.812  [################----]
     ok logistic_regression        acc=0.803  mf1=0.764  wf1=0.814  [################----]
     ok random_forest              acc=0.786  mf1=0.754  wf1=0.801  [################----]

  8%|▊         | 1/12 [7:25:12<81:37:12, 26712.09s/it]

     ok lightgbm                   acc=0.851  mf1=0.746  wf1=0.871  [#################---]
[cache] data\bank_marketing\bank.zip
[cache] data\bank_marketing\extracted

========================================================================
  CLASSIFICACAO  |  BANK_MARKETING  |  target: y
========================================================================
  classes: no: 39922 (88%)  |  yes: 5289 (12%)
     ok logistic_regression        acc=0.833  mf1=0.713  wf1=0.855  [#################---]
     ok random_forest              acc=0.904  mf1=0.697  wf1=0.889  [#################---]
     ok lightgbm                   acc=0.859  mf1=0.753  wf1=0.877  [#################---]

  EXPERIMENTO  MCAR   1%  [bank_marketing]
  --------------------------------------------------
  > imputador: dropna
     ok logistic_regression        acc=0.811  mf1=0.772  wf1=0.821  [################----]
     ok random_forest              acc=0.826  mf1=0.779  wf1=0.832  [################----]
     ok lightgbm                   acc=0.827  mf1=0.785  wf1=0.834  [################----]
  > imputador: simple_mean
     ok logistic_regression        acc=0.834  mf1=0.714  wf1=0.856  [#################---]
     ok random_forest              acc=0.846  mf1=0.731  wf1=0.865  [#################---]
     ok random_forest              acc=0.768  mf1=0.732  wf1=0.783  [###############-----]
     ok lightgbm                   acc=0.856  mf1=0.747  wf1=0.874  [#################---]
  > imputador: simple_median
     ok logistic_regression        acc=0.833  mf1=0.712  wf1=0.855  [#################---]
     ok random_forest              acc=0.846  mf1=0.733  wf1=0.866  [#################---]
     ok lightgbm                   acc=0.856  mf1=0.747  wf1=0.874  [#################---]
  > imputador: simple_freq
     ok logistic_regression        acc=0.833  mf1=0.712  wf1=0.855  [#################---]
     ok lightgbm                   acc=0.807  mf1=0.768  wf1=0.818  [################----]
  > imputador: knn_5
     ok random_forest              acc=0.844  mf1=0.730  wf1=0.864  [#################---]
     ok lightgbm                   acc=0.854  mf1=0.746  wf1=0.873  [#################---]
  > imputador: simple_const
     ok logistic_regression        acc=0.833  mf1=0.713  wf1=0.855  [#################---]
     ok random_forest              acc=0.843  mf1=0.728  wf1=0.863  [#################---]
     ok lightgbm                   acc=0.855  mf1=0.745  wf1=0.873  [#################---]
  > imputador: knn_3
     ok logistic_regression        acc=0.832  mf1=0.712  wf1=0.855  [#################---]
     ok random_forest              acc=0.841  mf1=0.726  wf1=0.862  [#################---]
     ok lightgbm                   acc=0.855  mf1=0.747  wf1=0.874  [#################---]
  > imputador: knn_5
     ok logistic_regression        acc=0.833  mf1=0.712  wf1=0.855  [#################---]
     ok random_forest              acc=0.844  mf1=0.730  wf1=0.865  [#################---]
     ok lightgbm                   acc=0.857  mf1=0.749  wf1=0.875  [#################---]
  > imputador: knn_7
     ok logistic_regression        acc=0.833  mf1=0.713  wf1=0.855  [#################---]
     ok random_forest              acc=0.842  mf1=0.727  wf1=0.863  [#################---]
     ok lightgbm                   acc=0.855  mf1=0.748  wf1=0.874  [#################---]
  > imputador: iterative
     ok logistic_regression        acc=0.834  mf1=0.714  wf1=0.856  [#################---]
     ok random_forest              acc=0.841  mf1=0.726  wf1=0.862  [#################---]
     ok lightgbm                   acc=0.855  mf1=0.746  wf1=0.873  [#################---]
  > imputador: miceforest
  [miceforest] fallback SimpleImputer (AssertionError)
     ok logistic_regression        acc=0.799  mf1=0.673  wf1=0.828  [################----]
     ok random_forest              acc=0.848  mf1=0.731  wf1=0.867  [#################---]
     ok lightgbm                   acc=0.853  mf1=0.745  wf1=0.872  [#################---]

  EXPERIMENTO  MCAR   5%  [bank_marketing]
  --------------------------------------------------
  > imputador: dropna
     ok logistic_regression        acc=0.824  mf1=0.777  wf1=0.832  [################----]
     ok random_forest              acc=0.848  mf1=0.791  wf1=0.850  [#################---]
     ok lightgbm                   acc=0.852  mf1=0.802  wf1=0.856  [#################---]
  > imputador: simple_mean
     ok logistic_regression        acc=0.831  mf1=0.709  wf1=0.854  [#################---]
     ok random_forest              acc=0.830  mf1=0.713  wf1=0.853  [#################---]
     ok lightgbm                   acc=0.848  mf1=0.737  wf1=0.868  [#################---]
  > imputador: simple_median
     ok logistic_regression        acc=0.832  mf1=0.710  wf1=0.854  [#################---]
     ok random_forest              acc=0.841  mf1=0.725  wf1=0.862  [#################---]
     ok lightgbm                   acc=0.849  mf1=0.737  wf1=0.868  [#################---]
  > imputador: simple_freq
     ok logistic_regression        acc=0.831  mf1=0.709  wf1=0.853  [#################---]
     ok random_forest              acc=0.839  mf1=0.722  wf1=0.860  [#################---]
     ok lightgbm                   acc=0.851  mf1=0.739  wf1=0.870  [#################---]
  > imputador: simple_const
     ok logistic_regression        acc=0.830  mf1=0.707  wf1=0.852  [#################---]
     ok lightgbm                   acc=0.801  mf1=0.763  wf1=0.813  [################----]
  > imputador: knn_7
     ok random_forest              acc=0.839  mf1=0.721  wf1=0.860  [#################---]
     ok lightgbm                   acc=0.848  mf1=0.735  wf1=0.867  [#################---]
  > imputador: knn_3
     ok logistic_regression        acc=0.830  mf1=0.707  wf1=0.852  [#################---]
     ok random_forest              acc=0.838  mf1=0.718  wf1=0.859  [#################---]
     ok logistic_regression        acc=0.782  mf1=0.744  wf1=0.796  [###############-----]
     ok logistic_regression        acc=0.771  mf1=0.731  wf1=0.785  [###############-----]
     ok lightgbm                   acc=0.852  mf1=0.741  wf1=0.871  [#################---]
  > imputador: knn_5
     ok logistic_regression        acc=0.831  mf1=0.708  wf1=0.853  [#################---]
     ok random_forest              acc=0.834  mf1=0.716  wf1=0.856  [#################---]
     ok lightgbm                   acc=0.851  mf1=0.740  wf1=0.870  [#################---]
  > imputador: knn_7
     ok random_forest              acc=0.789  mf1=0.744  wf1=0.800  [###############-----]
     ok random_forest              acc=0.768  mf1=0.735  wf1=0.784  [###############-----]
     ok logistic_regression        acc=0.772  mf1=0.731  wf1=0.785  [###############-----]
     ok logistic_regression        acc=0.830  mf1=0.707  wf1=0.853  [#################---]
     ok random_forest              acc=0.839  mf1=0.722  wf1=0.860  [#################---]
     ok lightgbm                   acc=0.851  mf1=0.739  wf1=0.870  [#################---]
  > imputador: iterative
     ok logistic_regression        acc=0.831  mf1=0.708  wf1=0.853  [#################---]
     ok random_forest              acc=0.841  mf1=0.723  wf1=0.861  [#################---]
     ok lightgbm                   acc=0.850  mf1=0.739  wf1=0.870  [#################---]
  > imputador: miceforest
  [miceforest] fallback SimpleImputer (AssertionError)
     ok logistic_regression        acc=0.791  mf1=0.664  wf1=0.822  [################----]
     ok random_forest              acc=0.847  mf1=0.726  wf1=0.866  [#################---]
     ok lightgbm                   acc=0.849  mf1=0.736  wf1=0.868  [#################---]

  EXPERIMENTO  MCAR  10%  [bank_marketing]
  --------------------------------------------------
  > imputador: dropna
     ok logistic_regression        acc=0.832  mf1=0.790  wf1=0.838  [################----]
     ok random_forest              acc=0.861  mf1=0.797  wf1=0.856  [#################---]
     ok lightgbm                   acc=0.835  mf1=0.783  wf1=0.838  [################----]
  > imputador: simple_mean
     ok logistic_regression        acc=0.820  mf1=0.695  wf1=0.845  [################----]
     ok random_forest              acc=0.838  mf1=0.718  wf1=0.859  [#################---]
     ok lightgbm                   acc=0.844  mf1=0.732  wf1=0.865  [#################---]
  > imputador: simple_median
     ok logistic_regression        acc=0.824  mf1=0.699  wf1=0.848  [################----]
     ok lightgbm                   acc=0.811  mf1=0.773  wf1=0.822  [################----]
  > imputador: knn_7
     ok random_forest              acc=0.834  mf1=0.715  wf1=0.856  [#################---]
     ok lightgbm                   acc=0.843  mf1=0.729  wf1=0.864  [#################---]
  > imputador: simple_freq
     ok logistic_regression        acc=0.822  mf1=0.696  wf1=0.846  [################----]
     ok random_forest              acc=0.835  mf1=0.715  wf1=0.857  [#################---]
     ok lightgbm                   acc=0.843  mf1=0.729  wf1=0.863  [#################---]
  > imputador: simple_const
     ok logistic_regression        acc=0.818  mf1=0.691  wf1=0.843  [################----]
     ok random_forest              acc=0.839  mf1=0.717  wf1=0.859  [#################---]
     ok lightgbm                   acc=0.842  mf1=0.731  wf1=0.863  [#################---]
  > imputador: knn_3
     ok random_forest              acc=0.775  mf1=0.737  wf1=0.789  [###############-----]
     ok lightgbm                   acc=0.817  mf1=0.780  wf1=0.827  [################----]
  > imputador: knn_7
     ok logistic_regression        acc=0.819  mf1=0.693  wf1=0.844  [################----]
     ok lightgbm                   acc=0.799  mf1=0.761  wf1=0.811  [################----]
  > imputador: iterative
     ok logistic_regression        acc=0.787  mf1=0.746  wf1=0.799  [###############-----]
     ok random_forest              acc=0.837  mf1=0.717  wf1=0.858  [#################---]
     ok random_forest              acc=0.782  mf1=0.745  wf1=0.796  [###############-----]
     ok lightgbm                   acc=0.810  mf1=0.772  wf1=0.820  [################----]
  > imputador: miceforest
  [miceforest] fallback SimpleImputer (AssertionError)
     ok logistic_regression        acc=0.739  mf1=0.694  wf1=0.755  [###############-----]
     ok random_forest              acc=0.801  mf1=0.765  wf1=0.813  [################----]
     ok lightgbm                   acc=0.820  mf1=0.784  wf1=0.830  [################----]

  EXPERIMENTO  MNAR  30%  [adult]
  --------------------------------------------------
  > imputador: dropna
     ok logistic_regression        acc=0.872  mf1=0.774  wf1=0.879  [#################---]
     ok random_forest              acc=0.894  mf1=0.693  wf1=0.867  [#################---]
     ok lightgbm                   acc=0.851  mf1=0.722  wf1=0.855  [#################---]
  > imputador: simple_mean
     ok logistic_regression        acc=0.793  mf1=0.752  wf1=0.805  [################----]
     ok random_forest              acc=0.787  mf1=0.752  wf1=0.800  [################----]
     ok lightgbm                   acc=0.822  mf1=0.786  wf1=0.832  [################----]
  > imputador: simple_median
     ok logistic_regression        acc=0.791  mf1=0.750  wf1=0.803  [################----]
     ok random_forest              acc=0.784  mf1=0.750  wf1=0.798  [###############-----]
     ok lightgbm                   acc=0.817  mf1=0.781  wf1=0.827  [################----]
  > imputador: simple_freq
     ok logistic_regression        acc=0.792  mf1=0.751  wf1=0.804  [################----]
     ok random_forest              acc=0.785  mf1=0.751  wf1=0.799  [###############-----]
     ok lightgbm                   acc=0.818  mf1=0.782  wf1=0.828  [################----]
  > imputador: simple_const
     ok logistic_regression        acc=0.765  mf1=0.725  wf1=0.780  [###############-----]
     ok random_forest              acc=0.774  mf1=0.739  wf1=0.789  [###############-----]
     ok lightgbm                   acc=0.823  mf1=0.787  wf1=0.833  [################----]
  > imputador: knn_3
     ok lightgbm                   acc=0.839  mf1=0.726  wf1=0.861  [#################---]
  > imputador: knn_5
     ok logistic_regression        acc=0.773  mf1=0.733  wf1=0.787  [###############-----]
     ok logistic_regression        acc=0.780  mf1=0.742  wf1=0.794  [###############-----]
     ok logistic_regression        acc=0.819  mf1=0.694  wf1=0.844  [################----]
     ok random_forest              acc=0.787  mf1=0.746  wf1=0.799  [###############-----]
     ok random_forest              acc=0.839  mf1=0.721  wf1=0.860  [#################---]
     ok lightgbm                   acc=0.840  mf1=0.727  wf1=0.861  [#################---]
  > imputador: knn_7
     ok random_forest              acc=0.773  mf1=0.740  wf1=0.788  [###############-----]
     ok logistic_regression        acc=0.776  mf1=0.736  wf1=0.789  [###############-----]
     ok lightgbm                   acc=0.812  mf1=0.774  wf1=0.822  [################----]
  > imputador: iterative
     ok logistic_regression        acc=0.780  mf1=0.740  wf1=0.793  [###############-----]
     ok random_forest              acc=0.799  mf1=0.758  wf1=0.810  [################----]
     ok lightgbm                   acc=0.815  mf1=0.777  wf1=0.825  [################----]
  > imputador: miceforest
  [miceforest] fallback SimpleImputer (AssertionError)
     ok logistic_regression        acc=0.774  mf1=0.730  wf1=0.787  [###############-----]
     ok random_forest              acc=0.798  mf1=0.765  wf1=0.811  [################----]
     ok lightgbm                   acc=0.833  mf1=0.799  wf1=0.842  [################----]

  EXPERIMENTO  MNAR  30%  [adult]
  --------------------------------------------------
  > imputador: dropna
     ok logistic_regression        acc=0.868  mf1=0.859  wf1=0.872  [#################---]
     ok random_forest              acc=0.853  mf1=0.828  wf1=0.853  [#################---]
     ok lightgbm                   acc=0.824  mf1=0.793  wf1=0.824  [################----]
  > imputador: simple_mean
     ok logistic_regression        acc=0.798  mf1=0.758  wf1=0.810  [################----]
     ok random_forest              acc=0.795  mf1=0.758  wf1=0.807  [################----]
     ok lightgbm                   acc=0.824  mf1=0.787  wf1=0.833  [################----]
  > imputador: simple_median
     ok logistic_regression        acc=0.798  mf1=0.758  wf1=0.810  [################----]
     ok random_forest              acc=0.788  mf1=0.752  wf1=0.801  [################----]
     ok lightgbm                   acc=0.823  mf1=0.786  wf1=0.833  [################----]
  > imputador: simple_freq
     ok logistic_regression        acc=0.804  mf1=0.763  wf1=0.814  [################----]
     ok logistic_regression        acc=0.820  mf1=0.695  wf1=0.845  [################----]
     ok random_forest              acc=0.812  mf1=0.772  wf1=0.822  [################----]
     ok lightgbm                   acc=0.829  mf1=0.791  wf1=0.837  [################----]
  > imputador: simple_const
     ok logistic_regression        acc=0.791  mf1=0.749  wf1=0.803  [################----]
     ok random_forest              acc=0.799  mf1=0.760  wf1=0.811  [################----]
     ok lightgbm                   acc=0.830  mf1=0.792  wf1=0.838  [################----]
  > imputador: knn_3
     ok random_forest              acc=0.838  mf1=0.719  wf1=0.859  [#################---]
     ok lightgbm                   acc=0.817  mf1=0.780  wf1=0.827  [################----]
  > imputador: iterative
     ok logistic_regression        acc=0.785  mf1=0.747  wf1=0.798  [###############-----]
     ok random_forest              acc=0.783  mf1=0.749  wf1=0.797  [###############-----]
     ok lightgbm                   acc=0.816  mf1=0.779  wf1=0.826  [################----]
  > imputador: miceforest
  [miceforest] fallback SimpleImputer (AssertionError)
     ok logistic_regression        acc=0.755  mf1=0.710  wf1=0.769  [###############-----]
     ok random_forest              acc=0.795  mf1=0.760  wf1=0.808  [################----]
     ok lightgbm                   acc=0.827  mf1=0.791  wf1=0.836  [################----]

  EXPERIMENTO  MNAR  30%  [adult]
  --------------------------------------------------
  > imputador: dropna
     ok logistic_regression        acc=0.870  mf1=0.801  wf1=0.875  [#################---]
     ok random_forest              acc=0.924  mf1=0.857  wf1=0.919  [##################--]
     ok lightgbm                   acc=0.870  mf1=0.784  wf1=0.870  [#################---]
  > imputador: simple_mean
     ok logistic_regression        acc=0.794  mf1=0.755  wf1=0.806  [################----]
     ok random_forest              acc=0.777  mf1=0.742  wf1=0.791  [###############-----]
     ok random_forest              acc=0.775  mf1=0.741  wf1=0.790  [###############-----]
     ok lightgbm                   acc=0.815  mf1=0.778  wf1=0.825  [################----]
  > imputador: simple_median
     ok logistic_regression        acc=0.790  mf1=0.751  wf1=0.802  [################----]
     ok random_forest              acc=0.774  mf1=0.740  wf1=0.789  [###############-----]
     ok lightgbm                   acc=0.816  mf1=0.779  wf1=0.826  [################----]
  > imputador: simple_freq
     ok logistic_regression        acc=0.787  mf1=0.749  wf1=0.800  [###############-----]
     ok random_forest              acc=0.757  mf1=0.726  wf1=0.774  [###############-----]
     ok lightgbm                   acc=0.816  mf1=0.779  wf1=0.826  [################----]
  > imputador: simple_const
     ok lightgbm                   acc=0.846  mf1=0.734  wf1=0.866  [#################---]
  > imputador: iterative
     ok logistic_regression        acc=0.773  mf1=0.737  wf1=0.788  [###############-----]
     ok logistic_regression        acc=0.822  mf1=0.697  wf1=0.846  [################----]
     ok random_forest              acc=0.751  mf1=0.721  wf1=0.769  [###############-----]
     ok random_forest              acc=0.837  mf1=0.717  wf1=0.858  [#################---]
     ok lightgbm                   acc=0.816  mf1=0.779  wf1=0.826  [################----]
  > imputador: knn_3
     ok lightgbm                   acc=0.843  mf1=0.730  wf1=0.864  [#################---]
  > imputador: miceforest
  [miceforest] fallback SimpleImputer (AssertionError)
     ok logistic_regression        acc=0.785  mf1=0.658  wf1=0.818  [################----]
     ok random_forest              acc=0.844  mf1=0.721  wf1=0.863  [#################---]
     ok lightgbm                   acc=0.841  mf1=0.727  wf1=0.862  [#################---]

  EXPERIMENTO  MCAR  15%  [bank_marketing]
  --------------------------------------------------
  > imputador: dropna
     ok logistic_regression        acc=0.756  mf1=0.723  wf1=0.773  [###############-----]
     ok random_forest              acc=0.772  mf1=0.663  wf1=0.764  [###############-----]
     ok lightgbm                   acc=0.780  mf1=0.708  wf1=0.784  [###############-----]
  > imputador: simple_mean
     ok logistic_regression        acc=0.823  mf1=0.697  wf1=0.847  [################----]
     ok random_forest              acc=0.831  mf1=0.709  wf1=0.853  [#################---]
     ok lightgbm                   acc=0.842  mf1=0.726  wf1=0.862  [#################---]
  > imputador: simple_median
     ok logistic_regression        acc=0.825  mf1=0.699  wf1=0.848  [################----]
     ok random_forest              acc=0.832  mf1=0.712  wf1=0.854  [#################---]
     ok lightgbm                   acc=0.845  mf1=0.729  wf1=0.865  [#################---]
  > imputador: simple_freq
     ok logistic_regression        acc=0.821  mf1=0.695  wf1=0.845  [################----]
     ok random_forest              acc=0.839  mf1=0.714  wf1=0.859  [#################---]

 17%|█▋        | 2/12 [8:21:08<41:45:43, 15034.36s/it]

     ok lightgbm                   acc=0.826  mf1=0.789  wf1=0.835  [################----]
[cache] data\bank_marketing\bank.zip
[cache] data\bank_marketing\extracted

========================================================================
  CLASSIFICACAO  |  BANK_MARKETING  |  target: y
========================================================================
  classes: no: 39922 (88%)  |  yes: 5289 (12%)
     ok logistic_regression        acc=0.844  mf1=0.730  wf1=0.865  [#################---]
     ok random_forest              acc=0.903  mf1=0.700  wf1=0.889  [#################---]
     ok lightgbm                   acc=0.856  mf1=0.753  wf1=0.875  [#################---]

  EXPERIMENTO  MCAR   1%  [bank_marketing]
  --------------------------------------------------
  > imputador: dropna
     ok logistic_regression        acc=0.806  mf1=0.760  wf1=0.816  [################----]
     ok random_forest              acc=0.825  mf1=0.771  wf1=0.830  [################----]
     ok lightgbm                   acc=0.825  mf1=0.778  wf1=0.833  [################----]
  > imputador: simple_mean
     ok logistic_regression        acc=0.842  mf1=0.727  wf1=0.863  [#################---]
     ok random_forest              acc=0.842  mf1=0.729  wf1=0.863  [#################---]
     ok lightgbm                   acc=0.857  mf1=0.754  wf1=0.876  [#################---]
  > imputador: simple_median
     ok logistic_regression        acc=0.842  mf1=0.727  wf1=0.863  [#################---]
     ok random_forest              acc=0.838  mf1=0.724  wf1=0.860  [#################---]
     ok lightgbm                   acc=0.856  mf1=0.751  wf1=0.875  [#################---]
  > imputador: simple_freq
     ok logistic_regression        acc=0.842  mf1=0.726  wf1=0.862  [#################---]
     ok random_forest              acc=0.841  mf1=0.728  wf1=0.862  [#################---]
     ok lightgbm                   acc=0.855  mf1=0.751  wf1=0.874  [#################---]
  > imputador: simple_const
     ok logistic_regression        acc=0.841  mf1=0.726  wf1=0.862  [#################---]
     ok random_forest              acc=0.848  mf1=0.736  wf1=0.868  [#################---]
     ok lightgbm                   acc=0.855  mf1=0.750  wf1=0.874  [#################---]
  > imputador: knn_3
     ok logistic_regression        acc=0.791  mf1=0.750  wf1=0.803  [################----]
     ok logistic_regression        acc=0.841  mf1=0.725  wf1=0.861  [#################---]
     ok random_forest              acc=0.838  mf1=0.724  wf1=0.860  [#################---]
     ok lightgbm                   acc=0.853  mf1=0.748  wf1=0.873  [#################---]
  > imputador: knn_5
     ok logistic_regression        acc=0.841  mf1=0.725  wf1=0.862  [#################---]
     ok random_forest              acc=0.843  mf1=0.730  wf1=0.864  [#################---]
     ok lightgbm                   acc=0.853  mf1=0.748  wf1=0.873  [#################---]
  > imputador: knn_7
     ok random_forest              acc=0.818  mf1=0.687  wf1=0.842  [################----]
     ok logistic_regression        acc=0.841  mf1=0.725  wf1=0.862  [#################---]
     ok random_forest              acc=0.840  mf1=0.728  wf1=0.862  [#################---]
     ok lightgbm                   acc=0.812  mf1=0.775  wf1=0.823  [################----]
  > imputador: knn_7
     ok lightgbm                   acc=0.858  mf1=0.755  wf1=0.877  [#################---]
  > imputador: iterative
     ok logistic_regression        acc=0.842  mf1=0.726  wf1=0.863  [#################---]
     ok random_forest              acc=0.844  mf1=0.732  wf1=0.865  [#################---]
     ok lightgbm                   acc=0.858  mf1=0.754  wf1=0.876  [#################---]
  > imputador: miceforest
  [miceforest] fallback SimpleImputer (AssertionError)
     ok logistic_regression        acc=0.808  mf1=0.681  wf1=0.835  [################----]
     ok random_forest              acc=0.847  mf1=0.731  wf1=0.867  [#################---]
     ok lightgbm                   acc=0.853  mf1=0.748  wf1=0.872  [#################---]

  EXPERIMENTO  MCAR   5%  [bank_marketing]
  --------------------------------------------------
  > imputador: dropna
     ok logistic_regression        acc=0.795  mf1=0.751  wf1=0.806  [################----]
     ok random_forest              acc=0.829  mf1=0.776  wf1=0.833  [################----]
     ok lightgbm                   acc=0.836  mf1=0.786  wf1=0.840  [################----]
  > imputador: simple_mean
     ok logistic_regression        acc=0.840  mf1=0.723  wf1=0.861  [#################---]
     ok random_forest              acc=0.840  mf1=0.724  wf1=0.861  [#################---]
     ok lightgbm                   acc=0.850  mf1=0.743  wf1=0.870  [#################---]
  > imputador: simple_median
     ok logistic_regression        acc=0.839  mf1=0.721  wf1=0.860  [#################---]
     ok random_forest              acc=0.837  mf1=0.720  wf1=0.858  [#################---]
     ok lightgbm                   acc=0.851  mf1=0.743  wf1=0.871  [#################---]
  > imputador: simple_freq
     ok logistic_regression        acc=0.837  mf1=0.719  wf1=0.858  [#################---]
     ok random_forest              acc=0.840  mf1=0.726  wf1=0.862  [#################---]
     ok lightgbm                   acc=0.849  mf1=0.740  wf1=0.869  [#################---]
  > imputador: simple_const
     ok logistic_regression        acc=0.835  mf1=0.717  wf1=0.857  [#################---]
     ok random_forest              acc=0.839  mf1=0.722  wf1=0.860  [#################---]
     ok lightgbm                   acc=0.847  mf1=0.738  wf1=0.867  [#################---]
  > imputador: knn_3
     ok random_forest              acc=0.787  mf1=0.750  wf1=0.800  [################----]
     ok logistic_regression        acc=0.834  mf1=0.716  wf1=0.857  [#################---]
     ok lightgbm                   acc=0.824  mf1=0.700  wf1=0.848  [################----]
  > imputador: knn_5
     ok random_forest              acc=0.832  mf1=0.716  wf1=0.855  [#################---]
     ok lightgbm                   acc=0.842  mf1=0.733  wf1=0.864  [#################---]
  > imputador: knn_5
     ok logistic_regression        acc=0.835  mf1=0.717  wf1=0.857  [#################---]
     ok lightgbm                   acc=0.817  mf1=0.780  wf1=0.827  [################----]
  > imputador: iterative
     ok logistic_regression        acc=0.792  mf1=0.752  wf1=0.804  [################----]
     ok random_forest              acc=0.800  mf1=0.762  wf1=0.812  [################----]
     ok lightgbm                   acc=0.822  mf1=0.784  wf1=0.831  [################----]
  > imputador: miceforest
  [miceforest] fallback SimpleImputer (AssertionError)
     ok logistic_regression        acc=0.791  mf1=0.750  wf1=0.803  [################----]
     ok random_forest              acc=0.804  mf1=0.769  wf1=0.816  [################----]

 25%|██▌       | 3/12 [8:28:35<25:25:45, 10171.75s/it]

     ok lightgbm                   acc=0.829  mf1=0.794  wf1=0.838  [################----]
[cache] data\air_quality_uci\AirQualityUCI.zip
[cache] data\air_quality_uci\extracted

========================================================================
  REGRESSAO  |  AIR_QUALITY_UCI  |  target: C6H6(GT)
========================================================================
     ok ridge_regression           mae=0.8335  rmse=1.1483  r2=0.9771  [###################-]
     ok random_forest              mae=0.0169  rmse=0.1478  r2=0.9996  [###################-]
     ok lightgbm                   mae=0.0608  rmse=0.2645  r2=0.9988  [###################-]

  EXPERIMENTO  MCAR   1%  [air_quality_uci]
  --------------------------------------------------
  > imputador: dropna
     ok ridge_regression           mae=0.4524  rmse=0.6205  r2=0.9930  [###################-]
     ok random_forest              mae=0.0725  rmse=0.2107  r2=0.9992  [###################-]
     ok lightgbm                   mae=0.1681  rmse=0.5514  r2=0.9945  [###################-]
  > imputador: simple_mean
     ok ridge_regression           mae=0.9029  rmse=1.4315  r2=0.9643  [###################-]
     ok random_forest              mae=0.0652  rmse=0.4523  r2=0.9964  [###################-]
     ok lightgbm                   mae=0.1308  rmse=0.5003  r2=0.9956  [###################-]
  > imputador: simple_median
     ok ridge_regression           mae=0.9164  rmse=1.4540  r2=0.9632  [###################-]
     ok random_forest              acc=0.835  mf1=0.719  wf1=0.857  [#################---]
     ok random_forest              mae=0.0539  rmse=0.3961  r2=0.9973  [###################-]
     ok lightgbm                   mae=0.1327  rmse=0.5185  r2=0.9953  [###################-]
  > imputador: simple_freq
     ok ridge_regression           mae=0.9501  rmse=1.5086  r2=0.9604  [###################-]
     ok random_forest              mae=0.0525  rmse=0.4183  r2=0.9970  [###################-]
     ok lightgbm                   mae=0.1308  rmse=0.4896  r2=0.9958  [###################-]
  > imputador: simple_const
     ok ridge_regression           mae=1.3776  rmse=2.2298  r2=0.9135  [##################--]
     ok random_forest              mae=0.0393  rmse=0.3199  r2=0.9982  [###################-]
     ok lightgbm                   mae=0.1072  rmse=0.4109  r2=0.9971  [###################-]
  > imputador: knn_3
     ok ridge_regression           mae=0.7291  rmse=1.0562  r2=0.9806  [###################-]
     ok random_forest              mae=0.0448  rmse=0.2894  r2=0.9985  [###################-]
     ok lightgbm                   mae=0.0867  rmse=0.3524  r2=0.9978  [###################-]
  > imputador: knn_5
     ok lightgbm                   acc=0.849  mf1=0.741  wf1=0.869  [#################---]
  > imputador: knn_7
     ok ridge_regression           mae=0.6936  rmse=1.0322  r2=0.9815  [###################-]
     ok random_forest              mae=0.0435  rmse=0.3062  r2=0.9984  [###################-]
     ok lightgbm                   mae=0.0831  rmse=0.3427  r2=0.9980  [###################-]
  > imputador: knn_7
     ok logistic_regression        acc=0.806  mf1=0.676  wf1=0.833  [################----]
     ok ridge_regression           mae=0.6653  rmse=1.0119  r2=0.9822  [###################-]
     ok random_forest              mae=0.0485  rmse=0.3363  r2=0.9980  [###################-]
     ok lightgbm                   mae=0.0871  rmse=0.3502  r2=0.9979  [###################-]
  > imputador: iterative
     ok ridge_regression           mae=0.8146  rmse=1.1349  r2=0.9776  [###################-]
     ok random_forest              mae=0.0381  rmse=0.2449  r2=0.9990  [###################-]
     ok lightgbm                   mae=0.0717  rmse=0.2737  r2=0.9987  [###################-]
  > imputador: miceforest
  [miceforest] fallback SimpleImputer (AssertionError)
     ok ridge_regression           mae=0.9029  rmse=1.4315  r2=0.9643  [###################-]
     ok random_forest              mae=0.0652  rmse=0.4523  r2=0.9964  [###################-]
     ok lightgbm                   mae=0.1308  rmse=0.5003  r2=0.9956  [###################-]

  EXPERIMENTO  MCAR   5%  [air_quality_uci]
  --------------------------------------------------
  > imputador: dropna
     ok ridge_regression           mae=0.4696  rmse=0.6257  r2=0.9931  [###################-]
     ok random_forest              mae=0.0917  rmse=0.2207  r2=0.9991  [###################-]
     ok lightgbm                   mae=0.2516  rmse=0.6613  r2=0.9922  [###################-]
  > imputador: simple_mean
     ok ridge_regression           mae=1.1475  rmse=1.7992  r2=0.9437  [##################--]
     ok logistic_regression        acc=0.836  mf1=0.719  wf1=0.858  [#################---]
     ok random_forest              mae=0.1888  rmse=0.8238  r2=0.9882  [###################-]
     ok lightgbm                   mae=0.2012  rmse=0.6628  r2=0.9924  [###################-]
  > imputador: simple_median
     ok ridge_regression           mae=1.1726  rmse=1.8428  r2=0.9409  [##################--]
     ok logistic_regression        acc=0.786  mf1=0.747  wf1=0.799  [###############-----]
     ok random_forest              mae=0.1886  rmse=0.8230  r2=0.9882  [###################-]
     ok lightgbm                   mae=0.1997  rmse=0.6798  r2=0.9920  [###################-]
  > imputador: simple_freq
     ok ridge_regression           mae=1.2467  rmse=1.9516  r2=0.9337  [##################--]
     ok random_forest              mae=0.1951  rmse=0.8321  r2=0.9879  [###################-]
     ok lightgbm                   mae=0.2021  rmse=0.6797  r2=0.9920  [###################-]
  > imputador: simple_const
     ok ridge_regression           mae=2.3530  rmse=3.4019  r2=0.7986  [###############-----]
     ok random_forest              mae=0.1176  rmse=0.6143  r2=0.9934  [###################-]
     ok lightgbm                   mae=0.1610  rmse=0.5968  r2=0.9938  [###################-]
  > imputador: knn_3
     ok ridge_regression           mae=0.7855  rmse=1.1616  r2=0.9765  [###################-]
     ok random_forest              mae=0.1914  rmse=0.7658  r2=0.9898  [###################-]
     ok lightgbm                   mae=0.2417  rmse=0.7535  r2=0.9901  [###################-]
  > imputador: knn_5
     ok random_forest              acc=0.836  mf1=0.719  wf1=0.858  [#################---]
     ok ridge_regression           mae=0.7431  rmse=1.1084  r2=0.9786  [###################-]
     ok random_forest              mae=0.1806  rmse=0.6602  r2=0.9924  [###################-]
     ok lightgbm                   mae=0.2213  rmse=0.6568  r2=0.9925  [###################-]
  > imputador: knn_7
     ok ridge_regression           mae=0.7231  rmse=1.0930  r2=0.9792  [###################-]
     ok lightgbm                   acc=0.848  mf1=0.739  wf1=0.868  [#################---]
  > imputador: iterative
     ok logistic_regression        acc=0.839  mf1=0.722  wf1=0.860  [#################---]
     ok random_forest              acc=0.840  mf1=0.722  wf1=0.861  [#################---]
     ok random_forest              mae=0.1698  rmse=0.6382  r2=0.9929  [###################-]
     ok lightgbm                   acc=0.849  mf1=0.740  wf1=0.869  [#################---]
  > imputador: miceforest
  [miceforest] fallback SimpleImputer (AssertionError)
     ok logistic_regression        acc=0.805  mf1=0.679  wf1=0.833  [################----]
     ok random_forest              acc=0.850  mf1=0.734  wf1=0.869  [#################---]
     ok lightgbm                   mae=0.2183  rmse=0.6745  r2=0.9921  [###################-]
  > imputador: iterative
     ok lightgbm                   acc=0.850  mf1=0.741  wf1=0.870  [#################---]

  EXPERIMENTO  MCAR  10%  [bank_marketing]
  --------------------------------------------------
  > imputador: dropna
     ok logistic_regression        acc=0.807  mf1=0.735  wf1=0.819  [################----]
     ok random_forest              acc=0.824  mf1=0.710  wf1=0.821  [################----]
     ok lightgbm                   acc=0.845  mf1=0.763  wf1=0.847  [################----]
  > imputador: simple_mean
     ok logistic_regression        acc=0.833  mf1=0.713  wf1=0.855  [#################---]
     ok ridge_regression           mae=0.8484  rmse=1.1851  r2=0.9756  [###################-]
     ok random_forest              acc=0.822  mf1=0.692  wf1=0.845  [################----]
     ok random_forest              acc=0.829  mf1=0.710  wf1=0.853  [#################---]
     ok lightgbm                   acc=0.839  mf1=0.727  wf1=0.861  [#################---]
  > imputador: simple_median
     ok random_forest              mae=0.1322  rmse=0.4788  r2=0.9960  [###################-]
     ok logistic_regression        acc=0.832  mf1=0.711  wf1=0.854  [#################---]
     ok lightgbm                   mae=0.1672  rmse=0.4803  r2=0.9960  [###################-]
  > imputador: miceforest
  [miceforest] fallback SimpleImputer (AssertionError)
     ok ridge_regression           mae=1.1475  rmse=1.7992  r2=0.9437  [##################--]
     ok random_forest              acc=0.830  mf1=0.711  wf1=0.853  [#################---]
     ok random_forest              mae=0.1888  rmse=0.8238  r2=0.9882  [###################-]
     ok lightgbm                   acc=0.842  mf1=0.730  wf1=0.863  [#################---]
  > imputador: simple_freq
     ok lightgbm                   mae=0.2012  rmse=0.6628  r2=0.9924  [###################-]

  EXPERIMENTO  MCAR  10%  [air_quality_uci]
  --------------------------------------------------
  > imputador: dropna
     ok ridge_regression           mae=0.4409  rmse=0.6139  r2=0.9892  [###################-]
     ok random_forest              mae=0.1993  rmse=0.3965  r2=0.9955  [###################-]
     ok lightgbm                   mae=0.8383  rmse=1.6168  r2=0.9250  [##################--]
  > imputador: simple_mean
     ok ridge_regression           mae=1.3283  rmse=1.9524  r2=0.9337  [##################--]
     ok logistic_regression        acc=0.832  mf1=0.711  wf1=0.855  [#################---]
     ok random_forest              mae=0.2391  rmse=0.8036  r2=0.9888  [###################-]
     ok lightgbm                   mae=0.2716  rmse=0.7442  r2=0.9904  [###################-]
  > imputador: simple_median
     ok ridge_regression           mae=1.3459  rmse=1.9884  r2=0.9312  [##################--]
     ok random_forest              acc=0.829  mf1=0.711  wf1=0.853  [#################---]
     ok lightgbm                   acc=0.841  mf1=0.729  wf1=0.863  [#################---]
  > imputador: simple_const
     ok logistic_regression        acc=0.830  mf1=0.709  wf1=0.853  [#################---]
     ok random_forest              mae=0.2453  rmse=0.8043  r2=0.9887  [###################-]
     ok lightgbm                   mae=0.2775  rmse=0.7514  r2=0.9902  [###################-]
  > imputador: simple_freq
     ok ridge_regression           mae=1.4464  rmse=2.1134  r2=0.9223  [##################--]
     ok random_forest              acc=0.842  mf1=0.720  wf1=0.861  [#################---]
     ok random_forest              mae=0.2447  rmse=0.8031  r2=0.9888  [###################-]
     ok lightgbm                   mae=0.2709  rmse=0.7167  r2=0.9911  [###################-]
  > imputador: simple_const
     ok ridge_regression           mae=2.7457  rmse=3.7484  r2=0.7555  [###############-----]
     ok lightgbm                   acc=0.840  mf1=0.728  wf1=0.862  [#################---]
  > imputador: knn_3
     ok random_forest              mae=0.2155  rmse=0.7864  r2=0.9892  [###################-]
     ok lightgbm                   mae=0.2654  rmse=0.7718  r2=0.9896  [###################-]
  > imputador: knn_3
     ok ridge_regression           mae=0.9432  rmse=1.4543  r2=0.9632  [###################-]
     ok random_forest              mae=0.3748  rmse=1.1023  r2=0.9789  [###################-]
     ok lightgbm                   mae=0.4609  rmse=0.9670  r2=0.9837  [###################-]
  > imputador: knn_5
     ok ridge_regression           mae=0.8753  rmse=1.3480  r2=0.9684  [###################-]
     ok random_forest              mae=0.3183  rmse=0.9250  r2=0.9851  [###################-]
     ok lightgbm                   mae=0.4062  rmse=0.8642  r2=0.9870  [###################-]
  > imputador: knn_7
     ok ridge_regression           mae=0.8392  rmse=1.2765  r2=0.9716  [###################-]
     ok random_forest              mae=0.2977  rmse=0.8847  r2=0.9864  [###################-]
     ok lightgbm                   mae=0.3809  rmse=0.8094  r2=0.9886  [###################-]
  > imputador: iterative
     ok ridge_regression           mae=0.8923  rmse=1.2857  r2=0.9712  [###################-]
     ok random_forest              acc=0.766  mf1=0.734  wf1=0.782  [###############-----]
     ok random_forest              mae=0.2344  rmse=0.7380  r2=0.9905  [###################-]
     ok lightgbm                   mae=0.2613  rmse=0.7186  r2=0.9910  [###################-]
  > imputador: miceforest
  [miceforest] fallback SimpleImputer (AssertionError)
     ok ridge_regression           mae=1.3283  rmse=1.9524  r2=0.9337  [##################--]
     ok lightgbm                   acc=0.828  mf1=0.706  wf1=0.851  [#################---]
  > imputador: knn_7
     ok random_forest              mae=0.2391  rmse=0.8036  r2=0.9888  [###################-]
     ok lightgbm                   mae=0.2716  rmse=0.7442  r2=0.9904  [###################-]

  EXPERIMENTO  MCAR  15%  [air_quality_uci]
  --------------------------------------------------
  > imputador: dropna
     ok ridge_regression           mae=0.6739  rmse=1.2860  r2=0.9789  [###################-]
     ok random_forest              mae=1.2896  rmse=3.4531  r2=0.8476  [################----]
     ok lightgbm                   mae=2.4424  rmse=5.0723  r2=0.6711  [#############-------]
  > imputador: simple_mean
     ok ridge_regression           mae=1.5680  rmse=2.3525  r2=0.9037  [##################--]
     ok random_forest              mae=0.3871  rmse=1.3297  r2=0.9692  [###################-]
     ok lightgbm                   mae=0.3992  rmse=1.1454  r2=0.9772  [###################-]
  > imputador: simple_median
     ok ridge_regression           mae=1.5798  rmse=2.3846  r2=0.9010  [##################--]
     ok random_forest              mae=0.3994  rmse=1.3320  r2=0.9691  [###################-]
     ok lightgbm                   mae=0.3987  rmse=1.1521  r2=0.9769  [###################-]
  > imputador: simple_freq
     ok ridge_regression           mae=1.6644  rmse=2.5019  r2=0.8911  [#################---]
     ok logistic_regression        acc=0.824  mf1=0.703  wf1=0.848  [################----]
     ok random_forest              mae=0.3768  rmse=1.3127  r2=0.9700  [###################-]
     ok lightgbm                   mae=0.3790  rmse=1.1126  r2=0.9785  [###################-]
  > imputador: simple_const
     ok ridge_regression           mae=3.0670  rmse=4.3226  r2=0.6748  [#############-------]
     ok random_forest              mae=0.2981  rmse=1.1388  r2=0.9774  [###################-]
     ok lightgbm                   mae=0.3468  rmse=1.0685  r2=0.9801  [###################-]
  > imputador: knn_3
     ok ridge_regression           mae=1.3445  rmse=2.1738  r2=0.9178  [##################--]
     ok random_forest              mae=0.5634  rmse=1.6002  r2=0.9554  [###################-]
     ok lightgbm                   mae=0.6602  rmse=1.5047  r2=0.9606  [###################-]
  > imputador: knn_5
     ok ridge_regression           mae=1.1923  rmse=1.9458  r2=0.9341  [##################--]
     ok random_forest              mae=0.5332  rmse=1.5277  r2=0.9594  [###################-]
     ok random_forest              acc=0.824  mf1=0.702  wf1=0.848  [################----]
     ok lightgbm                   mae=0.6152  rmse=1.3967  r2=0.9661  [###################-]
  > imputador: knn_7
     ok ridge_regression           mae=1.1196  rmse=1.8687  r2=0.9392  [##################--]
     ok random_forest              mae=0.5018  rmse=1.5148  r2=0.9601  [###################-]
     ok lightgbm                   mae=0.6014  rmse=1.4288  r2=0.9645  [###################-]
  > imputador: iterative
     ok ridge_regression           mae=0.9450  rmse=1.3595  r2=0.9678  [###################-]
     ok random_forest              mae=0.3299  rmse=0.8315  r2=0.9880  [###################-]
     ok lightgbm                   mae=0.3621  rmse=0.8262  r2=0.9881  [###################-]
  > imputador: miceforest
  [miceforest] fallback SimpleImputer (AssertionError)
     ok ridge_regression           mae=1.5680  rmse=2.3525  r2=0.9037  [##################--]
     ok random_forest              mae=0.3871  rmse=1.3297  r2=0.9692  [###################-]
     ok lightgbm                   mae=0.3992  rmse=1.1454  r2=0.9772  [###################-]

  EXPERIMENTO  MCAR  20%  [air_quality_uci]
  --------------------------------------------------
  > imputador: dropna
     ok ridge_regression           mae=0.2899  rmse=0.3831  r2=0.9944  [###################-]
     ok random_forest              mae=0.8871  rmse=0.9988  r2=0.9617  [###################-]
     ok lightgbm                   mae=2.2063  rmse=2.4660  r2=0.7665  [###############-----]
  > imputador: simple_mean
     ok ridge_regression           mae=1.6781  rmse=2.4459  r2=0.8959  [#################---]
     ok random_forest              mae=0.4682  rmse=1.1778  r2=0.9759  [###################-]
     ok lightgbm                   mae=0.4444  rmse=0.9893  r2=0.9830  [###################-]
  > imputador: simple_median
     ok ridge_regression           mae=1.6819  rmse=2.4807  r2=0.8929  [#################---]
     ok random_forest              mae=0.4835  rmse=1.1871  r2=0.9755  [###################-]
     ok lightgbm                   mae=0.4406  rmse=0.9737  r2=0.9835  [###################-]
  > imputador: simple_freq
     ok ridge_regression           mae=1.8779  rmse=2.7553  r2=0.8679  [#################---]
     ok random_forest              mae=0.4716  rmse=1.1903  r2=0.9753  [###################-]
     ok lightgbm                   mae=0.4482  rmse=0.9972  r2=0.9827  [###################-]
  > imputador: simple_const
     ok ridge_regression           mae=3.2699  rmse=4.4905  r2=0.6491  [############--------]
     ok random_forest              mae=0.4350  rmse=1.1379  r2=0.9775  [###################-]
     ok lightgbm                   mae=0.4174  rmse=0.9681  r2=0.9837  [###################-]
  > imputador: knn_3
     ok lightgbm                   acc=0.830  mf1=0.717  wf1=0.854  [#################---]
  > imputador: knn_5
     ok ridge_regression           mae=1.5757  rmse=2.4769  r2=0.8932  [#################---]
     ok random_forest              mae=0.7072  rmse=1.6493  r2=0.9527  [###################-]
     ok lightgbm                   mae=0.7795  rmse=1.4944  r2=0.9611  [###################-]
  > imputador: knn_5
     ok ridge_regression           mae=1.4192  rmse=2.2751  r2=0.9099  [##################--]
     ok lightgbm                   acc=0.812  mf1=0.774  wf1=0.822  [################----]
  > imputador: iterative
     ok random_forest              mae=0.6584  rmse=1.5899  r2=0.9560  [###################-]
     ok logistic_regression        acc=0.791  mf1=0.753  wf1=0.804  [################----]
     ok lightgbm                   mae=0.7086  rmse=1.3326  r2=0.9691  [###################-]
  > imputador: knn_7
     ok random_forest              acc=0.780  mf1=0.745  wf1=0.794  [###############-----]
     ok lightgbm                   acc=0.810  mf1=0.772  wf1=0.820  [################----]
  > imputador: miceforest
  [miceforest] fallback SimpleImputer (AssertionError)
     ok logistic_regression        acc=0.777  mf1=0.734  wf1=0.789  [###############-----]
     ok random_forest              acc=0.789  mf1=0.754  wf1=0.802  [################----]

 33%|███▎      | 4/12 [8:38:27<17:16:54, 7776.76s/it]

     ok lightgbm                   acc=0.818  mf1=0.781  wf1=0.828  [################----]
[cache] data\air_quality_uci\AirQualityUCI.zip
[cache] data\air_quality_uci\extracted

========================================================================
  REGRESSAO  |  AIR_QUALITY_UCI  |  target: C6H6(GT)
========================================================================
     ok ridge_regression           mae=0.8067  rmse=1.1182  r2=0.9780  [###################-]
     ok random_forest              mae=0.0157  rmse=0.1150  r2=0.9998  [###################-]
     ok lightgbm                   mae=0.0502  rmse=0.1878  r2=0.9994  [###################-]

  EXPERIMENTO  MCAR   1%  [air_quality_uci]
  --------------------------------------------------
  > imputador: dropna
     ok ridge_regression           mae=0.4057  rmse=0.4958  r2=0.9956  [###################-]
     ok random_forest              mae=0.0480  rmse=0.0709  r2=0.9999  [###################-]
     ok lightgbm                   mae=0.1730  rmse=0.4668  r2=0.9961  [###################-]
  > imputador: simple_mean
     ok ridge_regression           mae=0.8882  rmse=1.3272  r2=0.9690  [###################-]
     ok ridge_regression           mae=1.3410  rmse=2.1831  r2=0.9171  [##################--]
     ok random_forest              mae=0.0483  rmse=0.3136  r2=0.9983  [###################-]
     ok lightgbm                   mae=0.1123  rmse=0.3305  r2=0.9981  [###################-]
  > imputador: simple_median
     ok ridge_regression           mae=0.8896  rmse=1.3331  r2=0.9687  [###################-]
     ok random_forest              mae=0.0475  rmse=0.2995  r2=0.9984  [###################-]
     ok lightgbm                   mae=0.1157  rmse=0.3174  r2=0.9982  [###################-]
  > imputador: simple_freq
     ok ridge_regression           mae=0.9180  rmse=1.3723  r2=0.9668  [###################-]
     ok logistic_regression        acc=0.807  mf1=0.676  wf1=0.834  [################----]
     ok random_forest              mae=0.0446  rmse=0.2882  r2=0.9985  [###################-]
     ok lightgbm                   mae=0.1132  rmse=0.3139  r2=0.9983  [###################-]
  > imputador: simple_const
     ok ridge_regression           mae=1.3623  rmse=2.1763  r2=0.9166  [##################--]
     ok random_forest              mae=0.0440  rmse=0.3076  r2=0.9983  [###################-]
     ok lightgbm                   mae=0.0947  rmse=0.3333  r2=0.9980  [###################-]
  > imputador: knn_3
     ok random_forest              mae=0.6183  rmse=1.4899  r2=0.9614  [###################-]
     ok ridge_regression           mae=0.6864  rmse=0.9594  r2=0.9838  [###################-]
     ok lightgbm                   mae=0.7016  rmse=1.3069  r2=0.9703  [###################-]
  > imputador: iterative
     ok ridge_regression           mae=0.9685  rmse=1.4618  r2=0.9628  [###################-]
     ok random_forest              mae=0.0357  rmse=0.2173  r2=0.9992  [###################-]
     ok logistic_regression        acc=0.826  mf1=0.705  wf1=0.850  [################----]
     ok random_forest              mae=0.4284  rmse=1.0396  r2=0.9812  [###################-]
     ok lightgbm                   mae=0.0676  rmse=0.2362  r2=0.9990  [###################-]
  > imputador: knn_5
     ok lightgbm                   mae=0.4490  rmse=0.9851  r2=0.9831  [###################-]
  > imputador: miceforest
  [miceforest] fallback SimpleImputer (AssertionError)
     ok ridge_regression           mae=1.6781  rmse=2.4459  r2=0.8959  [#################---]
     ok random_forest              mae=0.4682  rmse=1.1778  r2=0.9759  [###################-]
     ok lightgbm                   mae=0.4444  rmse=0.9893  r2=0.9830  [###################-]

  EXPERIMENTO  MCAR  25%  [air_quality_uci]
  --------------------------------------------------
  > imputador: dropna
     ok ridge_regression           mae=0.7195  rmse=0.7791  r2=-0.4368  [--------------------]
     ok random_forest              mae=1.6910  rmse=1.6938  r2=-5.7903  [--------------------]
     ok lightgbm                   mae=1.3250  rmse=1.4758  r2=-4.1553  [--------------------]
  > imputador: simple_mean
     ok ridge_regression           mae=1.7906  rmse=2.5624  r2=0.8857  [#################---]
     ok ridge_regression           mae=0.6666  rmse=0.9417  r2=0.9844  [###################-]
     ok random_forest              mae=0.6220  rmse=1.4339  r2=0.9642  [###################-]
     ok lightgbm                   mae=0.5389  rmse=1.1229  r2=0.9781  [###################-]
  > imputador: simple_median
     ok ridge_regression           mae=1.8010  rmse=2.5960  r2=0.8827  [#################---]
     ok random_forest              mae=0.6252  rmse=1.4273  r2=0.9645  [###################-]
     ok lightgbm                   mae=0.5305  rmse=1.1133  r2=0.9784  [###################-]
  > imputador: simple_freq
     ok ridge_regression           mae=1.8653  rmse=2.7011  r2=0.8730  [#################---]
     ok random_forest              mae=0.6055  rmse=1.4014  r2=0.9658  [###################-]
     ok lightgbm                   mae=0.5331  rmse=1.0840  r2=0.9796  [###################-]
  > imputador: simple_const
     ok ridge_regression           mae=3.4549  rmse=4.7572  r2=0.6062  [############--------]
     ok random_forest              mae=0.0345  rmse=0.2166  r2=0.9992  [###################-]
     ok random_forest              mae=0.5485  rmse=1.2846  r2=0.9713  [###################-]
     ok lightgbm                   mae=0.5269  rmse=1.1053  r2=0.9787  [###################-]
  > imputador: knn_3
     ok lightgbm                   mae=0.0718  rmse=0.2296  r2=0.9991  [###################-]
  > imputador: knn_7
     ok ridge_regression           mae=0.6513  rmse=0.9231  r2=0.9850  [###################-]
     ok ridge_regression           mae=1.8920  rmse=2.7685  r2=0.8666  [#################---]
     ok random_forest              mae=0.0341  rmse=0.2103  r2=0.9992  [###################-]
     ok lightgbm                   mae=0.0699  rmse=0.2336  r2=0.9990  [###################-]
  > imputador: iterative
     ok ridge_regression           mae=0.7896  rmse=1.0900  r2=0.9791  [###################-]
     ok random_forest              mae=0.9973  rmse=2.0264  r2=0.9285  [##################--]
     ok random_forest              mae=0.0432  rmse=0.2918  r2=0.9985  [###################-]
     ok lightgbm                   mae=0.0746  rmse=0.3178  r2=0.9982  [###################-]
  > imputador: miceforest
  [miceforest] fallback SimpleImputer (AssertionError)
     ok ridge_regression           mae=0.8882  rmse=1.3272  r2=0.9690  [###################-]
     ok random_forest              mae=0.0483  rmse=0.3136  r2=0.9983  [###################-]
     ok lightgbm                   mae=0.1123  rmse=0.3305  r2=0.9981  [###################-]

  EXPERIMENTO  MCAR   5%  [air_quality_uci]
  --------------------------------------------------
  > imputador: dropna
     ok ridge_regression           mae=0.3975  rmse=0.4903  r2=0.9959  [###################-]
     ok random_forest              mae=0.0896  rmse=0.1276  r2=0.9997  [###################-]
     ok lightgbm                   mae=0.2741  rmse=0.5384  r2=0.9951  [###################-]
  > imputador: simple_mean
     ok lightgbm                   mae=1.0654  rmse=1.8843  r2=0.9382  [##################--]
  > imputador: knn_5
     ok ridge_regression           mae=1.1882  rmse=1.8527  r2=0.9395  [##################--]
     ok random_forest              mae=0.1765  rmse=0.7372  r2=0.9904  [###################-]
     ok lightgbm                   mae=0.2065  rmse=0.6380  r2=0.9928  [###################-]
  > imputador: simple_median
     ok ridge_regression           mae=1.1847  rmse=1.8736  r2=0.9382  [##################--]
     ok random_forest              acc=0.828  mf1=0.709  wf1=0.851  [#################---]
     ok random_forest              mae=0.1735  rmse=0.7133  r2=0.9910  [###################-]
     ok lightgbm                   mae=0.2098  rmse=0.6320  r2=0.9930  [###################-]
  > imputador: simple_freq
     ok ridge_regression           mae=1.2171  rmse=1.9385  r2=0.9338  [##################--]
     ok random_forest              mae=0.1849  rmse=0.7512  r2=0.9901  [###################-]
     ok lightgbm                   mae=0.2013  rmse=0.6339  r2=0.9929  [###################-]
  > imputador: simple_const
     ok ridge_regression           mae=2.2752  rmse=3.2807  r2=0.8104  [################----]
     ok random_forest              mae=0.1277  rmse=0.6345  r2=0.9929  [###################-]
     ok lightgbm                   mae=0.1659  rmse=0.6014  r2=0.9936  [###################-]
  > imputador: knn_3
     ok ridge_regression           mae=1.7556  rmse=2.6024  r2=0.8821  [#################---]
     ok ridge_regression           mae=0.7111  rmse=1.0224  r2=0.9816  [###################-]
     ok random_forest              mae=0.7623  rmse=1.6307  r2=0.9537  [###################-]
     ok random_forest              mae=0.1505  rmse=0.5572  r2=0.9945  [###################-]
     ok lightgbm                   mae=0.1923  rmse=0.5410  r2=0.9948  [###################-]
  > imputador: knn_5
     ok lightgbm                   mae=0.9016  rmse=1.5937  r2=0.9558  [###################-]
  > imputador: knn_7
     ok random_forest              acc=0.828  mf1=0.697  wf1=0.850  [################----]
     ok ridge_regression           mae=0.6928  rmse=0.9948  r2=0.9826  [###################-]
     ok random_forest              mae=0.1348  rmse=0.4762  r2=0.9960  [###################-]
     ok ridge_regression           mae=1.6774  rmse=2.5127  r2=0.8901  [#################---]
     ok lightgbm                   mae=0.1650  rmse=0.4695  r2=0.9961  [###################-]
  > imputador: knn_7
     ok lightgbm                   acc=0.838  mf1=0.725  wf1=0.860  [#################---]
  > imputador: knn_7
     ok random_forest              mae=0.7564  rmse=1.6298  r2=0.9538  [###################-]
     ok ridge_regression           mae=0.6830  rmse=0.9825  r2=0.9830  [###################-]
     ok random_forest              mae=0.1286  rmse=0.4645  r2=0.9962  [###################-]
     ok lightgbm                   mae=0.8721  rmse=1.5435  r2=0.9585  [###################-]
  > imputador: iterative
     ok ridge_regression           mae=1.0651  rmse=1.6087  r2=0.9550  [###################-]
     ok lightgbm                   mae=0.1651  rmse=0.4522  r2=0.9964  [###################-]
  > imputador: iterative
     ok ridge_regression           mae=0.8169  rmse=1.1637  r2=0.9761  [###################-]
     ok random_forest              mae=0.5129  rmse=1.4544  r2=0.9632  [###################-]
     ok lightgbm                   mae=0.5397  rmse=1.2462  r2=0.9730  [###################-]
  > imputador: miceforest
  [miceforest] fallback SimpleImputer (AssertionError)
     ok ridge_regression           mae=1.7906  rmse=2.5624  r2=0.8857  [#################---]
     ok random_forest              mae=0.1201  rmse=0.4940  r2=0.9957  [###################-]
     ok random_forest              mae=0.6220  rmse=1.4339  r2=0.9642  [###################-]
     ok lightgbm                   mae=0.5389  rmse=1.1229  r2=0.9781  [###################-]

  EXPERIMENTO  MCAR  30%  [air_quality_uci]
  --------------------------------------------------
  > imputador: dropna
     ok ridge_regression           mae=1.4497  rmse=1.7787  r2=0.9596  [###################-]
     ok random_forest              mae=2.9946  rmse=3.9627  r2=0.7994  [###############-----]
     ok lightgbm                   mae=6.8571  rmse=9.3897  r2=-0.1262  [--------------------]
  > imputador: simple_mean
     ok ridge_regression           mae=2.0093  rmse=3.0350  r2=0.8397  [################----]
     ok lightgbm                   mae=0.1604  rmse=0.5108  r2=0.9954  [###################-]
  > imputador: miceforest
  [miceforest] fallback SimpleImputer (AssertionError)
     ok ridge_regression           mae=1.1882  rmse=1.8527  r2=0.9395  [##################--]
     ok random_forest              mae=0.8298  rmse=1.9488  r2=0.9339  [##################--]
     ok lightgbm                   mae=0.7483  rmse=1.6623  r2=0.9519  [###################-]
  > imputador: simple_median
     ok ridge_regression           mae=1.9976  rmse=3.0767  r2=0.8353  [################----]
     ok random_forest              mae=0.1765  rmse=0.7372  r2=0.9904  [###################-]
     ok lightgbm                   mae=0.2065  rmse=0.6380  r2=0.9928  [###################-]

  EXPERIMENTO  MCAR  10%  [air_quality_uci]
  --------------------------------------------------
  > imputador: dropna
     ok ridge_regression           mae=0.3714  rmse=0.4278  r2=0.9958  [###################-]
     ok random_forest              mae=0.1402  rmse=0.3203  r2=0.9977  [###################-]
     ok lightgbm                   mae=0.4044  rmse=0.6622  r2=0.9900  [###################-]
  > imputador: simple_mean
     ok ridge_regression           mae=1.3981  rmse=2.0773  r2=0.9240  [##################--]
     ok random_forest              mae=0.8268  rmse=1.9318  r2=0.9351  [##################--]
     ok lightgbm                   mae=0.7403  rmse=1.6538  r2=0.9524  [###################-]
  > imputador: simple_freq
     ok ridge_regression           mae=2.1199  rmse=3.2326  r2=0.8181  [################----]
     ok random_forest              mae=0.2430  rmse=0.8962  r2=0.9859  [###################-]
     ok lightgbm                   mae=0.2568  rmse=0.8030  r2=0.9886  [###################-]
  > imputador: simple_median
     ok ridge_regression           mae=1.3855  rmse=2.0838  r2=0.9235  [##################--]
     ok random_forest              mae=0.8338  rmse=1.9163  r2=0.9361  [##################--]
     ok lightgbm                   mae=0.7407  rmse=1.6590  r2=0.9521  [###################-]
  > imputador: simple_const
     ok ridge_regression           mae=3.7458  rmse=5.3187  r2=0.5077  [##########----------]
     ok random_forest              mae=0.2494  rmse=0.8938  r2=0.9859  [###################-]
     ok lightgbm                   mae=0.2585  rmse=0.8121  r2=0.9884  [###################-]
  > imputador: simple_freq
     ok ridge_regression           mae=1.4266  rmse=2.1447  r2=0.9190  [##################--]
     ok random_forest              mae=0.7838  rmse=1.7982  r2=0.9437  [##################--]
     ok lightgbm                   mae=0.7059  rmse=1.5940  r2=0.9558  [###################-]
  > imputador: knn_3
     ok random_forest              mae=0.2478  rmse=0.9022  r2=0.9857  [###################-]
     ok lightgbm                   mae=0.2534  rmse=0.7863  r2=0.9891  [###################-]
  > imputador: simple_const
     ok ridge_regression           mae=2.7252  rmse=3.8039  r2=0.7451  [##############------]
     ok random_forest              mae=0.2065  rmse=0.8848  r2=0.9862  [###################-]
     ok lightgbm                   mae=0.2385  rmse=0.7984  r2=0.9888  [###################-]
  > imputador: knn_3
     ok ridge_regression           mae=0.8497  rmse=1.2670  r2=0.9717  [###################-]
     ok ridge_regression           mae=2.2172  rmse=3.3225  r2=0.8079  [################----]
     ok random_forest              mae=0.3247  rmse=1.0267  r2=0.9814  [###################-]
     ok lightgbm                   mae=0.3945  rmse=0.8876  r2=0.9861  [###################-]
  > imputador: knn_5
     ok random_forest              mae=1.3113  rmse=2.5919  r2=0.8831  [#################---]
     ok ridge_regression           mae=0.7966  rmse=1.1723  r2=0.9758  [###################-]
     ok lightgbm                   mae=1.3279  rmse=2.3855  r2=0.9010  [##################--]
  > imputador: knn_5
     ok random_forest              mae=0.2793  rmse=0.8501  r2=0.9873  [###################-]
     ok lightgbm                   acc=0.828  mf1=0.705  wf1=0.851  [#################---]
  > imputador: iterative
     ok logistic_regression        acc=0.814  mf1=0.685  wf1=0.840  [################----]
     ok lightgbm                   mae=0.3490  rmse=0.7813  r2=0.9892  [###################-]
  > imputador: knn_7
     ok random_forest              acc=0.826  mf1=0.698  wf1=0.849  [################----]
     ok logistic_regression        acc=0.828  mf1=0.707  wf1=0.851  [#################---]
     ok lightgbm                   acc=0.830  mf1=0.709  wf1=0.852  [#################---]
  > imputador: miceforest
     ok ridge_regression           mae=2.1057  rmse=3.1948  r2=0.8224  [################----]
  [miceforest] fallback SimpleImputer (AssertionError)
     ok logistic_regression        acc=0.777  mf1=0.648  wf1=0.811  [################----]
     ok random_forest              acc=0.830  mf1=0.698  wf1=0.851  [#################---]
     ok lightgbm                   acc=0.827  mf1=0.704  wf1=0.850  [################----]

  EXPERIMENTO  MCAR  25%  [bank_marketing]
  --------------------------------------------------
  > imputador: dropna
     ok logistic_regression        acc=0.684  mf1=0.635  wf1=0.670  [#############-------]
     ok random_forest              acc=0.632  mf1=0.387  wf1=0.489  [#########-----------]
     ok lightgbm                   acc=0.632  mf1=0.552  wf1=0.602  [############--------]
  > imputador: simple_mean
     ok ridge_regression           mae=0.7666  rmse=1.1266  r2=0.9776  [###################-]
     ok logistic_regression        acc=0.811  mf1=0.677  wf1=0.837  [################----]
     ok random_forest              acc=0.824  mf1=0.693  wf1=0.847  [################----]
     ok lightgbm                   acc=0.831  mf1=0.707  wf1=0.853  [#################---]
  > imputador: simple_median
     ok logistic_regression        acc=0.810  mf1=0.676  wf1=0.836  [################----]
     ok random_forest              mae=1.1124  rmse=2.3121  r2=0.9070  [##################--]
     ok random_forest              acc=0.827  mf1=0.698  wf1=0.850  [################----]
     ok random_forest              mae=0.2589  rmse=0.7814  r2=0.9892  [###################-]
     ok lightgbm                   acc=0.828  mf1=0.703  wf1=0.851  [#################---]
  > imputador: simple_freq
     ok logistic_regression        acc=0.804  mf1=0.670  wf1=0.831  [################----]
     ok random_forest              acc=0.836  mf1=0.702  wf1=0.855  [#################---]
     ok lightgbm                   mae=0.3262  rmse=0.6925  r2=0.9916  [###################-]
  > imputador: iterative
     ok lightgbm                   acc=0.829  mf1=0.703  wf1=0.851  [#################---]
  > imputador: simple_const
     ok lightgbm                   mae=1.1526  rmse=2.1403  r2=0.9203  [##################--]
  > imputador: knn_7
     ok logistic_regression        acc=0.794  mf1=0.659  wf1=0.823  [################----]
     ok ridge_regression           mae=0.8704  rmse=1.2042  r2=0.9745  [###################-]
     ok random_forest              acc=0.837  mf1=0.700  wf1=0.855  [#################---]
     ok lightgbm                   acc=0.827  mf1=0.703  wf1=0.850  [################----]
  > imputador: knn_3
     ok random_forest              mae=0.2137  rmse=0.5776  r2=0.9941  [###################-]
     ok lightgbm                   mae=0.2472  rmse=0.6085  r2=0.9935  [###################-]
  > imputador: miceforest
  [miceforest] fallback SimpleImputer (AssertionError)
     ok ridge_regression           mae=1.3981  rmse=2.0773  r2=0.9240  [##################--]
     ok random_forest              mae=0.2430  rmse=0.8962  r2=0.9859  [###################-]
     ok lightgbm                   mae=0.2568  rmse=0.8030  r2=0.9886  [###################-]

  EXPERIMENTO  MCAR  15%  [air_quality_uci]
  --------------------------------------------------
  > imputador: dropna
     ok ridge_regression           mae=0.5119  rmse=0.6107  r2=0.9958  [###################-]
     ok random_forest              mae=0.3522  rmse=0.6251  r2=0.9956  [###################-]

 42%|████▏     | 5/12 [9:11:54<12:52:40, 6622.96s/it]

     ok lightgbm                   mae=0.1763  rmse=0.3991  r2=0.9972  [###################-]

  EXPERIMENTO  MNAR  25%  [air_quality_uci]
  --------------------------------------------------
  > imputador: dropna

[ERRO] key=air_quality_uci seed=42: cannot convert float NaN to integer
[cache] data\air_quality_uci\AirQualityUCI.zip
[cache] data\air_quality_uci\extracted

========================================================================
  REGRESSAO  |  AIR_QUALITY_UCI  |  target: C6H6(GT)
========================================================================
     ok lightgbm                   mae=0.0755  rmse=0.2205  r2=0.9991  [###################-]
  > imputador: simple_const
     ok ridge_regression           mae=0.8346  rmse=1.1559  r2=0.9772  [###################-]
     ok ridge_regression           mae=1.4948  rmse=2.1890  r2=0.9156  [##################--]
     ok random_forest              mae=0.0148  rmse=0.0956  r2=0.9998  [###################-]
     ok random_forest              mae=0.0163  rmse=0.1244  r2=0.9997  [###################-]
     ok lightgbm                   mae=0.0626  rmse=0.3006  r2=0.9985  [###################-]

  EXPERIMENTO  MCAR   1%  [air_quality_uci]
  --------------------------------------------------
  > imputador: dropna
     ok ridge_regression           mae=0.4550  rmse=0.6147  r2=0.9930  [###################-]
     ok lightgbm                   mae=0.0511  rmse=0.1932  r2=0.9993  [###################-]
  > imputador: knn_3
     ok random_forest              mae=0.0641  rmse=0.1396  r2=0.9996  [###################-]
     ok lightgbm                   mae=0.1392  rmse=0.3563  r2=0.9976  [###################-]
  > imputador: simple_mean
     ok ridge_regression           mae=0.8892  rmse=1.3790  r2=0.9675  [###################-]
     ok random_forest              mae=0.0502  rmse=0.3611  r2=0.9978  [###################-]
     ok lightgbm                   mae=0.1294  rmse=0.5480  r2=0.9949  [###################-]
  > imputador: simple_median
     ok ridge_regression           mae=0.8909  rmse=1.3873  r2=0.9671  [###################-]
     ok ridge_regression           mae=0.6933  rmse=0.9702  r2=0.9834  [###################-]
     ok random_forest              mae=0.0493  rmse=0.3165  r2=0.9983  [###################-]
     ok lightgbm                   mae=0.1358  rmse=0.5377  r2=0.9951  [###################-]
  > imputador: simple_freq
     ok ridge_regression           mae=0.9070  rmse=1.4167  r2=0.9657  [###################-]
     ok random_forest              mae=0.0512  rmse=0.3294  r2=0.9981  [###################-]
     ok lightgbm                   mae=0.1350  rmse=0.5317  r2=0.9952  [###################-]
  > imputador: simple_const
     ok ridge_regression           mae=1.3019  rmse=2.0601  r2=0.9275  [##################--]
     ok random_forest              mae=0.0449  rmse=0.3215  r2=0.9982  [###################-]
     ok lightgbm                   mae=0.1106  rmse=0.5066  r2=0.9956  [###################-]
  > imputador: knn_3
     ok random_forest              mae=0.0466  rmse=0.2755  r2=0.9987  [###################-]
     ok lightgbm                   mae=0.0936  rmse=0.3194  r2=0.9982  [###################-]
  > imputador: knn_5
     ok ridge_regression           mae=0.7011  rmse=0.9652  r2=0.9841  [###################-]
     ok logistic_regression        acc=0.815  mf1=0.688  wf1=0.841  [################----]
     ok ridge_regression           mae=0.6776  rmse=0.9633  r2=0.9837  [###################-]
     ok random_forest              mae=0.0319  rmse=0.1475  r2=0.9996  [###################-]
     ok lightgbm                   mae=0.0861  rmse=0.3364  r2=0.9981  [###################-]
  > imputador: knn_5
     ok random_forest              mae=0.0429  rmse=0.2971  r2=0.9984  [###################-]
     ok lightgbm                   mae=0.0900  rmse=0.3338  r2=0.9980  [###################-]
  > imputador: knn_7
     ok ridge_regression           mae=0.6775  rmse=0.9615  r2=0.9842  [###################-]
     ok ridge_regression           mae=0.6650  rmse=0.9495  r2=0.9841  [###################-]
     ok random_forest              mae=0.0323  rmse=0.1380  r2=0.9997  [###################-]
     ok lightgbm                   mae=0.0873  rmse=0.3216  r2=0.9982  [###################-]
  > imputador: knn_7
     ok random_forest              mae=0.0421  rmse=0.2317  r2=0.9991  [###################-]
     ok random_forest              acc=0.824  mf1=0.691  wf1=0.846  [################----]
     ok lightgbm                   mae=0.0838  rmse=0.2751  r2=0.9987  [###################-]
  > imputador: iterative
     ok ridge_regression           mae=0.6598  rmse=0.9523  r2=0.9845  [###################-]
     ok ridge_regression           mae=0.7845  rmse=1.0738  r2=0.9797  [###################-]
     ok random_forest              mae=0.0322  rmse=0.1681  r2=0.9995  [###################-]
     ok random_forest              mae=0.0469  rmse=0.2804  r2=0.9986  [###################-]
     ok lightgbm                   mae=0.0825  rmse=0.2627  r2=0.9988  [###################-]
  > imputador: miceforest
  [miceforest] fallback SimpleImputer (AssertionError)
     ok ridge_regression           mae=0.9234  rmse=1.3315  r2=0.9688  [###################-]
     ok lightgbm                   mae=0.0829  rmse=0.3304  r2=0.9981  [###################-]
  > imputador: iterative
     ok random_forest              mae=0.0157  rmse=0.1053  r2=0.9998  [###################-]
     ok lightgbm                   mae=0.0688  rmse=0.2297  r2=0.9991  [###################-]

  EXPERIMENTO  MNAR   5%  [air_quality_uci]
  --------------------------------------------------
  > imputador: dropna
     ok ridge_regression           mae=0.4559  rmse=0.5550  r2=0.9955  [###################-]
     ok ridge_regression           mae=0.8118  rmse=1.1111  r2=0.9789  [###################-]
     ok random_forest              mae=0.1542  rmse=0.3068  r2=0.9986  [###################-]
     ok lightgbm                   mae=0.4117  rmse=0.9239  r2=0.9874  [###################-]
  > imputador: simple_mean
     ok ridge_regression           mae=1.1259  rmse=1.6340  r2=0.9530  [###################-]
     ok random_forest              mae=0.0226  rmse=0.1192  r2=0.9997  [###################-]
     ok lightgbm                   mae=0.0695  rmse=0.2360  r2=0.9990  [###################-]
  > imputador: simple_median
     ok ridge_regression           mae=1.0794  rmse=1.5811  r2=0.9560  [###################-]
     ok random_forest              mae=0.0294  rmse=0.1492  r2=0.9996  [###################-]
     ok random_forest              mae=0.0336  rmse=0.2440  r2=0.9990  [###################-]
     ok lightgbm                   mae=0.0711  rmse=0.2482  r2=0.9989  [###################-]
  > imputador: simple_freq
     ok ridge_regression           mae=0.9799  rmse=1.4085  r2=0.9651  [###################-]
     ok lightgbm                   mae=0.0854  rmse=0.3000  r2=0.9985  [###################-]
  > imputador: miceforest
  [miceforest] fallback SimpleImputer (AssertionError)
     ok ridge_regression           mae=0.8892  rmse=1.3790  r2=0.9675  [###################-]
     ok random_forest              mae=0.0270  rmse=0.1513  r2=0.9996  [###################-]
     ok lightgbm                   mae=0.0746  rmse=0.2352  r2=0.9990  [###################-]
  > imputador: simple_const
     ok ridge_regression           mae=2.0260  rmse=2.7192  r2=0.8698  [#################---]
     ok random_forest              mae=0.0502  rmse=0.3611  r2=0.9978  [###################-]
     ok lightgbm                   mae=0.1294  rmse=0.5480  r2=0.9949  [###################-]

  EXPERIMENTO  MCAR   5%  [air_quality_uci]
  --------------------------------------------------
  > imputador: dropna
     ok ridge_regression           mae=0.4627  rmse=0.6195  r2=0.9931  [###################-]
     ok random_forest              mae=0.0875  rmse=0.1670  r2=0.9995  [###################-]
     ok lightgbm                   mae=0.3038  rmse=0.6883  r2=0.9915  [###################-]
  > imputador: simple_mean
     ok ridge_regression           mae=1.1275  rmse=1.7160  r2=0.9497  [##################--]
     ok random_forest              mae=0.0229  rmse=0.1387  r2=0.9997  [###################-]
     ok lightgbm                   mae=0.0586  rmse=0.1889  r2=0.9994  [###################-]
  > imputador: knn_3
     ok random_forest              mae=0.1245  rmse=0.5006  r2=0.9957  [###################-]
     ok lightgbm                   mae=0.1701  rmse=0.5031  r2=0.9957  [###################-]
  > imputador: simple_median
     ok ridge_regression           mae=1.1321  rmse=1.7342  r2=0.9486  [##################--]
     ok random_forest              mae=0.1308  rmse=0.5046  r2=0.9956  [###################-]
     ok lightgbm                   mae=0.1707  rmse=0.5011  r2=0.9957  [###################-]
  > imputador: simple_freq
     ok ridge_regression           mae=1.1711  rmse=1.7879  r2=0.9454  [##################--]
     ok random_forest              mae=0.1399  rmse=0.5492  r2=0.9948  [###################-]
     ok lightgbm                   mae=0.1654  rmse=0.5051  r2=0.9956  [###################-]
  > imputador: simple_const
     ok ridge_regression           mae=2.2584  rmse=3.2120  r2=0.8237  [################----]
     ok ridge_regression           mae=0.6746  rmse=0.9578  r2=0.9838  [###################-]
     ok random_forest              mae=0.0988  rmse=0.4680  r2=0.9963  [###################-]
     ok lightgbm                   mae=0.1631  rmse=0.5199  r2=0.9954  [###################-]
  > imputador: knn_3
     ok random_forest              mae=0.0830  rmse=0.3575  r2=0.9977  [###################-]
     ok ridge_regression           mae=0.7670  rmse=1.0858  r2=0.9799  [###################-]
     ok lightgbm                   mae=0.1181  rmse=0.3708  r2=0.9976  [###################-]
  > imputador: knn_5
     ok random_forest              mae=0.1552  rmse=0.6090  r2=0.9937  [###################-]
     ok ridge_regression           mae=0.6423  rmse=0.9284  r2=0.9848  [###################-]
     ok lightgbm                   mae=0.2260  rmse=0.6397  r2=0.9930  [###################-]
  > imputador: knn_5
     ok random_forest              mae=0.0814  rmse=0.3594  r2=0.9977  [###################-]
     ok ridge_regression           mae=0.7402  rmse=1.0375  r2=0.9816  [###################-]
     ok lightgbm                   mae=0.1222  rmse=0.3802  r2=0.9975  [###################-]
  > imputador: knn_7
     ok random_forest              mae=0.1394  rmse=0.5287  r2=0.9952  [###################-]
     ok random_forest              acc=0.817  mf1=0.689  wf1=0.842  [################----]
     ok ridge_regression           mae=0.6309  rmse=0.9183  r2=0.9851  [###################-]
     ok lightgbm                   mae=0.1980  rmse=0.5719  r2=0.9944  [###################-]
  > imputador: knn_7
     ok random_forest              mae=0.0763  rmse=0.3316  r2=0.9981  [###################-]
     ok ridge_regression           mae=0.7216  rmse=1.0228  r2=0.9821  [###################-]
     ok lightgbm                   mae=0.1182  rmse=0.3579  r2=0.9977  [###################-]
  > imputador: iterative
     ok ridge_regression           mae=0.7951  rmse=1.0962  r2=0.9788  [###################-]
     ok random_forest              mae=0.1309  rmse=0.5014  r2=0.9957  [###################-]
     ok random_forest              mae=0.0626  rmse=0.2518  r2=0.9989  [###################-]
     ok lightgbm                   mae=0.1001  rmse=0.3057  r2=0.9984  [###################-]
  > imputador: miceforest
  [miceforest] fallback SimpleImputer (AssertionError)
     ok ridge_regression           mae=1.1259  rmse=1.6340  r2=0.9530  [###################-]
     ok lightgbm                   mae=0.1906  rmse=0.5395  r2=0.9950  [###################-]
  > imputador: iterative
     ok random_forest              mae=0.0226  rmse=0.1192  r2=0.9997  [###################-]
     ok lightgbm                   mae=0.0695  rmse=0.2360  r2=0.9990  [###################-]

  EXPERIMENTO  MNAR  10%  [air_quality_uci]
  --------------------------------------------------
  > imputador: dropna
     ok ridge_regression           mae=0.8357  rmse=1.1428  r2=0.9777  [###################-]
     ok ridge_regression           mae=0.4976  rmse=0.5795  r2=0.9960  [###################-]
     ok random_forest              mae=0.1135  rmse=0.2094  r2=0.9995  [###################-]
     ok lightgbm                   mae=0.3346  rmse=0.5614  r2=0.9963  [###################-]
  > imputador: simple_mean
     ok ridge_regression           mae=1.2989  rmse=1.7937  r2=0.9433  [##################--]
     ok random_forest              mae=0.0488  rmse=0.1642  r2=0.9995  [###################-]
     ok lightgbm                   mae=0.0826  rmse=0.2181  r2=0.9992  [###################-]
  > imputador: simple_median
     ok ridge_regression           mae=1.2452  rmse=1.7315  r2=0.9472  [##################--]
     ok random_forest              mae=0.1169  rmse=0.3820  r2=0.9975  [###################-]
     ok random_forest              mae=0.0528  rmse=0.1946  r2=0.9993  [###################-]
     ok lightgbm                   mae=0.0901  rmse=0.2443  r2=0.9989  [###################-]
  > imputador: simple_freq
     ok ridge_regression           mae=1.0029  rmse=1.3803  r2=0.9664  [###################-]
     ok lightgbm                   mae=0.1582  rmse=0.4553  r2=0.9965  [###################-]
  > imputador: miceforest
  [miceforest] fallback SimpleImputer (AssertionError)
     ok ridge_regression           mae=1.1275  rmse=1.7160  r2=0.9497  [##################--]
     ok random_forest              mae=0.0530  rmse=0.1891  r2=0.9994  [###################-]
     ok lightgbm                   mae=0.0909  rmse=0.2392  r2=0.9990  [###################-]
  > imputador: simple_const
     ok random_forest              mae=0.1245  rmse=0.5006  r2=0.9957  [###################-]
     ok ridge_regression           mae=2.2619  rmse=2.9547  r2=0.8462  [################----]
     ok lightgbm                   mae=0.1701  rmse=0.5031  r2=0.9957  [###################-]

  EXPERIMENTO  MCAR  10%  [air_quality_uci]
  --------------------------------------------------
  > imputador: dropna
     ok ridge_regression           mae=0.3815  rmse=0.4622  r2=0.9947  [###################-]
     ok random_forest              mae=0.1341  rmse=0.2461  r2=0.9985  [###################-]
     ok lightgbm                   mae=0.6464  rmse=1.1374  r2=0.9680  [###################-]
  > imputador: simple_mean
     ok ridge_regression           mae=1.3431  rmse=1.9298  r2=0.9364  [##################--]
     ok random_forest              mae=0.0488  rmse=0.1620  r2=0.9995  [###################-]
     ok lightgbm                   mae=0.0826  rmse=0.2194  r2=0.9992  [###################-]
  > imputador: knn_3
     ok random_forest              mae=0.2377  rmse=0.7326  r2=0.9908  [###################-]
     ok lightgbm                   mae=0.2638  rmse=0.6626  r2=0.9925  [###################-]
  > imputador: simple_median
     ok ridge_regression           mae=1.3348  rmse=1.9430  r2=0.9355  [##################--]
     ok lightgbm                   acc=0.826  mf1=0.699  wf1=0.848  [################----]
  > imputador: iterative
     ok random_forest              mae=0.2504  rmse=0.7439  r2=0.9905  [###################-]
     ok lightgbm                   mae=0.2624  rmse=0.6826  r2=0.9920  [###################-]
  > imputador: simple_freq
     ok ridge_regression           mae=1.3806  rmse=2.0096  r2=0.9310  [##################--]
     ok logistic_regression        acc=0.808  mf1=0.674  wf1=0.834  [################----]
     ok random_forest              mae=0.2470  rmse=0.7581  r2=0.9902  [###################-]
     ok lightgbm                   mae=0.2604  rmse=0.6723  r2=0.9923  [###################-]
  > imputador: simple_const
     ok ridge_regression           mae=2.7205  rmse=3.7501  r2=0.7597  [###############-----]
     ok ridge_regression           mae=0.8881  rmse=1.2884  r2=0.9708  [###################-]
     ok random_forest              acc=0.830  mf1=0.696  wf1=0.850  [#################---]
     ok random_forest              mae=0.1883  rmse=0.7041  r2=0.9915  [###################-]
     ok lightgbm                   mae=0.2703  rmse=0.7450  r2=0.9905  [###################-]
  > imputador: knn_3
     ok lightgbm                   acc=0.829  mf1=0.705  wf1=0.852  [#################---]
  > imputador: miceforest
  [miceforest] fallback SimpleImputer (AssertionError)
     ok logistic_regression        acc=0.770  mf1=0.639  wf1=0.806  [################----]
     ok random_forest              acc=0.838  mf1=0.702  wf1=0.856  [#################---]
     ok lightgbm                   acc=0.829  mf1=0.704  wf1=0.851  [#################---]

  EXPERIMENTO  MCAR  30%  [bank_marketing]
  --------------------------------------------------
  > imputador: dropna
     ok logistic_regression        acc=0.714  mf1=0.417  wf1=0.833  [################----]
     ok random_forest              acc=0.714  mf1=0.417  wf1=0.833  [################----]
     ok lightgbm                   acc=1.000  mf1=1.000  wf1=1.000  [####################]
  > imputador: simple_mean
     ok logistic_regression        acc=0.798  mf1=0.666  wf1=0.827  [################----]
     ok random_forest              mae=0.2024  rmse=0.5324  r2=0.9950  [###################-]
     ok ridge_regression           mae=0.9132  rmse=1.2901  r2=0.9716  [###################-]
     ok random_forest              acc=0.808  mf1=0.673  wf1=0.834  [################----]
     ok lightgbm                   acc=0.820  mf1=0.692  wf1=0.844  [################----]
  > imputador: simple_median
     ok lightgbm                   mae=0.2277  rmse=0.4977  r2=0.9956  [###################-]
  > imputador: knn_5
     ok logistic_regression        acc=0.800  mf1=0.666  wf1=0.828  [################----]
     ok random_forest              acc=0.812  mf1=0.678  wf1=0.837  [################----]
     ok lightgbm                   acc=0.817  mf1=0.687  wf1=0.841  [################----]
  > imputador: simple_freq
     ok random_forest              mae=0.3333  rmse=0.9410  r2=0.9849  [###################-]
     ok logistic_regression        acc=0.793  mf1=0.658  wf1=0.823  [################----]
     ok random_forest              acc=0.829  mf1=0.691  wf1=0.849  [################----]
     ok ridge_regression           mae=0.8536  rmse=1.2450  r2=0.9727  [###################-]
     ok lightgbm                   acc=0.816  mf1=0.690  wf1=0.841  [################----]
  > imputador: simple_const
     ok lightgbm                   mae=0.4209  rmse=0.8821  r2=0.9867  [###################-]
  > imputador: knn_5
     ok logistic_regression        acc=0.780  mf1=0.645  wf1=0.812  [################----]
     ok random_forest              acc=0.833  mf1=0.694  wf1=0.852  [#################---]
     ok lightgbm                   acc=0.816  mf1=0.688  wf1=0.841  [################----]
  > imputador: knn_3
     ok random_forest              mae=0.1875  rmse=0.4935  r2=0.9957  [###################-]
     ok ridge_regression           mae=0.8552  rmse=1.2001  r2=0.9754  [###################-]
     ok lightgbm                   mae=0.2172  rmse=0.4400  r2=0.9966  [###################-]
  > imputador: knn_7
     ok random_forest              mae=0.2999  rmse=0.8419  r2=0.9879  [###################-]
     ok ridge_regression           mae=0.8352  rmse=1.2197  r2=0.9738  [###################-]
     ok lightgbm                   mae=0.3950  rmse=0.8405  r2=0.9879  [###################-]
  > imputador: knn_7
     ok random_forest              mae=0.1745  rmse=0.4713  r2=0.9961  [###################-]
     ok lightgbm                   acc=0.825  mf1=0.703  wf1=0.849  [################----]
  > imputador: knn_5

 50%|█████     | 6/12 [9:29:05<9:29:05, 5690.99s/it]

     ok random_forest              mae=0.2764  rmse=0.6093  r2=0.9935  [###################-]
     ok lightgbm                   mae=0.2724  rmse=0.5580  r2=0.9945  [###################-]
[cache] data\communities_crime\communities.data

========================================================================
  REGRESSAO  |  COMMUNITIES_CRIME  |  target: ViolentCrimesPerPop
========================================================================
     ok random_forest              mae=0.0598  rmse=0.5708  r2=0.9944  [###################-]
     ok ridge_regression           mae=0.0941  rmse=0.1343  r2=0.6232  [############--------]
     ok lightgbm                   mae=0.1245  rmse=0.6963  r2=0.9917  [###################-]
  > imputador: simple_freq
     ok ridge_regression           mae=0.9048  rmse=1.4814  r2=0.9625  [###################-]
     ok random_forest              mae=0.0626  rmse=0.5667  r2=0.9945  [###################-]
     ok lightgbm                   mae=0.1326  rmse=0.7020  r2=0.9916  [###################-]
  > imputador: simple_const
     ok ridge_regression           mae=1.2587  rmse=2.1215  r2=0.9231  [##################--]
     ok random_forest              mae=0.0931  rmse=0.1365  r2=0.6111  [############--------]
     ok lightgbm                   mae=0.0888  rmse=0.1353  r2=0.6178  [############--------]

  EXPERIMENTO  MCAR   1%  [communities_crime]
  --------------------------------------------------
  > imputador: dropna
     ok ridge_regression           mae=0.2356  rmse=0.3533  r2=-0.7142  [--------------------]
     ok random_forest              mae=0.1122  rmse=0.1481  r2=0.6986  [#############-------]
     ok lightgbm                   mae=0.1113  rmse=0.1558  r2=0.6664  [#############-------]
  > imputador: simple_mean
     ok ridge_regression           mae=0.0958  rmse=0.1398  r2=0.5917  [###########---------]
     ok random_forest              mae=0.0471  rmse=0.5024  r2=0.9957  [###################-]
     ok lightgbm                   mae=0.1116  rmse=0.6752  r2=0.9922  [###################-]
  > imputador: knn_3
     ok lightgbm                   acc=0.813  mf1=0.682  wf1=0.838  [################----]
  > imputador: knn_5
     ok random_forest              mae=0.0940  rmse=0.1383  r2=0.6007  [############--------]
     ok lightgbm                   mae=0.0897  rmse=0.1362  r2=0.6130  [############--------]
  > imputador: simple_median
     ok ridge_regression           mae=0.0955  rmse=0.1397  r2=0.5925  [###########---------]
     ok ridge_regression           mae=0.6585  rmse=0.9354  r2=0.9850  [###################-]
     ok random_forest              mae=0.0940  rmse=0.1383  r2=0.6007  [############--------]
     ok lightgbm                   mae=0.0905  rmse=0.1379  r2=0.6028  [############--------]
  > imputador: simple_freq
     ok ridge_regression           mae=0.0957  rmse=0.1397  r2=0.5923  [###########---------]
     ok random_forest              mae=0.0948  rmse=0.1400  r2=0.5907  [###########---------]
     ok random_forest              mae=0.0430  rmse=0.3015  r2=0.9984  [###################-]
     ok lightgbm                   mae=0.0892  rmse=0.1364  r2=0.6118  [############--------]
  > imputador: simple_const
     ok ridge_regression           mae=0.0982  rmse=0.1396  r2=0.5930  [###########---------]
     ok lightgbm                   mae=0.0896  rmse=0.3941  r2=0.9973  [###################-]
  > imputador: knn_5
     ok random_forest              mae=0.0928  rmse=0.1389  r2=0.5973  [###########---------]
     ok lightgbm                   mae=0.0920  rmse=0.1381  r2=0.6020  [############--------]
  > imputador: knn_3
     ok ridge_regression           mae=0.0928  rmse=0.1327  r2=0.6321  [############--------]
     ok ridge_regression           mae=0.6358  rmse=0.9260  r2=0.9853  [###################-]
     ok random_forest              mae=0.0944  rmse=0.1388  r2=0.5978  [###########---------]
     ok lightgbm                   mae=0.0891  rmse=0.1355  r2=0.6166  [############--------]
  > imputador: knn_5
     ok random_forest              mae=0.0376  rmse=0.2637  r2=0.9988  [###################-]
     ok ridge_regression           mae=0.0927  rmse=0.1331  r2=0.6302  [############--------]
     ok lightgbm                   mae=0.0840  rmse=0.3508  r2=0.9979  [###################-]
  > imputador: knn_7
     ok random_forest              mae=0.0935  rmse=0.1361  r2=0.6134  [############--------]
     ok lightgbm                   mae=0.0897  rmse=0.1363  r2=0.6120  [############--------]
  > imputador: knn_7
     ok ridge_regression           mae=0.6296  rmse=0.9329  r2=0.9851  [###################-]
     ok ridge_regression           mae=0.0923  rmse=0.1335  r2=0.6282  [############--------]
     ok random_forest              mae=0.0390  rmse=0.2583  r2=0.9989  [###################-]
     ok random_forest              mae=0.0928  rmse=0.1356  r2=0.6162  [############--------]
     ok lightgbm                   mae=0.0883  rmse=0.1326  r2=0.6330  [############--------]
  > imputador: iterative
     ok lightgbm                   mae=0.0831  rmse=0.3504  r2=0.9979  [###################-]
  > imputador: iterative
     ok logistic_regression        acc=0.819  mf1=0.691  wf1=0.843  [################----]
     ok ridge_regression           mae=0.8158  rmse=1.1158  r2=0.9787  [###################-]
     ok random_forest              mae=0.0316  rmse=0.2270  r2=0.9991  [###################-]
     ok lightgbm                   mae=0.0820  rmse=0.3532  r2=0.9979  [###################-]
  > imputador: miceforest
  [miceforest] fallback SimpleImputer (AssertionError)
     ok ridge_regression           mae=0.8761  rmse=1.4210  r2=0.9655  [###################-]
     ok random_forest              mae=0.0653  rmse=0.5747  r2=0.9944  [###################-]
     ok lightgbm                   mae=0.1245  rmse=0.7054  r2=0.9915  [###################-]

  EXPERIMENTO  MAR   5%  [air_quality_uci]
  --------------------------------------------------
  > imputador: dropna
     ok ridge_regression           mae=0.5136  rmse=0.6723  r2=0.9941  [###################-]
     ok random_forest              mae=0.1259  rmse=0.3521  r2=0.9984  [###################-]
     ok lightgbm                   mae=0.2608  rmse=0.5242  r2=0.9964  [###################-]
  > imputador: simple_mean
     ok ridge_regression           mae=1.1772  rmse=1.6747  r2=0.9521  [###################-]
     ok random_forest              mae=0.1085  rmse=0.4633  r2=0.9963  [###################-]
     ok lightgbm                   mae=0.1598  rmse=0.5447  r2=0.9949  [###################-]
  > imputador: simple_median
     ok ridge_regression           mae=1.1694  rmse=1.6954  r2=0.9509  [###################-]
     ok random_forest              mae=0.1091  rmse=0.4785  r2=0.9961  [###################-]
     ok lightgbm                   mae=0.1661  rmse=0.5366  r2=0.9951  [###################-]
  > imputador: simple_freq
     ok ridge_regression           mae=1.2172  rmse=1.7819  r2=0.9457  [##################--]
     ok random_forest              mae=0.1013  rmse=0.4650  r2=0.9963  [###################-]
     ok lightgbm                   mae=0.1606  rmse=0.5405  r2=0.9950  [###################-]
  > imputador: simple_const
     ok ridge_regression           mae=2.1187  rmse=2.9719  r2=0.8491  [################----]
     ok random_forest              mae=0.0924  rmse=0.4312  r2=0.9968  [###################-]
     ok lightgbm                   mae=0.1626  rmse=0.5560  r2=0.9947  [###################-]
  > imputador: knn_3
     ok random_forest              acc=0.815  mf1=0.687  wf1=0.840  [################----]
     ok ridge_regression           mae=0.7361  rmse=1.0650  r2=0.9806  [###################-]
     ok random_forest              mae=0.1690  rmse=0.6038  r2=0.9938  [###################-]
     ok lightgbm                   mae=0.2189  rmse=0.6584  r2=0.9926  [###################-]
  > imputador: knn_5
     ok ridge_regression           mae=0.7307  rmse=1.0525  r2=0.9811  [###################-]
     ok logistic_regression        acc=0.791  mf1=0.660  wf1=0.822  [################----]
     ok random_forest              mae=0.1522  rmse=0.5985  r2=0.9939  [###################-]
     ok lightgbm                   acc=0.833  mf1=0.714  wf1=0.856  [#################---]
  > imputador: iterative
     ok lightgbm                   mae=0.2011  rmse=0.6291  r2=0.9932  [###################-]
  > imputador: knn_7
     ok logistic_regression        acc=0.823  mf1=0.695  wf1=0.847  [################----]
     ok ridge_regression           mae=0.7254  rmse=1.0441  r2=0.9814  [###################-]
     ok random_forest              acc=0.824  mf1=0.694  wf1=0.847  [################----]
     ok ridge_regression           mae=0.0937  rmse=0.1326  r2=0.6330  [############--------]
     ok lightgbm                   acc=0.835  mf1=0.715  wf1=0.857  [#################---]
  > imputador: miceforest
  [miceforest] fallback SimpleImputer (AssertionError)
     ok random_forest              mae=0.1652  rmse=0.6514  r2=0.9927  [###################-]
     ok logistic_regression        acc=0.789  mf1=0.660  wf1=0.821  [################----]
     ok lightgbm                   mae=0.1952  rmse=0.6215  r2=0.9934  [###################-]
  > imputador: iterative
     ok random_forest              acc=0.846  mf1=0.714  wf1=0.863  [#################---]
     ok lightgbm                   acc=0.830  mf1=0.709  wf1=0.853  [#################---]

  EXPERIMENTO  MCAR  25%  [bank_marketing]
  --------------------------------------------------
  > imputador: dropna
     ok logistic_regression        acc=0.941  mf1=0.924  wf1=0.943  [##################--]
     ok random_forest              acc=0.824  mf1=0.773  wf1=0.830  [################----]
     ok lightgbm                   acc=0.824  mf1=0.773  wf1=0.830  [################----]
  > imputador: simple_mean
     ok logistic_regression        acc=0.818  mf1=0.688  wf1=0.843  [################----]
     ok ridge_regression           mae=0.8177  rmse=1.1423  r2=0.9777  [###################-]
     ok random_forest              acc=0.818  mf1=0.686  wf1=0.842  [################----]
     ok random_forest              mae=0.1308  rmse=0.4738  r2=0.9962  [###################-]
     ok lightgbm                   acc=0.826  mf1=0.702  wf1=0.849  [################----]
  > imputador: simple_median
     ok logistic_regression        acc=0.817  mf1=0.684  wf1=0.841  [################----]
     ok lightgbm                   mae=0.1733  rmse=0.5020  r2=0.9957  [###################-]
  > imputador: miceforest
  [miceforest] fallback SimpleImputer (AssertionError)
     ok ridge_regression           mae=1.1772  rmse=1.6747  r2=0.9521  [###################-]
     ok random_forest              mae=0.1085  rmse=0.4633  r2=0.9963  [###################-]
     ok lightgbm                   mae=0.1598  rmse=0.5447  r2=0.9949  [###################-]

  EXPERIMENTO  MAR  10%  [air_quality_uci]
  --------------------------------------------------
  > imputador: dropna
     ok ridge_regression           mae=0.1443  rmse=0.1824  r2=0.9767  [###################-]
     ok random_forest              mae=0.1385  rmse=0.1723  r2=0.9792  [###################-]
     ok random_forest              acc=0.821  mf1=0.690  wf1=0.844  [################----]
     ok lightgbm                   mae=1.3200  rmse=1.6115  r2=-0.8200  [--------------------]
  > imputador: simple_mean
     ok ridge_regression           mae=1.3430  rmse=1.9917  r2=0.9322  [##################--]
     ok random_forest              acc=0.811  mf1=0.673  wf1=0.836  [################----]
     ok lightgbm                   acc=0.828  mf1=0.706  wf1=0.851  [#################---]
  > imputador: simple_freq
     ok random_forest              mae=0.1978  rmse=0.5991  r2=0.9939  [###################-]
     ok lightgbm                   mae=0.2288  rmse=0.5925  r2=0.9940  [###################-]
  > imputador: simple_median
     ok ridge_regression           mae=1.3847  rmse=2.0423  r2=0.9287  [##################--]
     ok logistic_regression        acc=0.815  mf1=0.682  wf1=0.840  [################----]
     ok random_forest              mae=0.1812  rmse=0.5683  r2=0.9945  [###################-]
     ok lightgbm                   mae=0.2105  rmse=0.5461  r2=0.9949  [###################-]
  > imputador: simple_freq
     ok ridge_regression           mae=1.4515  rmse=2.1246  r2=0.9229  [##################--]
     ok random_forest              acc=0.823  mf1=0.690  wf1=0.845  [################----]
     ok lightgbm                   acc=0.828  mf1=0.704  wf1=0.851  [#################---]
  > imputador: simple_const
     ok random_forest              mae=0.1807  rmse=0.5617  r2=0.9946  [###################-]
     ok lightgbm                   mae=0.2116  rmse=0.5469  r2=0.9949  [###################-]
  > imputador: simple_const
     ok ridge_regression           mae=2.6425  rmse=3.5435  r2=0.7854  [###############-----]
     ok logistic_regression        acc=0.801  mf1=0.668  wf1=0.829  [################----]
     ok random_forest              mae=0.1693  rmse=0.6056  r2=0.9937  [###################-]
     ok lightgbm                   mae=0.2166  rmse=0.5960  r2=0.9939  [###################-]
  > imputador: knn_3
     ok random_forest              acc=0.841  mf1=0.704  wf1=0.858  [#################---]
     ok lightgbm                   acc=0.827  mf1=0.703  wf1=0.850  [#################---]
  > imputador: knn_3
     ok ridge_regression           mae=0.8688  rmse=1.3647  r2=0.9682  [###################-]
     ok random_forest              mae=0.0933  rmse=0.1379  r2=0.6032  [############--------]
     ok random_forest              mae=0.2657  rmse=1.0091  r2=0.9826  [###################-]
     ok lightgbm                   mae=0.2963  rmse=0.8524  r2=0.9876  [###################-]
  > imputador: knn_5
     ok ridge_regression           mae=0.8407  rmse=1.3244  r2=0.9700  [###################-]
     ok lightgbm                   acc=0.811  mf1=0.682  wf1=0.837  [################----]
  > imputador: knn_7
     ok random_forest              mae=0.2552  rmse=1.0572  r2=0.9809  [###################-]
     ok lightgbm                   mae=0.3016  rmse=0.8735  r2=0.9870  [###################-]
  > imputador: knn_7
     ok ridge_regression           mae=0.8216  rmse=1.2919  r2=0.9715  [###################-]
     ok lightgbm                   mae=0.0915  rmse=0.1374  r2=0.6058  [############--------]
  > imputador: miceforest
[miceforest] 122 colunas → usando top-50 por variância
  [miceforest] fallback SimpleImputer (AssertionError)
     ok ridge_regression           mae=0.0958  rmse=0.1398  r2=0.5917  [###########---------]
     ok random_forest              mae=0.0940  rmse=0.1383  r2=0.6007  [############--------]
     ok lightgbm                   mae=0.0897  rmse=0.1362  r2=0.6130  [############--------]

  EXPERIMENTO  MCAR   5%  [communities_crime]
  --------------------------------------------------
  > imputador: dropna
  > imputador: simple_mean
     ok ridge_regression           mae=0.0963  rmse=0.1363  r2=0.6122  [############--------]
     ok random_forest              mae=0.2470  rmse=0.9297  r2=0.9852  [###################-]
     ok random_forest              mae=0.0956  rmse=0.1387  r2=0.5986  [###########---------]
     ok lightgbm                   mae=0.0899  rmse=0.1359  r2=0.6147  [############--------]
  > imputador: simple_median
     ok ridge_regression           mae=0.0964  rmse=0.1373  r2=0.6062  [############--------]
     ok lightgbm                   mae=0.2854  rmse=0.8205  r2=0.9885  [###################-]
  > imputador: iterative
     ok random_forest              mae=0.0949  rmse=0.1388  r2=0.5979  [###########---------]
     ok ridge_regression           mae=0.8653  rmse=1.1841  r2=0.9760  [###################-]
     ok lightgbm                   mae=0.0890  rmse=0.1351  r2=0.6188  [############--------]
  > imputador: simple_freq
     ok ridge_regression           mae=0.0964  rmse=0.1374  r2=0.6061  [############--------]
     ok random_forest              mae=0.1987  rmse=0.5957  r2=0.9939  [###################-]
     ok random_forest              mae=0.0968  rmse=0.1405  r2=0.5876  [###########---------]
     ok lightgbm                   mae=0.0923  rmse=0.1369  r2=0.6088  [############--------]
  > imputador: simple_const
     ok ridge_regression           mae=0.0997  rmse=0.1408  r2=0.5863  [###########---------]
     ok lightgbm                   mae=0.2238  rmse=0.5477  r2=0.9949  [###################-]
  > imputador: miceforest
  [miceforest] fallback SimpleImputer (AssertionError)
     ok ridge_regression           mae=1.3430  rmse=1.9917  r2=0.9322  [##################--]
     ok random_forest              mae=0.1978  rmse=0.5991  r2=0.9939  [###################-]
     ok lightgbm                   mae=0.2288  rmse=0.5925  r2=0.9940  [###################-]

  EXPERIMENTO  MAR  15%  [air_quality_uci]
  --------------------------------------------------
  > imputador: dropna
     ok ridge_regression           mae=0.7154  rmse=0.9310  r2=0.9937  [###################-]
     ok random_forest              mae=0.2603  rmse=0.4793  r2=0.9983  [###################-]
     ok lightgbm                   mae=0.8851  rmse=1.4599  r2=0.9846  [###################-]
  > imputador: simple_mean
     ok ridge_regression           mae=1.6116  rmse=2.2750  r2=0.9115  [##################--]
     ok random_forest              mae=0.0952  rmse=0.1398  r2=0.5921  [###########---------]
     ok lightgbm                   mae=0.0915  rmse=0.1385  r2=0.5993  [###########---------]
  > imputador: knn_3
     ok random_forest              mae=0.1809  rmse=0.4983  r2=0.9958  [###################-]
     ok lightgbm                   mae=0.2389  rmse=0.5199  r2=0.9954  [###################-]
  > imputador: simple_median
     ok ridge_regression           mae=1.6057  rmse=2.2736  r2=0.9117  [##################--]
     ok ridge_regression           mae=0.0948  rmse=0.1331  r2=0.6304  [############--------]
     ok random_forest              mae=0.1907  rmse=0.5045  r2=0.9956  [###################-]
     ok lightgbm                   mae=0.2360  rmse=0.5109  r2=0.9955  [###################-]
  > imputador: simple_freq
     ok ridge_regression           mae=1.6927  rmse=2.3437  r2=0.9061  [##################--]
     ok random_forest              mae=0.1763  rmse=0.4873  r2=0.9959  [###################-]
     ok lightgbm                   mae=0.2350  rmse=0.5147  r2=0.9955  [###################-]
  > imputador: simple_const
     ok ridge_regression           mae=2.4877  rmse=3.4705  r2=0.7942  [###############-----]
     ok random_forest              mae=0.0925  rmse=0.1354  r2=0.6173  [############--------]
     ok lightgbm                   mae=0.0923  rmse=0.1377  r2=0.6044  [############--------]
  > imputador: knn_5
     ok random_forest              mae=0.1586  rmse=0.4452  r2=0.9966  [###################-]
     ok lightgbm                   mae=0.2281  rmse=0.5149  r2=0.9955  [###################-]
  > imputador: knn_3
     ok ridge_regression           mae=0.0947  rmse=0.1336  r2=0.6273  [############--------]
     ok random_forest              mae=0.0950  rmse=0.1389  r2=0.5970  [###########---------]
     ok ridge_regression           mae=0.9699  rmse=1.3851  r2=0.9672  [###################-]
     ok lightgbm                   mae=0.0931  rmse=0.1394  r2=0.5945  [###########---------]
  > imputador: knn_7
     ok ridge_regression           mae=0.0938  rmse=0.1346  r2=0.6219  [############--------]
     ok random_forest              mae=0.3412  rmse=0.8606  r2=0.9873  [###################-]
     ok random_forest              mae=0.0951  rmse=0.1383  r2=0.6009  [############--------]
     ok lightgbm                   mae=0.0912  rmse=0.1367  r2=0.6097  [############--------]
  > imputador: iterative

 58%|█████▊    | 7/12 [10:13:06<7:17:55, 5255.14s/it]

  > imputador: dropna

[ERRO] key=air_quality_uci seed=456: cannot convert float NaN to integer
[cache] data\communities_crime\communities.data

========================================================================
  REGRESSAO  |  COMMUNITIES_CRIME  |  target: ViolentCrimesPerPop
========================================================================
     ok ridge_regression           mae=0.0999  rmse=0.1407  r2=0.6269  [############--------]
     ok logistic_regression        acc=0.834  mf1=0.713  wf1=0.856  [#################---]
     ok random_forest              mae=0.0956  rmse=0.1376  r2=0.6432  [############--------]
     ok lightgbm                   mae=0.0936  rmse=0.1378  r2=0.6422  [############--------]

  EXPERIMENTO  MCAR   1%  [communities_crime]
  --------------------------------------------------
  > imputador: dropna
     ok ridge_regression           mae=0.9683  rmse=3.5767  r2=-194.2071  [--------------------]
     ok random_forest              mae=0.1178  rmse=0.1627  r2=0.5960  [###########---------]
     ok lightgbm                   mae=0.1588  rmse=0.1908  r2=0.4445  [########------------]
  > imputador: simple_mean
     ok random_forest              acc=0.849  mf1=0.737  wf1=0.869  [#################---]
     ok ridge_regression           mae=0.1014  rmse=0.1426  r2=0.6171  [############--------]
     ok lightgbm                   mae=0.0925  rmse=0.1399  r2=0.5914  [###########---------]
  > imputador: miceforest
[miceforest] 122 colunas → usando top-50 por variância
  [miceforest] fallback SimpleImputer (AssertionError)
     ok ridge_regression           mae=0.0963  rmse=0.1363  r2=0.6122  [############--------]
     ok lightgbm                   acc=0.858  mf1=0.751  wf1=0.876  [#################---]
  > imputador: simple_median
     ok logistic_regression        acc=0.833  mf1=0.713  wf1=0.855  [#################---]
     ok random_forest              mae=0.0970  rmse=0.1398  r2=0.6318  [############--------]
     ok lightgbm                   mae=0.0950  rmse=0.1393  r2=0.6343  [############--------]
  > imputador: simple_median
     ok ridge_regression           mae=0.1002  rmse=0.1412  r2=0.6245  [############--------]
     ok random_forest              mae=0.0956  rmse=0.1387  r2=0.5986  [###########---------]
     ok random_forest              acc=0.846  mf1=0.734  wf1=0.866  [#################---]
     ok lightgbm                   mae=0.0899  rmse=0.1359  r2=0.6147  [############--------]

  EXPERIMENTO  MCAR  10%  [communities_crime]
  --------------------------------------------------
  > imputador: dropna
  > imputador: simple_mean
     ok ridge_regression           mae=0.0991  rmse=0.1421  r2=0.5783  [###########---------]
     ok lightgbm                   acc=0.857  mf1=0.749  wf1=0.875  [#################---]
  > imputador: simple_freq
     ok logistic_regression        acc=0.833  mf1=0.713  wf1=0.855  [#################---]
     ok random_forest              mae=0.0946  rmse=0.1383  r2=0.6396  [############--------]
     ok lightgbm                   mae=0.0948  rmse=0.1396  r2=0.6332  [############--------]
  > imputador: simple_freq
     ok ridge_regression           mae=0.0988  rmse=0.1399  r2=0.6316  [############--------]
     ok random_forest              mae=0.0931  rmse=0.1369  r2=0.6085  [############--------]
     ok random_forest              acc=0.844  mf1=0.729  wf1=0.864  [#################---]
     ok lightgbm                   mae=0.0889  rmse=0.1351  r2=0.6187  [############--------]
  > imputador: simple_median
     ok ridge_regression           mae=0.0980  rmse=0.1420  r2=0.5792  [###########---------]
     ok lightgbm                   acc=0.857  mf1=0.748  wf1=0.875  [#################---]
  > imputador: simple_const
     ok logistic_regression        acc=0.833  mf1=0.713  wf1=0.855  [#################---]
     ok random_forest              mae=0.0959  rmse=0.1394  r2=0.6340  [############--------]
     ok lightgbm                   mae=0.0948  rmse=0.1390  r2=0.6358  [############--------]
  > imputador: simple_const
     ok ridge_regression           mae=0.1003  rmse=0.1421  r2=0.6194  [############--------]
     ok random_forest              mae=0.0935  rmse=0.1364  r2=0.6114  [############--------]
     ok lightgbm                   mae=0.0905  rmse=0.1380  r2=0.6023  [############--------]
  > imputador: simple_freq
     ok random_forest              acc=0.838  mf1=0.724  wf1=0.860  [#################---]
     ok ridge_regression           mae=0.0993  rmse=0.1438  r2=0.5680  [###########---------]
     ok lightgbm                   acc=0.859  mf1=0.751  wf1=0.877  [#################---]
  > imputador: knn_3
     ok random_forest              mae=0.0962  rmse=0.1390  r2=0.6363  [############--------]
     ok lightgbm                   mae=0.0953  rmse=0.1390  r2=0.6358  [############--------]
  > imputador: knn_3
     ok random_forest              mae=0.0933  rmse=0.1363  r2=0.6123  [############--------]
     ok lightgbm                   mae=0.0869  rmse=0.1333  r2=0.6291  [############--------]
  > imputador: simple_const
     ok ridge_regression           mae=0.1019  rmse=0.1438  r2=0.5683  [###########---------]
     ok ridge_regression           mae=0.0988  rmse=0.1384  r2=0.6390  [############--------]
     ok random_forest              mae=0.0975  rmse=0.1422  r2=0.5776  [###########---------]
     ok lightgbm                   mae=0.0946  rmse=0.1397  r2=0.5927  [###########---------]
  > imputador: knn_3
     ok random_forest              mae=0.0992  rmse=0.1433  r2=0.6134  [############--------]
     ok logistic_regression        acc=0.832  mf1=0.711  wf1=0.854  [#################---]
     ok lightgbm                   mae=0.0947  rmse=0.1393  r2=0.6347  [############--------]
  > imputador: knn_5
     ok ridge_regression           mae=0.0964  rmse=0.1357  r2=0.6156  [############--------]
     ok ridge_regression           mae=0.0998  rmse=0.1403  r2=0.6291  [############--------]
     ok random_forest              acc=0.846  mf1=0.731  wf1=0.866  [#################---]
     ok random_forest              mae=0.0951  rmse=0.1372  r2=0.6071  [############--------]
     ok random_forest              mae=0.0960  rmse=0.1395  r2=0.6332  [############--------]
     ok lightgbm                   mae=0.0879  rmse=0.1324  r2=0.6340  [############--------]
  > imputador: knn_5
     ok lightgbm                   mae=0.0956  rmse=0.1406  r2=0.6274  [############--------]
  > imputador: knn_7
     ok ridge_regression           mae=0.0997  rmse=0.1407  r2=0.6273  [############--------]
     ok lightgbm                   acc=0.856  mf1=0.748  wf1=0.875  [#################---]
  > imputador: knn_5
     ok ridge_regression           mae=0.0965  rmse=0.1369  r2=0.6086  [############--------]
     ok random_forest              mae=0.0949  rmse=0.1396  r2=0.6330  [############--------]
     ok lightgbm                   mae=0.0952  rmse=0.1422  r2=0.6190  [############--------]
  > imputador: iterative
     ok random_forest              mae=0.0938  rmse=0.1384  r2=0.6003  [############--------]
     ok random_forest              acc=0.820  mf1=0.687  wf1=0.843  [################----]
     ok logistic_regression        acc=0.833  mf1=0.712  wf1=0.855  [#################---]
     ok lightgbm                   mae=0.0908  rmse=0.1378  r2=0.6038  [############--------]
  > imputador: knn_7
     ok random_forest              acc=0.842  mf1=0.728  wf1=0.863  [#################---]
     ok ridge_regression           mae=0.0964  rmse=0.1366  r2=0.6104  [############--------]
     ok lightgbm                   acc=0.858  mf1=0.751  wf1=0.876  [#################---]
  > imputador: knn_7
     ok random_forest              mae=0.0938  rmse=0.1362  r2=0.6126  [############--------]
     ok logistic_regression        acc=0.833  mf1=0.712  wf1=0.855  [#################---]
     ok lightgbm                   mae=0.0913  rmse=0.1358  r2=0.6150  [############--------]
  > imputador: iterative
     ok random_forest              acc=0.844  mf1=0.732  wf1=0.865  [#################---]
     ok lightgbm                   acc=0.821  mf1=0.698  wf1=0.846  [################----]
  > imputador: knn_7
     ok lightgbm                   acc=0.858  mf1=0.750  wf1=0.876  [#################---]
  > imputador: iterative
     ok logistic_regression        acc=0.834  mf1=0.713  wf1=0.856  [#################---]
     ok random_forest              acc=0.851  mf1=0.737  wf1=0.870  [#################---]
     ok lightgbm                   acc=0.859  mf1=0.751  wf1=0.876  [#################---]
  > imputador: miceforest
  [miceforest] fallback SimpleImputer (AssertionError)
     ok logistic_regression        acc=0.810  mf1=0.684  wf1=0.837  [################----]
     ok random_forest              acc=0.849  mf1=0.733  wf1=0.868  [#################---]
     ok lightgbm                   acc=0.856  mf1=0.748  wf1=0.874  [#################---]

  EXPERIMENTO  MAR   5%  [bank_marketing]
  --------------------------------------------------
  > imputador: dropna
     ok logistic_regression        acc=0.744  mf1=0.662  wf1=0.768  [###############-----]
     ok random_forest              acc=0.797  mf1=0.693  wf1=0.807  [################----]
     ok lightgbm                   acc=0.814  mf1=0.710  wf1=0.821  [################----]
  > imputador: simple_mean
     ok logistic_regression        acc=0.834  mf1=0.712  wf1=0.855  [#################---]
     ok random_forest              acc=0.843  mf1=0.727  wf1=0.863  [#################---]
     ok lightgbm                   acc=0.854  mf1=0.743  wf1=0.873  [#################---]
  > imputador: simple_median
     ok logistic_regression        acc=0.836  mf1=0.714  wf1=0.857  [#################---]
     ok random_forest              acc=0.844  mf1=0.728  wf1=0.864  [#################---]
     ok lightgbm                   acc=0.857  mf1=0.746  wf1=0.875  [#################---]
  > imputador: simple_freq
     ok logistic_regression        acc=0.835  mf1=0.713  wf1=0.856  [#################---]
     ok logistic_regression        acc=0.811  mf1=0.680  wf1=0.837  [################----]
     ok ridge_regression           mae=0.0992  rmse=0.1412  r2=0.6246  [############--------]
     ok random_forest              acc=0.845  mf1=0.728  wf1=0.864  [#################---]
     ok lightgbm                   acc=0.857  mf1=0.746  wf1=0.875  [#################---]
  > imputador: simple_const
     ok logistic_regression        acc=0.835  mf1=0.714  wf1=0.857  [#################---]
     ok random_forest              acc=0.840  mf1=0.723  wf1=0.861  [#################---]
     ok lightgbm                   acc=0.855  mf1=0.745  wf1=0.873  [#################---]
  > imputador: knn_3
     ok logistic_regression        acc=0.832  mf1=0.710  wf1=0.854  [#################---]
     ok random_forest              acc=0.820  mf1=0.688  wf1=0.843  [################----]
     ok random_forest              acc=0.839  mf1=0.722  wf1=0.860  [#################---]
     ok ridge_regression           mae=0.0952  rmse=0.1365  r2=0.6108  [############--------]
     ok random_forest              mae=0.0943  rmse=0.1379  r2=0.6416  [############--------]
     ok lightgbm                   acc=0.852  mf1=0.740  wf1=0.871  [#################---]
  > imputador: knn_5
     ok lightgbm                   acc=0.823  mf1=0.698  wf1=0.847  [################----]
  > imputador: iterative
     ok logistic_regression        acc=0.819  mf1=0.688  wf1=0.843  [################----]
     ok logistic_regression        acc=0.834  mf1=0.711  wf1=0.855  [#################---]
     ok random_forest              acc=0.827  mf1=0.691  wf1=0.848  [################----]
     ok lightgbm                   acc=0.827  mf1=0.703  wf1=0.850  [################----]
  > imputador: miceforest
  [miceforest] fallback SimpleImputer (AssertionError)
     ok logistic_regression        acc=0.773  mf1=0.638  wf1=0.807  [################----]
     ok random_forest              acc=0.844  mf1=0.728  wf1=0.864  [#################---]
     ok random_forest              acc=0.833  mf1=0.695  wf1=0.852  [#################---]
     ok lightgbm                   acc=0.826  mf1=0.702  wf1=0.850  [################----]

  EXPERIMENTO  MCAR  30%  [bank_marketing]
  --------------------------------------------------
  > imputador: dropna
     ok logistic_regression        acc=0.500  mf1=0.333  wf1=0.333  [######--------------]
     ok random_forest              acc=0.500  mf1=0.333  wf1=0.333  [######--------------]
     ok lightgbm                   acc=0.500  mf1=0.333  wf1=0.333  [######--------------]
  > imputador: simple_mean
     ok logistic_regression        acc=0.810  mf1=0.675  wf1=0.835  [################----]
     ok lightgbm                   acc=0.855  mf1=0.743  wf1=0.873  [#################---]
  > imputador: knn_7
     ok random_forest              acc=0.807  mf1=0.672  wf1=0.833  [################----]
     ok lightgbm                   acc=0.816  mf1=0.688  wf1=0.841  [################----]
  > imputador: simple_median
     ok random_forest              mae=0.0946  rmse=0.1372  r2=0.6068  [############--------]
     ok lightgbm                   mae=0.0917  rmse=0.1342  r2=0.6606  [#############-------]
  > imputador: miceforest
[miceforest] 122 colunas → usando top-50 por variância
  [miceforest] fallback SimpleImputer (AssertionError)
     ok ridge_regression           mae=0.1014  rmse=0.1426  r2=0.6171  [############--------]
     ok logistic_regression        acc=0.811  mf1=0.676  wf1=0.836  [################----]
     ok random_forest              mae=0.0970  rmse=0.1398  r2=0.6318  [############--------]
     ok lightgbm                   mae=0.0950  rmse=0.1393  r2=0.6343  [############--------]

  EXPERIMENTO  MCAR   5%  [communities_crime]
  --------------------------------------------------
  > imputador: dropna
  > imputador: simple_mean
     ok ridge_regression           mae=0.1025  rmse=0.1445  r2=0.6067  [############--------]
     ok random_forest              acc=0.803  mf1=0.671  wf1=0.831  [################----]
     ok lightgbm                   acc=0.818  mf1=0.692  wf1=0.843  [################----]
  > imputador: simple_freq
     ok random_forest              mae=0.0991  rmse=0.1426  r2=0.6169  [############--------]
     ok lightgbm                   mae=0.0958  rmse=0.1383  r2=0.6397  [############--------]
  > imputador: simple_median
     ok ridge_regression           mae=0.1015  rmse=0.1442  r2=0.6083  [############--------]
     ok logistic_regression        acc=0.806  mf1=0.672  wf1=0.833  [################----]
     ok random_forest              mae=0.0986  rmse=0.1425  r2=0.6177  [############--------]
     ok lightgbm                   mae=0.0947  rmse=0.1395  r2=0.6333  [############--------]
  > imputador: simple_freq
     ok random_forest              acc=0.829  mf1=0.696  wf1=0.850  [################----]
     ok ridge_regression           mae=0.1003  rmse=0.1436  r2=0.6116  [############--------]
     ok lightgbm                   acc=0.823  mf1=0.696  wf1=0.846  [################----]
  > imputador: simple_const
     ok logistic_regression        acc=0.834  mf1=0.712  wf1=0.855  [#################---]
     ok random_forest              mae=0.0970  rmse=0.1399  r2=0.6312  [############--------]
     ok logistic_regression        acc=0.794  mf1=0.660  wf1=0.823  [################----]
     ok lightgbm                   mae=0.0934  rmse=0.1383  r2=0.6396  [############--------]
  > imputador: simple_const
     ok ridge_regression           mae=0.1058  rmse=0.1505  r2=0.5736  [###########---------]
     ok random_forest              mae=0.0994  rmse=0.1423  r2=0.6184  [############--------]
     ok random_forest              acc=0.834  mf1=0.697  wf1=0.853  [#################---]
     ok lightgbm                   mae=0.0942  rmse=0.1402  r2=0.6298  [############--------]
  > imputador: knn_3
     ok lightgbm                   acc=0.813  mf1=0.687  wf1=0.839  [################----]
  > imputador: knn_3
     ok ridge_regression           mae=0.1010  rmse=0.1398  r2=0.6318  [############--------]
     ok random_forest              acc=0.845  mf1=0.728  wf1=0.864  [#################---]
     ok random_forest              mae=0.0988  rmse=0.1420  r2=0.6203  [############--------]
     ok lightgbm                   mae=0.0975  rmse=0.1426  r2=0.6171  [############--------]
  > imputador: knn_5
     ok lightgbm                   mae=0.0914  rmse=0.1370  r2=0.6079  [############--------]
  > imputador: miceforest
[miceforest] 122 colunas → usando top-50 por variância
  [miceforest] fallback SimpleImputer (AssertionError)
     ok ridge_regression           mae=0.0991  rmse=0.1421  r2=0.5783  [###########---------]
     ok ridge_regression           mae=0.1008  rmse=0.1408  r2=0.6264  [############--------]
     ok random_forest              mae=0.0931  rmse=0.1369  r2=0.6085  [############--------]
     ok lightgbm                   mae=0.0889  rmse=0.1351  r2=0.6187  [############--------]

  EXPERIMENTO  MCAR  15%  [communities_crime]
  --------------------------------------------------
  > imputador: dropna
  > imputador: simple_mean
     ok ridge_regression           mae=0.0999  rmse=0.1391  r2=0.5962  [###########---------]
     ok random_forest              mae=0.0973  rmse=0.1400  r2=0.6306  [############--------]
     ok random_forest              mae=0.0966  rmse=0.1391  r2=0.5963  [###########---------]
     ok lightgbm                   mae=0.0938  rmse=0.1398  r2=0.5920  [###########---------]
  > imputador: simple_median
     ok ridge_regression           mae=0.1005  rmse=0.1417  r2=0.5810  [###########---------]
     ok lightgbm                   mae=0.0919  rmse=0.1349  r2=0.6570  [#############-------]
  > imputador: knn_7
     ok random_forest              mae=0.0956  rmse=0.1381  r2=0.6018  [############--------]
     ok ridge_regression           mae=0.1007  rmse=0.1405  r2=0.6280  [############--------]
     ok lightgbm                   mae=0.0920  rmse=0.1379  r2=0.6032  [############--------]
  > imputador: simple_freq
     ok lightgbm                   acc=0.855  mf1=0.744  wf1=0.873  [#################---]
  > imputador: iterative
     ok ridge_regression           mae=0.1003  rmse=0.1417  r2=0.5806  [###########---------]
     ok logistic_regression        acc=0.834  mf1=0.712  wf1=0.856  [#################---]
     ok random_forest              mae=0.0940  rmse=0.1386  r2=0.5991  [###########---------]
     ok lightgbm                   mae=0.0946  rmse=0.1415  r2=0.5821  [###########---------]
  > imputador: simple_const
     ok ridge_regression           mae=0.1033  rmse=0.1444  r2=0.5645  [###########---------]
     ok random_forest              acc=0.839  mf1=0.721  wf1=0.860  [#################---]
     ok random_forest              mae=0.0979  rmse=0.1406  r2=0.6275  [############--------]
     ok lightgbm                   acc=0.854  mf1=0.744  wf1=0.873  [#################---]
  > imputador: miceforest
  [miceforest] fallback SimpleImputer (AssertionError)
     ok logistic_regression        acc=0.798  mf1=0.671  wf1=0.827  [################----]
     ok random_forest              mae=0.0993  rmse=0.1438  r2=0.5684  [###########---------]
     ok lightgbm                   mae=0.0946  rmse=0.1402  r2=0.6299  [############--------]
  > imputador: iterative
     ok lightgbm                   mae=0.0948  rmse=0.1419  r2=0.5799  [###########---------]
  > imputador: knn_3
     ok random_forest              acc=0.853  mf1=0.735  wf1=0.870  [#################---]
     ok lightgbm                   acc=0.855  mf1=0.744  wf1=0.873  [#################---]

  EXPERIMENTO  MAR  10%  [bank_marketing]
  --------------------------------------------------
  > imputador: dropna
     ok logistic_regression        acc=0.790  mf1=0.702  wf1=0.812  [################----]
     ok random_forest              acc=0.858  mf1=0.698  wf1=0.847  [################----]

 67%|██████▋   | 8/12 [17:04:14<8:32:07, 7681.79s/it]

     ok lightgbm                   acc=0.863  mf1=0.759  wf1=0.880  [#################---]
[cache] data\communities_crime\communities.data

========================================================================
  REGRESSAO  |  COMMUNITIES_CRIME  |  target: ViolentCrimesPerPop
========================================================================
     ok ridge_regression           mae=0.0968  rmse=0.1416  r2=0.6266  [############--------]
     ok random_forest              mae=0.0966  rmse=0.1418  r2=0.6258  [############--------]
     ok lightgbm                   mae=0.0914  rmse=0.1399  r2=0.6356  [############--------]

  EXPERIMENTO  MCAR   1%  [communities_crime]
  --------------------------------------------------
  > imputador: dropna
     ok ridge_regression           mae=0.2845  rmse=0.3656  r2=-1.5218  [--------------------]
     ok random_forest              mae=0.1475  rmse=0.1722  r2=0.4404  [########------------]
     ok random_forest              acc=0.830  mf1=0.709  wf1=0.853  [#################---]
     ok lightgbm                   mae=0.1455  rmse=0.1671  r2=0.4734  [#########-----------]
  > imputador: simple_mean
     ok ridge_regression           mae=0.0977  rmse=0.1413  r2=0.6287  [############--------]
     ok random_forest              mae=0.0967  rmse=0.1417  r2=0.6261  [############--------]
     ok lightgbm                   mae=0.0909  rmse=0.1387  r2=0.6418  [############--------]
  > imputador: simple_median
     ok ridge_regression           mae=0.0990  rmse=0.1422  r2=0.6236  [############--------]
     ok random_forest              mae=0.0973  rmse=0.1427  r2=0.6208  [############--------]
     ok lightgbm                   mae=0.0908  rmse=0.1393  r2=0.6387  [############--------]
  > imputador: simple_freq
     ok ridge_regression           mae=0.0999  rmse=0.1430  r2=0.6193  [############--------]
     ok random_forest              mae=0.0972  rmse=0.1425  r2=0.6220  [############--------]
     ok lightgbm                   mae=0.0932  rmse=0.1416  r2=0.6267  [############--------]
  > imputador: simple_const
     ok ridge_regression           mae=0.1026  rmse=0.1457  r2=0.6051  [############--------]
     ok lightgbm                   mae=0.0922  rmse=0.1375  r2=0.6052  [############--------]
  > imputador: miceforest
[miceforest] 122 colunas → usando top-50 por variância
  [miceforest] fallback SimpleImputer (AssertionError)
     ok ridge_regression           mae=0.1006  rmse=0.1416  r2=0.5816  [###########---------]
     ok random_forest              mae=0.0976  rmse=0.1440  r2=0.6143  [############--------]
     ok lightgbm                   mae=0.0949  rmse=0.1441  r2=0.6134  [############--------]
  > imputador: knn_3
     ok random_forest              mae=0.0948  rmse=0.1376  r2=0.6044  [############--------]
     ok lightgbm                   mae=0.0935  rmse=0.1377  r2=0.6042  [############--------]

  EXPERIMENTO  MNAR  20%  [communities_crime]
  --------------------------------------------------
  > imputador: dropna
  > imputador: simple_mean
     ok ridge_regression           mae=0.0991  rmse=0.1408  r2=0.5860  [###########---------]
     ok ridge_regression           mae=0.0951  rmse=0.1391  r2=0.6399  [############--------]
     ok random_forest              mae=0.0942  rmse=0.1376  r2=0.6046  [############--------]
     ok lightgbm                   mae=0.0914  rmse=0.1357  r2=0.6157  [############--------]
  > imputador: simple_median
     ok ridge_regression           mae=0.1011  rmse=0.1419  r2=0.5794  [###########---------]
     ok random_forest              mae=0.0954  rmse=0.1392  r2=0.5954  [###########---------]
     ok random_forest              mae=0.0930  rmse=0.1384  r2=0.6437  [############--------]
     ok lightgbm                   mae=0.0914  rmse=0.1356  r2=0.6160  [############--------]
  > imputador: simple_freq
     ok ridge_regression           mae=0.0999  rmse=0.1402  r2=0.5895  [###########---------]
     ok random_forest              mae=0.0954  rmse=0.1381  r2=0.6019  [############--------]
     ok lightgbm                   mae=0.0921  rmse=0.1425  r2=0.6222  [############--------]
  > imputador: knn_5
     ok lightgbm                   acc=0.837  mf1=0.724  wf1=0.859  [#################---]
  > imputador: knn_7
     ok lightgbm                   mae=0.0904  rmse=0.1342  r2=0.6242  [############--------]
  > imputador: simple_const
     ok ridge_regression           mae=0.1009  rmse=0.1418  r2=0.5801  [###########---------]
     ok ridge_regression           mae=0.0961  rmse=0.1405  r2=0.6325  [############--------]
     ok random_forest              mae=0.0942  rmse=0.1378  r2=0.6033  [############--------]
     ok lightgbm                   mae=0.0946  rmse=0.1410  r2=0.5847  [###########---------]
  > imputador: knn_3
     ok random_forest              mae=0.0949  rmse=0.1419  r2=0.6253  [############--------]
     ok lightgbm                   mae=0.0931  rmse=0.1413  r2=0.6283  [############--------]
  > imputador: knn_7
     ok ridge_regression           mae=0.1071  rmse=0.1620  r2=0.5058  [##########----------]
     ok ridge_regression           mae=0.0948  rmse=0.1358  r2=0.6147  [############--------]
     ok ridge_regression           mae=0.0968  rmse=0.1407  r2=0.6317  [############--------]
     ok random_forest              mae=0.0957  rmse=0.1412  r2=0.6292  [############--------]
     ok random_forest              mae=0.0945  rmse=0.1380  r2=0.6024  [############--------]
     ok lightgbm                   mae=0.0922  rmse=0.1420  r2=0.6245  [############--------]
  > imputador: iterative
     ok lightgbm                   mae=0.0895  rmse=0.1369  r2=0.6089  [############--------]
  > imputador: knn_5
     ok ridge_regression           mae=0.0971  rmse=0.1380  r2=0.6026  [############--------]
     ok logistic_regression        acc=0.800  mf1=0.675  wf1=0.830  [################----]
     ok random_forest              mae=0.0972  rmse=0.1409  r2=0.5857  [###########---------]
     ok random_forest              mae=0.0984  rmse=0.1426  r2=0.6168  [############--------]
     ok lightgbm                   mae=0.0931  rmse=0.1402  r2=0.5899  [###########---------]
  > imputador: knn_7
     ok ridge_regression           mae=0.0955  rmse=0.1376  r2=0.6048  [############--------]
     ok random_forest              mae=0.0946  rmse=0.1388  r2=0.5977  [###########---------]
     ok random_forest              acc=0.836  mf1=0.716  wf1=0.857  [#################---]
     ok lightgbm                   mae=0.0899  rmse=0.1354  r2=0.6171  [############--------]
  > imputador: iterative
     ok lightgbm                   acc=0.838  mf1=0.726  wf1=0.860  [#################---]
  > imputador: iterative
     ok lightgbm                   mae=0.0959  rmse=0.1393  r2=0.6347  [############--------]
  > imputador: miceforest
[miceforest] 122 colunas → usando top-50 por variância
  [miceforest] fallback SimpleImputer (AssertionError)
     ok logistic_regression        acc=0.812  mf1=0.688  wf1=0.839  [################----]
     ok ridge_regression           mae=0.1021  rmse=0.1423  r2=0.6186  [############--------]
     ok random_forest              mae=0.0986  rmse=0.1429  r2=0.6155  [############--------]
     ok lightgbm                   mae=0.0918  rmse=0.1361  r2=0.6512  [#############-------]

  EXPERIMENTO  MNAR  15%  [communities_crime]
  --------------------------------------------------
  > imputador: dropna
  > imputador: simple_mean
     ok ridge_regression           mae=0.0992  rmse=0.1417  r2=0.6219  [############--------]
     ok random_forest              mae=0.1001  rmse=0.1444  r2=0.6070  [############--------]
     ok random_forest              acc=0.836  mf1=0.727  wf1=0.859  [#################---]
     ok lightgbm                   mae=0.0945  rmse=0.1395  r2=0.6335  [############--------]
  > imputador: simple_median
     ok ridge_regression           mae=0.0986  rmse=0.1408  r2=0.6266  [############--------]
     ok ridge_regression           mae=0.0980  rmse=0.1440  r2=0.6140  [############--------]
     ok random_forest              mae=0.0986  rmse=0.1433  r2=0.6132  [############--------]
     ok lightgbm                   mae=0.0930  rmse=0.1397  r2=0.6324  [############--------]
  > imputador: simple_freq
     ok lightgbm                   acc=0.848  mf1=0.743  wf1=0.869  [#################---]
  > imputador: miceforest
  [miceforest] fallback SimpleImputer (AssertionError)
     ok ridge_regression           mae=0.0998  rmse=0.1414  r2=0.6235  [############--------]
     ok logistic_regression        acc=0.800  mf1=0.664  wf1=0.828  [################----]
     ok random_forest              mae=0.0975  rmse=0.1416  r2=0.6221  [############--------]
     ok lightgbm                   mae=0.0951  rmse=0.1404  r2=0.6289  [############--------]
  > imputador: simple_const
     ok ridge_regression           mae=0.1012  rmse=0.1435  r2=0.6124  [############--------]
     ok random_forest              acc=0.863  mf1=0.761  wf1=0.881  [#################---]
     ok random_forest              mae=0.0953  rmse=0.1386  r2=0.6380  [############--------]
     ok lightgbm                   acc=0.857  mf1=0.756  wf1=0.876  [#################---]

  EXPERIMENTO  MNAR  30%  [bank_marketing]
  --------------------------------------------------
     ok lightgbm                   mae=0.0929  rmse=0.1373  r2=0.6450  [############--------]
  > imputador: knn_3
  > imputador: dropna
     ok logistic_regression        acc=0.714  mf1=0.713  wf1=0.719  [##############------]
     ok random_forest              acc=0.750  mf1=0.750  wf1=0.752  [###############-----]
     ok lightgbm                   acc=0.786  mf1=0.785  wf1=0.789  [###############-----]
  > imputador: simple_mean
     ok logistic_regression        acc=0.822  mf1=0.694  wf1=0.846  [################----]
     ok random_forest              acc=0.835  mf1=0.724  wf1=0.858  [#################---]
     ok ridge_regression           mae=0.0963  rmse=0.1378  r2=0.6422  [############--------]
     ok lightgbm                   acc=0.851  mf1=0.748  wf1=0.872  [#################---]
  > imputador: simple_median
     ok logistic_regression        acc=0.837  mf1=0.711  wf1=0.857  [#################---]
     ok random_forest              acc=0.831  mf1=0.715  wf1=0.854  [#################---]
     ok random_forest              mae=0.0997  rmse=0.1432  r2=0.6136  [############--------]
     ok lightgbm                   acc=0.849  mf1=0.742  wf1=0.869  [#################---]
  > imputador: simple_freq
     ok logistic_regression        acc=0.837  mf1=0.715  wf1=0.858  [#################---]
     ok lightgbm                   mae=0.0951  rmse=0.1404  r2=0.6285  [############--------]
  > imputador: knn_5
     ok random_forest              acc=0.839  mf1=0.724  wf1=0.860  [#################---]
     ok lightgbm                   acc=0.849  mf1=0.742  wf1=0.869  [#################---]
  > imputador: simple_const
     ok logistic_regression        acc=0.834  mf1=0.714  wf1=0.856  [#################---]
     ok random_forest              acc=0.830  mf1=0.715  wf1=0.854  [#################---]
     ok ridge_regression           mae=0.0979  rmse=0.1382  r2=0.6403  [############--------]
     ok lightgbm                   acc=0.850  mf1=0.744  wf1=0.871  [#################---]
  > imputador: knn_3
     ok random_forest              mae=0.0959  rmse=0.1413  r2=0.6284  [############--------]
     ok random_forest              mae=0.0979  rmse=0.1407  r2=0.6273  [############--------]
     ok lightgbm                   mae=0.0935  rmse=0.1390  r2=0.6358  [############--------]
  > imputador: knn_7
     ok ridge_regression           mae=0.0969  rmse=0.1379  r2=0.6027  [############--------]
     ok ridge_regression           mae=0.0979  rmse=0.1385  r2=0.6386  [############--------]
     ok random_forest              mae=0.0991  rmse=0.1413  r2=0.6239  [############--------]
     ok lightgbm                   mae=0.0948  rmse=0.1383  r2=0.6398  [############--------]
  > imputador: iterative
     ok logistic_regression        acc=0.812  mf1=0.682  wf1=0.837  [################----]
     ok lightgbm                   mae=0.0930  rmse=0.1414  r2=0.6279  [############--------]
  > imputador: miceforest
[miceforest] 122 colunas → usando top-50 por variância
  [miceforest] fallback SimpleImputer (AssertionError)
     ok ridge_regression           mae=0.0977  rmse=0.1413  r2=0.6287  [############--------]
     ok random_forest              mae=0.0967  rmse=0.1417  r2=0.6261  [############--------]
     ok lightgbm                   mae=0.0909  rmse=0.1387  r2=0.6418  [############--------]

  EXPERIMENTO  MCAR   5%  [communities_crime]
  --------------------------------------------------
  > imputador: dropna
  > imputador: simple_mean
     ok ridge_regression           mae=0.1044  rmse=0.1502  r2=0.5799  [###########---------]
     ok random_forest              mae=0.0979  rmse=0.1434  r2=0.6175  [############--------]
     ok lightgbm                   mae=0.0953  rmse=0.1405  r2=0.6324  [############--------]
  > imputador: simple_median
     ok ridge_regression           mae=0.1033  rmse=0.1489  r2=0.5871  [###########---------]
     ok random_forest              mae=0.0976  rmse=0.1436  r2=0.6160  [############--------]
     ok lightgbm                   mae=0.0950  rmse=0.1400  r2=0.6351  [############--------]
  > imputador: simple_freq
     ok ridge_regression           mae=0.1013  rmse=0.1473  r2=0.5959  [###########---------]
     ok random_forest              mae=0.0977  rmse=0.1441  r2=0.6134  [############--------]
     ok lightgbm                   mae=0.0971  rmse=0.1452  r2=0.6078  [############--------]
  > imputador: simple_const
     ok ridge_regression           mae=0.1023  rmse=0.1475  r2=0.5952  [###########---------]
     ok random_forest              mae=0.0952  rmse=0.1373  r2=0.6065  [############--------]
     ok random_forest              mae=0.0981  rmse=0.1455  r2=0.6062  [############--------]
     ok lightgbm                   mae=0.0983  rmse=0.1475  r2=0.5952  [###########---------]
  > imputador: knn_3
     ok random_forest              acc=0.826  mf1=0.703  wf1=0.850  [################----]
     ok ridge_regression           mae=0.0962  rmse=0.1398  r2=0.6364  [############--------]
     ok random_forest              mae=0.0955  rmse=0.1412  r2=0.6291  [############--------]
     ok lightgbm                   mae=0.0949  rmse=0.1440  r2=0.6142  [############--------]
  > imputador: knn_5
     ok ridge_regression           mae=0.0966  rmse=0.1395  r2=0.6378  [############--------]
     ok random_forest              mae=0.0956  rmse=0.1422  r2=0.6238  [############--------]
     ok lightgbm                   acc=0.821  mf1=0.706  wf1=0.847  [################----]
  > imputador: knn_5
     ok lightgbm                   mae=0.0928  rmse=0.1416  r2=0.6271  [############--------]
  > imputador: knn_7
     ok ridge_regression           mae=0.0972  rmse=0.1401  r2=0.6349  [############--------]
     ok random_forest              mae=0.0957  rmse=0.1426  r2=0.6216  [############--------]
     ok lightgbm                   mae=0.0917  rmse=0.1375  r2=0.6054  [############--------]
  > imputador: miceforest
[miceforest] 122 colunas → usando top-50 por variância
  [miceforest] fallback SimpleImputer (AssertionError)
     ok ridge_regression           mae=0.0991  rmse=0.1408  r2=0.5860  [###########---------]
     ok random_forest              mae=0.0942  rmse=0.1376  r2=0.6046  [############--------]
     ok lightgbm                   mae=0.0914  rmse=0.1357  r2=0.6157  [############--------]

  EXPERIMENTO  MNAR  25%  [communities_crime]
  --------------------------------------------------
     ok lightgbm                   mae=0.0938  rmse=0.1438  r2=0.6151  [############--------]
  > imputador: iterative
  > imputador: dropna
  > imputador: simple_mean
     ok ridge_regression           mae=0.1005  rmse=0.1422  r2=0.5780  [###########---------]
     ok ridge_regression           mae=0.1025  rmse=0.1451  r2=0.6035  [############--------]
     ok random_forest              mae=0.0942  rmse=0.1375  r2=0.6051  [############--------]
     ok lightgbm                   mae=0.0932  rmse=0.1385  r2=0.5997  [###########---------]
  > imputador: simple_median
     ok ridge_regression           mae=0.1015  rmse=0.1439  r2=0.5676  [###########---------]
     ok random_forest              mae=0.0967  rmse=0.1383  r2=0.6007  [############--------]
     ok lightgbm                   mae=0.0930  rmse=0.1383  r2=0.6006  [############--------]
  > imputador: simple_freq
     ok ridge_regression           mae=0.0962  rmse=0.1381  r2=0.6021  [############--------]
     ok random_forest              mae=0.0946  rmse=0.1394  r2=0.5941  [###########---------]
     ok lightgbm                   mae=0.0937  rmse=0.1412  r2=0.5837  [###########---------]
  > imputador: simple_const
     ok ridge_regression           mae=0.1017  rmse=0.1450  r2=0.5611  [###########---------]
     ok random_forest              mae=0.0960  rmse=0.1404  r2=0.5887  [###########---------]
     ok lightgbm                   mae=0.0917  rmse=0.1396  r2=0.5931  [###########---------]
  > imputador: knn_3
     ok logistic_regression        acc=0.814  mf1=0.685  wf1=0.840  [################----]
     ok ridge_regression           mae=0.0975  rmse=0.1366  r2=0.6107  [############--------]
     ok random_forest              mae=0.0939  rmse=0.1354  r2=0.6170  [############--------]
     ok lightgbm                   mae=0.0962  rmse=0.1403  r2=0.5890  [###########---------]
  > imputador: knn_5
     ok random_forest              mae=0.0956  rmse=0.1379  r2=0.6417  [############--------]
     ok random_forest              acc=0.830  mf1=0.712  wf1=0.853  [#################---]
     ok ridge_regression           mae=0.0989  rmse=0.1381  r2=0.6016  [############--------]
     ok random_forest              mae=0.0964  rmse=0.1386  r2=0.5988  [###########---------]
     ok lightgbm                   mae=0.0922  rmse=0.1393  r2=0.5949  [###########---------]
  > imputador: knn_7
     ok lightgbm                   acc=0.829  mf1=0.716  wf1=0.853  [#################---]
  > imputador: knn_7
     ok ridge_regression           mae=0.0974  rmse=0.1366  r2=0.6105  [############--------]
     ok ridge_regression           mae=0.1004  rmse=0.1468  r2=0.5987  [###########---------]
     ok lightgbm                   mae=0.0934  rmse=0.1365  r2=0.6490  [############--------]
  > imputador: miceforest
[miceforest] 122 colunas → usando top-50 por variância
  [miceforest] fallback SimpleImputer (AssertionError)
     ok ridge_regression           mae=0.0992  rmse=0.1417  r2=0.6219  [############--------]
     ok random_forest              mae=0.0966  rmse=0.1387  r2=0.5981  [###########---------]
     ok random_forest              mae=0.1001  rmse=0.1444  r2=0.6070  [############--------]
     ok lightgbm                   mae=0.0945  rmse=0.1395  r2=0.6335  [############--------]

  EXPERIMENTO  MNAR  20%  [communities_crime]
  --------------------------------------------------
  > imputador: dropna
  > imputador: simple_mean
     ok ridge_regression           mae=0.1044  rmse=0.1460  r2=0.5987  [###########---------]
     ok random_forest              mae=0.0990  rmse=0.1412  r2=0.6242  [############--------]
     ok lightgbm                   mae=0.0929  rmse=0.1364  r2=0.6495  [############--------]
  > imputador: simple_median
     ok lightgbm                   mae=0.0897  rmse=0.1349  r2=0.6201  [############--------]
  > imputador: iterative
     ok ridge_regression           mae=0.1028  rmse=0.1443  r2=0.6077  [############--------]
     ok random_forest              mae=0.0999  rmse=0.1428  r2=0.6158  [############--------]
     ok lightgbm                   mae=0.0933  rmse=0.1364  r2=0.6494  [############--------]
  > imputador: simple_freq
     ok ridge_regression           mae=0.0988  rmse=0.1413  r2=0.6239  [############--------]

 75%|███████▌  | 9/12 [17:51:15<5:57:05, 7141.77s/it]

     ok lightgbm                   acc=0.858  mf1=0.755  wf1=0.877  [#################---]
     ok lightgbm                   mae=0.0962  rmse=0.1459  r2=0.6037  [############--------]
  > imputador: knn_5
     ok random_forest              mae=0.0937  rmse=0.1364  r2=0.6117  [############--------]
     ok ridge_regression           mae=0.0993  rmse=0.1422  r2=0.6237  [############--------]
     ok random_forest              mae=0.0949  rmse=0.1417  r2=0.6260  [############--------]
     ok lightgbm                   mae=0.0920  rmse=0.1401  r2=0.6348  [############--------]
  > imputador: knn_7
     ok ridge_regression           mae=0.0990  rmse=0.1413  r2=0.6283  [############--------]
     ok random_forest              mae=0.0952  rmse=0.1415  r2=0.6275  [############--------]
     ok lightgbm                   mae=0.0917  rmse=0.1411  r2=0.6295  [############--------]
  > imputador: iterative
     ok lightgbm                   mae=0.0900  rmse=0.1343  r2=0.6236  [############--------]
  > imputador: miceforest
[miceforest] 122 colunas → usando top-50 por variância
  [miceforest] fallback SimpleImputer (AssertionError)
     ok ridge_regression           mae=0.1005  rmse=0.1422  r2=0.5780  [###########---------]
     ok random_forest              mae=0.0942  rmse=0.1375  r2=0.6051  [############--------]
     ok lightgbm                   mae=0.0932  rmse=0.1385  r2=0.5997  [###########---------]

  EXPERIMENTO  MNAR  30%  [communities_crime]
  --------------------------------------------------
  > imputador: dropna
  > imputador: simple_mean
     ok ridge_regression           mae=0.0978  rmse=0.1376  r2=0.6046  [############--------]
     ok ridge_regression           mae=0.1181  rmse=0.2745  r2=-0.4192  [--------------------]
     ok random_forest              mae=0.0960  rmse=0.1396  r2=0.5929  [###########---------]
     ok lightgbm                   mae=0.0911  rmse=0.1392  r2=0.5956  [###########---------]
  > imputador: simple_median
     ok ridge_regression           mae=0.0989  rmse=0.1403  r2=0.5890  [###########---------]
     ok random_forest              mae=0.0965  rmse=0.1414  r2=0.5823  [###########---------]
     ok lightgbm                   mae=0.0923  rmse=0.1406  r2=0.5872  [###########---------]
  > imputador: simple_freq
     ok ridge_regression           mae=0.0972  rmse=0.1392  r2=0.5954  [###########---------]
     ok random_forest              mae=0.0955  rmse=0.1401  r2=0.5902  [###########---------]
     ok lightgbm                   mae=0.0907  rmse=0.1373  r2=0.6061  [############--------]
  > imputador: simple_const
     ok ridge_regression           mae=0.0964  rmse=0.1392  r2=0.5952  [###########---------]
     ok random_forest              mae=0.0944  rmse=0.1400  r2=0.5911  [###########---------]
     ok lightgbm                   mae=0.0937  rmse=0.1409  r2=0.5853  [###########---------]
  > imputador: knn_3
     ok ridge_regression           mae=0.0959  rmse=0.1325  r2=0.6336  [############--------]
     ok random_forest              mae=0.0966  rmse=0.1401  r2=0.5900  [###########---------]
     ok random_forest              mae=0.0980  rmse=0.1411  r2=0.6249  [############--------]
     ok lightgbm                   mae=0.0935  rmse=0.1389  r2=0.5972  [###########---------]
  > imputador: knn_5
     ok ridge_regression           mae=0.0989  rmse=0.1369  r2=0.6085  [############--------]
     ok ridge_regression           mae=0.0987  rmse=0.1410  r2=0.6301  [############--------]
     ok random_forest              mae=0.0944  rmse=0.1394  r2=0.5940  [###########---------]
     ok lightgbm                   mae=0.0932  rmse=0.1385  r2=0.5992  [###########---------]
  > imputador: knn_7
     ok lightgbm                   mae=0.0967  rmse=0.1388  r2=0.6369  [############--------]
  > imputador: miceforest
[miceforest] 122 colunas → usando top-50 por variância
  [miceforest] fallback SimpleImputer (AssertionError)
     ok ridge_regression           mae=0.1044  rmse=0.1460  r2=0.5987  [###########---------]
     ok random_forest              mae=0.0990  rmse=0.1412  r2=0.6242  [############--------]
     ok lightgbm                   mae=0.0929  rmse=0.1364  r2=0.6495  [############--------]

  EXPERIMENTO  MNAR  25%  [communities_crime]
  --------------------------------------------------
  > imputador: dropna
  > imputador: simple_mean
     ok ridge_regression           mae=0.1036  rmse=0.1421  r2=0.6197  [############--------]
     ok random_forest              mae=0.0998  rmse=0.1438  r2=0.6103  [############--------]
     ok lightgbm                   mae=0.0971  rmse=0.1413  r2=0.6241  [############--------]
  > imputador: simple_median
     ok ridge_regression           mae=0.1036  rmse=0.1406  r2=0.6276  [############--------]
     ok random_forest              mae=0.1006  rmse=0.1428  r2=0.6157  [############--------]
     ok ridge_regression           mae=0.0991  rmse=0.1377  r2=0.6042  [############--------]
     ok lightgbm                   mae=0.0932  rmse=0.1375  r2=0.6441  [############--------]
  > imputador: simple_freq
     ok ridge_regression           mae=0.1010  rmse=0.1386  r2=0.6383  [############--------]
     ok random_forest              mae=0.0986  rmse=0.1408  r2=0.6265  [############--------]
     ok lightgbm                   mae=0.0984  rmse=0.1434  r2=0.6125  [############--------]
  > imputador: simple_const
     ok ridge_regression           mae=0.1018  rmse=0.1433  r2=0.6130  [############--------]
     ok random_forest              mae=0.0985  rmse=0.1406  r2=0.6278  [############--------]
     ok lightgbm                   mae=0.0929  rmse=0.1363  r2=0.6501  [#############-------]
  > imputador: knn_3
     ok random_forest              mae=0.0964  rmse=0.1430  r2=0.6194  [############--------]
     ok random_forest              mae=0.0958  rmse=0.1386  r2=0.5990  [###########---------]
     ok ridge_regression           mae=0.0993  rmse=0.1402  r2=0.6295  [############--------]
     ok lightgbm                   mae=0.0964  rmse=0.1424  r2=0.5768  [###########---------]
  > imputador: iterative
     ok random_forest              mae=0.0992  rmse=0.1403  r2=0.6291  [############--------]
     ok lightgbm                   mae=0.0944  rmse=0.1392  r2=0.6351  [############--------]
  > imputador: knn_5
     ok lightgbm                   mae=0.0970  rmse=0.1458  r2=0.6045  [############--------]
  > imputador: miceforest
[miceforest] 122 colunas → usando top-50 por variância
  [miceforest] fallback SimpleImputer (AssertionError)
     ok ridge_regression           mae=0.1046  rmse=0.1523  r2=0.5684  [###########---------]
     ok ridge_regression           mae=0.0997  rmse=0.1408  r2=0.6266  [############--------]
     ok random_forest              mae=0.0956  rmse=0.1407  r2=0.6316  [############--------]
     ok lightgbm                   mae=0.0989  rmse=0.1460  r2=0.6032  [############--------]

  EXPERIMENTO  MCAR  15%  [communities_crime]
  --------------------------------------------------
  > imputador: dropna
  > imputador: simple_mean
     ok ridge_regression           mae=0.1009  rmse=0.1455  r2=0.6059  [############--------]
     ok random_forest              mae=0.0951  rmse=0.1398  r2=0.6364  [############--------]
     ok lightgbm                   mae=0.0954  rmse=0.1419  r2=0.6253  [############--------]
  > imputador: simple_median
     ok ridge_regression           mae=0.1011  rmse=0.1459  r2=0.6040  [############--------]
     ok random_forest              mae=0.0980  rmse=0.1398  r2=0.6320  [############--------]
     ok random_forest              mae=0.0965  rmse=0.1410  r2=0.6298  [############--------]
     ok lightgbm                   mae=0.0953  rmse=0.1438  r2=0.6149  [############--------]
  > imputador: simple_freq
     ok ridge_regression           mae=0.1020  rmse=0.1474  r2=0.5958  [###########---------]
     ok random_forest              mae=0.0979  rmse=0.1426  r2=0.6217  [############--------]
     ok lightgbm                   mae=0.0963  rmse=0.1427  r2=0.6209  [############--------]
  > imputador: simple_const
     ok ridge_regression           mae=0.1055  rmse=0.1546  r2=0.5550  [###########---------]
     ok lightgbm                   mae=0.0919  rmse=0.1371  r2=0.6461  [############--------]
  > imputador: knn_7
     ok random_forest              mae=0.1003  rmse=0.1464  r2=0.6013  [############--------]
     ok lightgbm                   mae=0.0970  rmse=0.1471  r2=0.5975  [###########---------]
  > imputador: knn_3
     ok ridge_regression           mae=0.0957  rmse=0.1379  r2=0.6461  [############--------]
     ok ridge_regression           mae=0.0999  rmse=0.1410  r2=0.6254  [############--------]
     ok ridge_regression           mae=0.1058  rmse=0.1516  r2=0.5200  [##########----------]
     ok random_forest              mae=0.0934  rmse=0.1380  r2=0.6454  [############--------]
     ok random_forest              mae=0.0963  rmse=0.1378  r2=0.6424  [############--------]
     ok lightgbm                   mae=0.0921  rmse=0.1402  r2=0.6340  [############--------]
  > imputador: knn_5
     ok lightgbm                   mae=0.0932  rmse=0.1363  r2=0.6502  [#############-------]
  > imputador: iterative
     ok ridge_regression           mae=0.0948  rmse=0.1373  r2=0.6493  [############--------]
     ok random_forest              mae=0.0946  rmse=0.1401  r2=0.6346  [############--------]
     ok random_forest              mae=0.0950  rmse=0.1382  r2=0.6013  [############--------]
     ok lightgbm                   mae=0.0899  rmse=0.1384  r2=0.6437  [############--------]
  > imputador: knn_7
     ok ridge_regression           mae=0.0951  rmse=0.1379  r2=0.6463  [############--------]
     ok random_forest              mae=0.0932  rmse=0.1394  r2=0.6384  [############--------]
     ok lightgbm                   mae=0.0943  rmse=0.1423  r2=0.6231  [############--------]
  > imputador: iterative
     ok lightgbm                   mae=0.0922  rmse=0.1409  r2=0.5852  [###########---------]
  > imputador: miceforest
[miceforest] 122 colunas → usando top-50 por variância
  [miceforest] fallback SimpleImputer (AssertionError)
     ok ridge_regression           mae=0.0978  rmse=0.1376  r2=0.6046  [############--------]
     ok random_forest              mae=0.0960  rmse=0.1396  r2=0.5929  [###########---------]

 83%|████████▎ | 10/12 [18:00:42<3:36:08, 6484.23s/it]

     ok lightgbm                   mae=0.0911  rmse=0.1392  r2=0.5956  [###########---------]
     ok ridge_regression           mae=0.1046  rmse=0.1498  r2=0.5771  [###########---------]
     ok random_forest              mae=0.0968  rmse=0.1383  r2=0.6396  [############--------]
     ok ridge_regression           mae=0.0989  rmse=0.1497  r2=0.5827  [###########---------]
     ok lightgbm                   mae=0.0960  rmse=0.1403  r2=0.6290  [############--------]
  > imputador: miceforest
[miceforest] 122 colunas → usando top-50 por variância
  [miceforest] fallback SimpleImputer (AssertionError)
     ok ridge_regression           mae=0.1036  rmse=0.1421  r2=0.6197  [############--------]
     ok random_forest              mae=0.0998  rmse=0.1438  r2=0.6103  [############--------]
     ok lightgbm                   mae=0.0971  rmse=0.1413  r2=0.6241  [############--------]

  EXPERIMENTO  MNAR  30%  [communities_crime]
  --------------------------------------------------
  > imputador: dropna
  > imputador: simple_mean
     ok ridge_regression           mae=0.1018  rmse=0.1432  r2=0.6136  [############--------]
     ok random_forest              mae=0.0953  rmse=0.1420  r2=0.6245  [############--------]
     ok random_forest              mae=0.0986  rmse=0.1423  r2=0.6186  [############--------]
     ok lightgbm                   mae=0.0953  rmse=0.1421  r2=0.6195  [############--------]
  > imputador: simple_median
     ok ridge_regression           mae=0.1036  rmse=0.1458  r2=0.5998  [###########---------]
     ok random_forest              mae=0.0998  rmse=0.1434  r2=0.6126  [############--------]
     ok lightgbm                   mae=0.0974  rmse=0.1409  r2=0.6259  [############--------]
  > imputador: simple_freq
     ok ridge_regression           mae=0.1024  rmse=0.1445  r2=0.6064  [############--------]
     ok random_forest              mae=0.0987  rmse=0.1420  r2=0.6200  [############--------]
     ok lightgbm                   mae=0.0974  rmse=0.1410  r2=0.6253  [############--------]
  > imputador: simple_const
     ok ridge_regression           mae=0.1032  rmse=0.1467  r2=0.5948  [###########---------]
     ok random_forest              mae=0.0982  rmse=0.1412  r2=0.6243  [############--------]
     ok lightgbm                   mae=0.0974  rmse=0.1406  r2=0.6275  [############--------]
  > imputador: knn_3
     ok ridge_regression           mae=0.1013  rmse=0.1441  r2=0.6086  [############--------]
     ok lightgbm                   mae=0.0896  rmse=0.1379  r2=0.6458  [############--------]
  > imputador: miceforest
[miceforest] 122 colunas → usando top-50 por variância
  [miceforest] fallback SimpleImputer (AssertionError)
     ok ridge_regression           mae=0.1009  rmse=0.1455  r2=0.6059  [############--------]
     ok random_forest              mae=0.0951  rmse=0.1398  r2=0.6364  [############--------]
     ok lightgbm                   mae=0.0954  rmse=0.1419  r2=0.6253  [############--------]

  EXPERIMENTO  MCAR  20%  [communities_crime]
  --------------------------------------------------
  > imputador: dropna
  > imputador: simple_mean
     ok ridge_regression           mae=0.1027  rmse=0.1477  r2=0.5938  [###########---------]
     ok random_forest              mae=0.0994  rmse=0.1442  r2=0.6084  [############--------]
     ok random_forest              mae=0.0977  rmse=0.1421  r2=0.6242  [############--------]
     ok lightgbm                   mae=0.0948  rmse=0.1422  r2=0.6239  [############--------]
  > imputador: simple_median
     ok ridge_regression           mae=0.1024  rmse=0.1486  r2=0.5890  [###########---------]
     ok lightgbm                   mae=0.0942  rmse=0.1386  r2=0.6380  [############--------]
  > imputador: knn_5
     ok random_forest              mae=0.0969  rmse=0.1409  r2=0.6305  [############--------]
     ok lightgbm                   mae=0.0954  rmse=0.1393  r2=0.6389  [############--------]
  > imputador: simple_freq
     ok ridge_regression           mae=0.1042  rmse=0.1501  r2=0.5809  [###########---------]
     ok ridge_regression           mae=0.1007  rmse=0.1436  r2=0.6114  [############--------]
     ok random_forest              mae=0.0959  rmse=0.1403  r2=0.6336  [############--------]
     ok lightgbm                   mae=0.0968  rmse=0.1425  r2=0.6220  [############--------]
  > imputador: simple_const
     ok ridge_regression           mae=0.1063  rmse=0.1549  r2=0.5534  [###########---------]
     ok random_forest              mae=0.0969  rmse=0.1427  r2=0.6207  [############--------]
     ok random_forest              mae=0.0975  rmse=0.1401  r2=0.6302  [############--------]
     ok lightgbm                   mae=0.0972  rmse=0.1454  r2=0.6063  [############--------]
  > imputador: knn_3
     ok lightgbm                   mae=0.0936  rmse=0.1361  r2=0.6512  [#############-------]
  > imputador: knn_7
     ok ridge_regression           mae=0.0984  rmse=0.1425  r2=0.6219  [############--------]
     ok ridge_regression           mae=0.1016  rmse=0.1443  r2=0.6076  [############--------]
     ok random_forest              mae=0.0944  rmse=0.1402  r2=0.6341  [############--------]
     ok lightgbm                   mae=0.0918  rmse=0.1363  r2=0.6543  [#############-------]
  > imputador: knn_5
     ok random_forest              mae=0.0993  rmse=0.1446  r2=0.6059  [############--------]
     ok ridge_regression           mae=0.0994  rmse=0.1438  r2=0.6150  [############--------]
     ok lightgbm                   mae=0.0961  rmse=0.1402  r2=0.6298  [############--------]
  > imputador: iterative
     ok random_forest              mae=0.0925  rmse=0.1386  r2=0.6426  [############--------]
     ok lightgbm                   mae=0.0931  rmse=0.1401  r2=0.6346  [############--------]
  > imputador: knn_7
     ok ridge_regression           mae=0.0982  rmse=0.1414  r2=0.6281  [############--------]
     ok random_forest              mae=0.0938  rmse=0.1410  r2=0.6301  [############--------]
     ok lightgbm                   mae=0.0959  rmse=0.1416  r2=0.6266  [############--------]
  > imputador: iterative
     ok ridge_regression           mae=0.1039  rmse=0.1483  r2=0.5858  [###########---------]
     ok random_forest              mae=0.0961  rmse=0.1387  r2=0.6378  [############--------]
     ok ridge_regression           mae=0.0975  rmse=0.1421  r2=0.6241  [############--------]
     ok lightgbm                   mae=0.0940  rmse=0.1353  r2=0.6554  [#############-------]
  > imputador: miceforest
[miceforest] 122 colunas → usando top-50 por variância
  [miceforest] fallback SimpleImputer (AssertionError)
     ok ridge_regression           mae=0.1018  rmse=0.1432  r2=0.6136  [############--------]
     ok random_forest              mae=0.0986  rmse=0.1423  r2=0.6186  [############--------]

 92%|█████████▏| 11/12 [18:07:21<1:38:51, 5931.03s/it]

     ok lightgbm                   mae=0.0953  rmse=0.1421  r2=0.6195  [############--------]
     ok random_forest              mae=0.0956  rmse=0.1416  r2=0.6270  [############--------]
     ok lightgbm                   mae=0.0939  rmse=0.1392  r2=0.6395  [############--------]
  > imputador: miceforest
[miceforest] 122 colunas → usando top-50 por variância
  [miceforest] fallback SimpleImputer (AssertionError)
     ok ridge_regression           mae=0.1027  rmse=0.1477  r2=0.5938  [###########---------]
     ok random_forest              mae=0.0977  rmse=0.1421  r2=0.6242  [############--------]
     ok lightgbm                   mae=0.0948  rmse=0.1422  r2=0.6239  [############--------]

  EXPERIMENTO  MCAR  25%  [communities_crime]
  --------------------------------------------------
  > imputador: dropna
  > imputador: simple_mean
     ok ridge_regression           mae=0.1034  rmse=0.1492  r2=0.5859  [###########---------]
     ok random_forest              mae=0.0947  rmse=0.1377  r2=0.6470  [############--------]
     ok lightgbm                   mae=0.0943  rmse=0.1407  r2=0.6313  [############--------]
  > imputador: simple_median
     ok ridge_regression           mae=0.1040  rmse=0.1497  r2=0.5828  [###########---------]
     ok random_forest              mae=0.0946  rmse=0.1368  r2=0.6517  [#############-------]
     ok lightgbm                   mae=0.0947  rmse=0.1423  r2=0.6229  [############--------]
  > imputador: simple_freq
     ok ridge_regression           mae=0.1043  rmse=0.1505  r2=0.5783  [###########---------]
     ok random_forest              mae=0.0947  rmse=0.1378  r2=0.6467  [############--------]
     ok lightgbm                   mae=0.0961  rmse=0.1432  r2=0.6181  [############--------]
  > imputador: simple_const
     ok ridge_regression           mae=0.1085  rmse=0.1571  r2=0.5406  [##########----------]
     ok random_forest              mae=0.0966  rmse=0.1415  r2=0.6273  [############--------]
     ok lightgbm                   mae=0.0983  rmse=0.1471  r2=0.5974  [###########---------]
  > imputador: knn_3
     ok ridge_regression           mae=0.0998  rmse=0.1430  r2=0.6193  [############--------]
     ok random_forest              mae=0.0916  rmse=0.1359  r2=0.6560  [#############-------]
     ok lightgbm                   mae=0.0894  rmse=0.1336  r2=0.6676  [#############-------]
  > imputador: knn_5
     ok ridge_regression           mae=0.1003  rmse=0.1424  r2=0.6225  [############--------]
     ok random_forest              mae=0.0927  rmse=0.1356  r2=0.6575  [#############-------]
     ok lightgbm                   mae=0.0891  rmse=0.1332  r2=0.6696  [#############-------]
  > imputador: knn_7
     ok ridge_regression           mae=0.0997  rmse=0.1416  r2=0.6267  [############--------]
     ok random_forest              mae=0.0927  rmse=0.1351  r2=0.6602  [#############-------]
     ok lightgbm                   mae=0.0915  rmse=0.1339  r2=0.6664  [#############-------]
  > imputador: iterative
     ok ridge_regression           mae=0.0993  rmse=0.1463  r2=0.6014  [############--------]
     ok random_forest              mae=0.0930  rmse=0.1362  r2=0.6548  [#############-------]
     ok lightgbm                   mae=0.0934  rmse=0.1389  r2=0.6408  [############--------]
  > imputador: miceforest
[miceforest] 122 colunas → usando top-50 por variância
  [miceforest] fallback SimpleImputer (AssertionError)
     ok ridge_regression           mae=0.1034  rmse=0.1492  r2=0.5859  [###########---------]
     ok random_forest              mae=0.0947  rmse=0.1377  r2=0.6470  [############--------]
     ok lightgbm                   mae=0.0943  rmse=0.1407  r2=0.6313  [############--------]

  EXPERIMENTO  MCAR  30%  [communities_crime]
  --------------------------------------------------
  > imputador: dropna
  > imputador: simple_mean
     ok ridge_regression           mae=0.1031  rmse=0.1486  r2=0.5888  [###########---------]
     ok random_forest              mae=0.0970  rmse=0.1413  r2=0.6282  [############--------]
     ok lightgbm                   mae=0.0986  rmse=0.1448  r2=0.6098  [############--------]
  > imputador: simple_median
     ok ridge_regression           mae=0.1029  rmse=0.1502  r2=0.5803  [###########---------]
     ok random_forest              mae=0.0977  rmse=0.1415  r2=0.6275  [############--------]
     ok lightgbm                   mae=0.0963  rmse=0.1413  r2=0.6283  [############--------]
  > imputador: simple_freq
     ok ridge_regression           mae=0.1057  rmse=0.1523  r2=0.5680  [###########---------]
     ok random_forest              mae=0.0983  rmse=0.1426  r2=0.6213  [############--------]
     ok lightgbm                   mae=0.0988  rmse=0.1452  r2=0.6078  [############--------]
  > imputador: simple_const
     ok ridge_regression           mae=0.1131  rmse=0.1654  r2=0.4907  [#########-----------]
     ok random_forest              mae=0.1015  rmse=0.1520  r2=0.5697  [###########---------]
     ok lightgbm                   mae=0.0993  rmse=0.1489  r2=0.5873  [###########---------]
  > imputador: knn_3
     ok ridge_regression           mae=0.0982  rmse=0.1421  r2=0.6240  [############--------]
     ok random_forest              mae=0.0925  rmse=0.1387  r2=0.6418  [############--------]
     ok lightgbm                   mae=0.0916  rmse=0.1376  r2=0.6475  [############--------]
  > imputador: knn_5
     ok ridge_regression           mae=0.0977  rmse=0.1409  r2=0.6305  [############--------]
     ok random_forest              mae=0.0938  rmse=0.1402  r2=0.6341  [############--------]
     ok lightgbm                   mae=0.0928  rmse=0.1420  r2=0.6250  [############--------]
  > imputador: knn_7
     ok ridge_regression           mae=0.0959  rmse=0.1409  r2=0.6306  [############--------]
     ok random_forest              mae=0.0928  rmse=0.1382  r2=0.6448  [############--------]
     ok lightgbm                   mae=0.0903  rmse=0.1368  r2=0.6515  [#############-------]
  > imputador: iterative
     ok ridge_regression           mae=0.0960  rmse=0.1372  r2=0.6495  [############--------]
     ok random_forest              mae=0.0941  rmse=0.1395  r2=0.6379  [############--------]
     ok lightgbm                   mae=0.0903  rmse=0.1363  r2=0.6541  [#############-------]
  > imputador: miceforest
[miceforest] 122 colunas → usando top-50 por variância
  [miceforest] fallback SimpleImputer (AssertionError)
     ok ridge_regression           mae=0.1031  rmse=0.1486  r2=0.5888  [###########---------]
     ok random_forest              mae=0.0970  rmse=0.1413  r2=0.6282  [############--------]
     ok lightgbm                   mae=0.0986  rmse=0.1448  r2=0.6098  [############--------]

  EXPERIMENTO  MAR   1%  [communities_crime]
  --------------------------------------------------
  > imputador: dropna
     ok ridge_regression           mae=0.2105  rmse=0.2873  r2=-0.1150  [--------------------]
     ok random_forest              mae=0.1353  rmse=0.1665  r2=0.6256  [############--------]
     ok lightgbm                   mae=0.1404  rmse=0.1909  r2=0.5078  [##########----------]
  > imputador: simple_mean
     ok ridge_regression           mae=0.0975  rmse=0.1423  r2=0.6232  [############--------]
     ok random_forest              mae=0.0947  rmse=0.1392  r2=0.6395  [############--------]
     ok lightgbm                   mae=0.0910  rmse=0.1359  r2=0.6562  [#############-------]
  > imputador: simple_median
     ok ridge_regression           mae=0.0984  rmse=0.1428  r2=0.6203  [############--------]
     ok random_forest              mae=0.0949  rmse=0.1397  r2=0.6369  [############--------]
     ok lightgbm                   mae=0.0903  rmse=0.1381  r2=0.6452  [############--------]
  > imputador: simple_freq
     ok ridge_regression           mae=0.0989  rmse=0.1435  r2=0.6170  [############--------]
     ok random_forest              mae=0.0960  rmse=0.1419  r2=0.6250  [############--------]
     ok lightgbm                   mae=0.0911  rmse=0.1380  r2=0.6454  [############--------]
  > imputador: simple_const
     ok ridge_regression           mae=0.1001  rmse=0.1442  r2=0.6132  [############--------]
     ok random_forest              mae=0.0968  rmse=0.1432  r2=0.6181  [############--------]
     ok lightgbm                   mae=0.0902  rmse=0.1392  r2=0.6392  [############--------]
  > imputador: knn_3
     ok ridge_regression           mae=0.0951  rmse=0.1401  r2=0.6347  [############--------]
     ok random_forest              mae=0.0932  rmse=0.1400  r2=0.6350  [############--------]
     ok lightgbm                   mae=0.0878  rmse=0.1338  r2=0.6667  [#############-------]
  > imputador: knn_5
     ok ridge_regression           mae=0.0963  rmse=0.1421  r2=0.6239  [############--------]
     ok random_forest              mae=0.0938  rmse=0.1401  r2=0.6349  [############--------]
     ok lightgbm                   mae=0.0943  rmse=0.1441  r2=0.6135  [############--------]
  > imputador: knn_7
     ok ridge_regression           mae=0.0964  rmse=0.1417  r2=0.6265  [############--------]
     ok random_forest              mae=0.0940  rmse=0.1396  r2=0.6373  [############--------]
     ok lightgbm                   mae=0.0936  rmse=0.1437  r2=0.6156  [############--------]
  > imputador: iterative
     ok ridge_regression           mae=0.0965  rmse=0.1422  r2=0.6239  [############--------]
     ok random_forest              mae=0.0943  rmse=0.1408  r2=0.6313  [############--------]
     ok lightgbm                   mae=0.0912  rmse=0.1400  r2=0.6351  [############--------]
  > imputador: miceforest
[miceforest] 122 colunas → usando top-50 por variância
  [miceforest] fallback SimpleImputer (AssertionError)
     ok ridge_regression           mae=0.0975  rmse=0.1423  r2=0.6232  [############--------]
     ok random_forest              mae=0.0947  rmse=0.1392  r2=0.6395  [############--------]
     ok lightgbm                   mae=0.0910  rmse=0.1359  r2=0.6562  [#############-------]

  EXPERIMENTO  MAR   5%  [communities_crime]
  --------------------------------------------------
  > imputador: dropna
  > imputador: simple_mean
     ok ridge_regression           mae=0.0989  rmse=0.1421  r2=0.6244  [############--------]
     ok random_forest              mae=0.0967  rmse=0.1410  r2=0.6300  [############--------]
     ok lightgbm                   mae=0.0926  rmse=0.1408  r2=0.6310  [############--------]
  > imputador: simple_median
     ok ridge_regression           mae=0.0986  rmse=0.1412  r2=0.6290  [############--------]
     ok random_forest              mae=0.0971  rmse=0.1430  r2=0.6194  [############--------]
     ok lightgbm                   mae=0.0938  rmse=0.1419  r2=0.6255  [############--------]
  > imputador: simple_freq
     ok ridge_regression           mae=0.0979  rmse=0.1410  r2=0.6298  [############--------]
     ok random_forest              mae=0.0980  rmse=0.1447  r2=0.6105  [############--------]
     ok lightgbm                   mae=0.0948  rmse=0.1453  r2=0.6070  [############--------]
  > imputador: simple_const
     ok ridge_regression           mae=0.1030  rmse=0.1476  r2=0.5944  [###########---------]
     ok random_forest              mae=0.0947  rmse=0.1404  r2=0.6332  [############--------]
     ok lightgbm                   mae=0.0931  rmse=0.1417  r2=0.6262  [############--------]
  > imputador: knn_3
     ok ridge_regression           mae=0.0952  rmse=0.1374  r2=0.6484  [############--------]
     ok random_forest              mae=0.0952  rmse=0.1406  r2=0.6319  [############--------]
     ok lightgbm                   mae=0.0918  rmse=0.1382  r2=0.6444  [############--------]
  > imputador: knn_5
     ok ridge_regression           mae=0.0951  rmse=0.1379  r2=0.6462  [############--------]
     ok random_forest              mae=0.0933  rmse=0.1408  r2=0.6309  [############--------]
     ok lightgbm                   mae=0.0936  rmse=0.1420  r2=0.6249  [############--------]
  > imputador: knn_7
     ok ridge_regression           mae=0.0960  rmse=0.1383  r2=0.6442  [############--------]
     ok random_forest              mae=0.0962  rmse=0.1420  r2=0.6246  [############--------]
     ok lightgbm                   mae=0.0931  rmse=0.1389  r2=0.6407  [############--------]
  > imputador: iterative
     ok ridge_regression           mae=0.0959  rmse=0.1421  r2=0.6242  [############--------]
     ok random_forest              mae=0.0954  rmse=0.1409  r2=0.6307  [############--------]
     ok lightgbm                   mae=0.0950  rmse=0.1397  r2=0.6367  [############--------]
  > imputador: miceforest
[miceforest] 122 colunas → usando top-50 por variância
  [miceforest] fallback SimpleImputer (AssertionError)
     ok ridge_regression           mae=0.0989  rmse=0.1421  r2=0.6244  [############--------]
     ok random_forest              mae=0.0967  rmse=0.1410  r2=0.6300  [############--------]
     ok lightgbm                   mae=0.0926  rmse=0.1408  r2=0.6310  [############--------]

  EXPERIMENTO  MAR  10%  [communities_crime]
  --------------------------------------------------
  > imputador: dropna
  > imputador: simple_mean
     ok ridge_regression           mae=0.1031  rmse=0.1484  r2=0.5903  [###########---------]
     ok random_forest              mae=0.0964  rmse=0.1429  r2=0.6199  [############--------]
     ok lightgbm                   mae=0.0952  rmse=0.1447  r2=0.6103  [############--------]
  > imputador: simple_median
     ok ridge_regression           mae=0.1040  rmse=0.1502  r2=0.5803  [###########---------]
     ok random_forest              mae=0.0952  rmse=0.1428  r2=0.6205  [############--------]
     ok lightgbm                   mae=0.0927  rmse=0.1411  r2=0.6292  [############--------]
  > imputador: simple_freq
     ok ridge_regression           mae=0.1033  rmse=0.1498  r2=0.5825  [###########---------]
     ok random_forest              mae=0.0956  rmse=0.1430  r2=0.6193  [############--------]
     ok lightgbm                   mae=0.0910  rmse=0.1410  r2=0.6298  [############--------]
  > imputador: simple_const
     ok ridge_regression           mae=0.1033  rmse=0.1488  r2=0.5878  [###########---------]
     ok random_forest              mae=0.0963  rmse=0.1427  r2=0.6211  [############--------]
     ok lightgbm                   mae=0.0933  rmse=0.1430  r2=0.6196  [############--------]
  > imputador: knn_3
     ok ridge_regression           mae=0.0985  rmse=0.1423  r2=0.6229  [############--------]
     ok random_forest              mae=0.0958  rmse=0.1423  r2=0.6231  [############--------]
     ok lightgbm                   mae=0.0911  rmse=0.1397  r2=0.6365  [############--------]
  > imputador: knn_5
     ok ridge_regression           mae=0.0987  rmse=0.1423  r2=0.6230  [############--------]
     ok random_forest              mae=0.0968  rmse=0.1418  r2=0.6259  [############--------]
     ok lightgbm                   mae=0.0949  rmse=0.1439  r2=0.6143  [############--------]
  > imputador: knn_7
     ok ridge_regression           mae=0.0992  rmse=0.1432  r2=0.6182  [############--------]
     ok random_forest              mae=0.0938  rmse=0.1398  r2=0.6363  [############--------]
     ok lightgbm                   mae=0.0923  rmse=0.1415  r2=0.6271  [############--------]
  > imputador: iterative
     ok ridge_regression           mae=0.0963  rmse=0.1383  r2=0.6441  [############--------]
     ok random_forest              mae=0.0947  rmse=0.1406  r2=0.6321  [############--------]
     ok lightgbm                   mae=0.0921  rmse=0.1425  r2=0.6222  [############--------]
  > imputador: miceforest
[miceforest] 122 colunas → usando top-50 por variância
  [miceforest] fallback SimpleImputer (AssertionError)
     ok ridge_regression           mae=0.1031  rmse=0.1484  r2=0.5903  [###########---------]
     ok random_forest              mae=0.0964  rmse=0.1429  r2=0.6199  [############--------]
     ok lightgbm                   mae=0.0952  rmse=0.1447  r2=0.6103  [############--------]

  EXPERIMENTO  MAR  15%  [communities_crime]
  --------------------------------------------------
  > imputador: dropna
  > imputador: simple_mean
     ok ridge_regression           mae=0.1006  rmse=0.1475  r2=0.5949  [###########---------]
     ok random_forest              mae=0.0956  rmse=0.1442  r2=0.6131  [############--------]
     ok lightgbm                   mae=0.0984  rmse=0.1502  r2=0.5799  [###########---------]
  > imputador: simple_median
     ok ridge_regression           mae=0.0995  rmse=0.1482  r2=0.5914  [###########---------]
     ok random_forest              mae=0.0980  rmse=0.1451  r2=0.6079  [############--------]
     ok lightgbm                   mae=0.0971  rmse=0.1473  r2=0.5962  [###########---------]
  > imputador: simple_freq
     ok ridge_regression           mae=0.1002  rmse=0.1493  r2=0.5853  [###########---------]
     ok random_forest              mae=0.0976  rmse=0.1452  r2=0.6077  [############--------]
     ok lightgbm                   mae=0.0969  rmse=0.1484  r2=0.5903  [###########---------]
  > imputador: simple_const
     ok ridge_regression           mae=0.1007  rmse=0.1515  r2=0.5726  [###########---------]
     ok random_forest              mae=0.0992  rmse=0.1470  r2=0.5976  [###########---------]
     ok lightgbm                   mae=0.0965  rmse=0.1461  r2=0.6027  [############--------]
  > imputador: knn_3
     ok ridge_regression           mae=0.0951  rmse=0.1398  r2=0.6361  [############--------]
     ok random_forest              mae=0.0966  rmse=0.1411  r2=0.6293  [############--------]
     ok lightgbm                   mae=0.0938  rmse=0.1423  r2=0.6234  [############--------]
  > imputador: knn_5
     ok ridge_regression           mae=0.0949  rmse=0.1413  r2=0.6282  [############--------]
     ok random_forest              mae=0.0968  rmse=0.1420  r2=0.6249  [############--------]
     ok lightgbm                   mae=0.0935  rmse=0.1396  r2=0.6374  [############--------]
  > imputador: knn_7
     ok ridge_regression           mae=0.0974  rmse=0.1437  r2=0.6157  [############--------]
     ok random_forest              mae=0.0973  rmse=0.1422  r2=0.6237  [############--------]
     ok lightgbm                   mae=0.0952  rmse=0.1426  r2=0.6214  [############--------]
  > imputador: iterative
     ok ridge_regression           mae=0.0960  rmse=0.1414  r2=0.6277  [############--------]
     ok random_forest              mae=0.0957  rmse=0.1419  r2=0.6250  [############--------]
     ok lightgbm                   mae=0.0917  rmse=0.1395  r2=0.6377  [############--------]
  > imputador: miceforest
[miceforest] 122 colunas → usando top-50 por variância
  [miceforest] fallback SimpleImputer (AssertionError)
     ok ridge_regression           mae=0.1006  rmse=0.1475  r2=0.5949  [###########---------]
     ok random_forest              mae=0.0956  rmse=0.1442  r2=0.6131  [############--------]
     ok lightgbm                   mae=0.0984  rmse=0.1502  r2=0.5799  [###########---------]

  EXPERIMENTO  MAR  20%  [communities_crime]
  --------------------------------------------------
  > imputador: dropna
  > imputador: simple_mean
     ok ridge_regression           mae=0.1050  rmse=0.1491  r2=0.5864  [###########---------]
     ok random_forest              mae=0.0974  rmse=0.1431  r2=0.6187  [############--------]
     ok lightgbm                   mae=0.0961  rmse=0.1452  r2=0.6074  [############--------]
  > imputador: simple_median
     ok ridge_regression           mae=0.1045  rmse=0.1482  r2=0.5912  [###########---------]
     ok random_forest              mae=0.0971  rmse=0.1411  r2=0.6295  [############--------]
     ok lightgbm                   mae=0.0934  rmse=0.1426  r2=0.6216  [############--------]
  > imputador: simple_freq
     ok ridge_regression           mae=0.1044  rmse=0.1484  r2=0.5901  [###########---------]
     ok random_forest              mae=0.0992  rmse=0.1438  r2=0.6154  [############--------]
     ok lightgbm                   mae=0.0977  rmse=0.1460  r2=0.6033  [############--------]

100%|██████████| 12/12 [18:48:03<00:00, 5640.27s/it]

     ok lightgbm                   mae=0.0933  rmse=0.1396  r2=0.6371  [############--------]
  > imputador: miceforest
[miceforest] 122 colunas → usando top-50 por variância
  [miceforest] fallback SimpleImputer (AssertionError)

[ERRO] key=communities_crime seed=456: Shape of passed values is (1595, 71), indices imply (1595, 72)

CSV detalhado salvo: data\all_results.csv  (5574 linhas)
CSV resumo (média±std) salvo: data\summary_results.csv

=== Classificacao (baseline, média 3 sementes) ===

          dataset          model  accuracy  macro_f1  weighted_f1
2           adult  random_forest    0.8551    0.7875       0.8500
5  bank_marketing  random_forest    0.9037    0.6989       0.8891

Salvo em: data\classification_summary.csv

=== Regressao (baseline, média 3 sementes) ===

             dataset          model     mae    rmse      r2
1    air_quality_uci  random_forest  0.0157  0.1150  0.9998
3  communities_crime       lightgbm  0.0912  0.1366  0.6300

Salvo em: data\regression_summary.csv